const fs = require("fs");
const path = require("path");
const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "vectors", "typeschema.json"), "utf8"));
const modelOrder = Object.keys(schema);
function toCamel(n) { return n.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase()); }
function toPascal(n) { const c = toCamel(n); return c.charAt(0).toUpperCase() + c.slice(1); }

var Q = String.raw`\"`;

function ktScalar(type, acc) {
  if (type === "string") return "_ds(" + acc + ")";
  if (type === "boolean") return "if(" + acc + ")\"true\" else \"false\"";
  if (type === "int64") return "_di(" + acc + ")";
  if (type === "uint64") return "_du(" + acc + ")";
  if (type === "float32") return "_dn(" + acc + ".toDouble())";
  if (type === "float64") return "_dn(" + acc + ")";
  return acc + ".toString()";
}
function ktAdd(fn, expr) {
  return '    parts.add("' + Q + fn + Q + ':"+' + expr + ')';
}
function ktAddArr(fn) {
  return '    parts.add("' + Q + fn + Q + ':"+"["+_a+"]")';
}
function ktAddBytes(fn, acc) {
  return '    parts.add("' + Q + fn + Q + ':"+' + '"' + Q + '"' + '+_db(' + acc + ')+' + '"' + Q + '"' + ')';
}

function dartScalar(type, acc) {
  if (type === "string") return "_ds(" + acc + ")";
  if (type === "boolean") return acc + "?\"true\":\"false\"";
  if (type === "int64") return "_di(" + acc + ")";
  if (type === "uint64") return "_du(" + acc + ")";
  if (type === "float32" || type === "float64") return "_dn(" + acc + ")";
  return acc + ".toString()";
}
function dartAdd(fn, expr) {
  return "    parts.add('\"" + fn + "\":'+" + expr + ");";
}
function dartAddArr(fn) {
  return "    parts.add('\"" + fn + "\":['+_a+']');";
}
function dartAddBytes(fn, acc) {
  return "    parts.add('\"" + fn + "\":\"'+" + "_db(" + acc + ")+" + "'\"');";
}

function swiftScalar(type, acc) {
  if (type === "string") return "_ds(" + acc + ")";
  if (type === "boolean") return acc + "?\"true\":\"false\"";
  if (type === "int64") return "_di(" + acc + ")";
  if (type === "uint64") return "_du(" + acc + ")";
  if (type === "float32") return "_dn(Double(" + acc + "))";
  if (type === "float64") return "_dn(" + acc + ")";
  return "String(" + acc + ")";
}
function swiftAdd(fn, expr) {
  return '    parts.append("' + Q + fn + Q + ':"+' + expr + ')';
}
function swiftAddArr(fn) {
  return '    parts.append("' + Q + fn + Q + ':"+"["+_a+"]")';
}
function swiftAddBytes(fn, acc) {
  return '    parts.append("' + Q + fn + Q + ':"+' + '"' + Q + '"' + '+_db(' + acc + ')+' + '"' + Q + '"' + ')';
}

function ktMapExpr(f, acc) {
  if (f.isModel) return acc + ".map { x -> dump" + f.type + "(x) }.joinToString(\",\")";
  if (f.type === "bytes") return acc + ".map { x -> " + '"' + Q + '"' + "+_db(x)+" + '"' + Q + '"' + " }.joinToString(\",\")";
  return acc + ".map { x -> " + ktScalar(f.type, "x") + " }.joinToString(\",\")";
}
function dartMapExpr(f, acc) {
  if (f.isModel) return acc + ".map((x) => dump" + f.type + "(x)).join(',')";
  if (f.type === "bytes") return acc + ".map((x) => '\"' + _db(x) + '\"').join(',')";
  return acc + ".map((x) => " + dartScalar(f.type, "x") + ").join(',')";
}
function swiftMapExpr(f, acc) {
  if (f.isModel) return acc + ".map { x in dump" + f.type + "(x) }.joined(separator: \",\")";
  if (f.type === "bytes") return acc + ".map { x in " + '"' + Q + '"' + "+_db(x)+" + '"' + Q + '"' + " }.joined(separator: \",\")";
  return acc + ".map { x in " + swiftScalar(f.type, "x") + " }.joined(separator: \",\")";
}

function generateKotlin() {
  var L = [];
  L.push("// Generated by gen_dump_three.cjs. DO NOT EDIT.");
  L.push("package alltypes");
  L.push("");
  L.push("import java.util.Base64");
  L.push("");
  L.push("fun _ds(v: String): String {");
  L.push("    val b = StringBuilder()");
  L.push("    b.append('\"')");
  L.push("    for (c in v) {");
  L.push("        when (c) {");
  L.push("            '\"' -> b.append(" + '"' + String.raw`\\\"` + '"' + ")");
  L.push("            '\\\\' -> b.append(" + '"' + String.raw`\\\\` + '"' + ")");
  L.push("            '\\n' -> b.append(" + '"' + String.raw`\\n` + '"' + ")");
  L.push("            '\\t' -> b.append(" + '"' + String.raw`\\t` + '"' + ")");
  L.push("            '\\r' -> b.append(" + '"' + String.raw`\\r` + '"' + ")");
  L.push("            else -> if (c.code < 0x20) b.append(String.format(" + '"' + String.raw`\\u%04x` + '"' + ", c.code)) else b.append(c)");
  L.push("        }");
  L.push("    }");
  L.push("    b.append('\"')");
  L.push("    return b.toString()");
  L.push("}");
  L.push("");
  L.push("fun _dn(v: Double): String {");
  L.push("    if (v == 0.0 && java.lang.Double.doubleToRawLongBits(v) < 0) return \"-0\"");
  L.push("    val s = v.toString()");
  L.push("    if ('.' in s || 'E' in s || 'e' in s || s == \"Infinity\" || s == \"-Infinity\" || s == \"NaN\") {");
  L.push("        if (s.endsWith(\".0\")) return s.dropLast(2)");
  L.push("        return s");
  L.push("    }");
  L.push("    return s");
  L.push("}");
  L.push("");
  L.push("fun _di(v: Long): String = " + '"' + Q + '"' + " + v.toString() + " + '"' + Q + '"');
  L.push("");
  L.push("fun _du(v: ULong): String = " + '"' + Q + '"' + " + v.toString() + " + '"' + Q + '"');
  L.push("");
  L.push("fun _db(v: ByteArray): String = Base64.getEncoder().encodeToString(v)");
  L.push("");

  for (const name of modelOrder) {
    var m = schema[name], cn = toPascal(name);
    L.push("fun dump" + cn + "(o: " + cn + "): String {");
    L.push("    val parts = mutableListOf<String>()");
    for (var f of m.fields) {
      var camel = toCamel(f.name), acc = "o." + camel;
      if (f.isArray) {
        var me = ktMapExpr(f, f.optional ? acc + "!!" : acc);
        if (f.optional) {
          L.push("    if (" + acc + " != null) {");
          L.push("        val _a = " + me);
          L.push(ktAddArr(f.name).replace("    ", "        "));
          L.push("    }");
        } else {
          L.push("    run {");
          L.push("        val _a = " + me);
          L.push(ktAddArr(f.name).replace("    ", "        "));
          L.push("    }");
        }
      } else if (f.isModel) {
        var val = f.optional ? acc + "!!" : acc;
        if (f.optional) {
          L.push("    if (" + acc + " != null) {");
          L.push(ktAdd(f.name, "dump" + f.type + "(" + val + ")").replace("    ", "        "));
          L.push("    }");
        } else {
          L.push(ktAdd(f.name, "dump" + f.type + "(" + val + ")"));
        }
      } else if (f.type === "bytes") {
        var bacc = f.optional ? acc + "!!" : acc;
        if (f.optional) {
          L.push("    if (" + acc + " != null) {");
          L.push(ktAddBytes(f.name, bacc).replace("    ", "        "));
          L.push("    }");
        } else {
          L.push(ktAddBytes(f.name, bacc));
        }
      } else {
        var val = f.optional ? acc + "!!" : acc;
        if (f.optional) {
          L.push("    if (" + acc + " != null) {");
          L.push(ktAdd(f.name, ktScalar(f.type, val)).replace("    ", "        "));
          L.push("    }");
        } else {
          L.push(ktAdd(f.name, ktScalar(f.type, val)));
        }
      }
    }
    L.push("    return \"{\"+parts.joinToString(\",\")+\"}\"");
    L.push("}");
    L.push("");
  }
  return L.join("\n");
}

function generateDart() {
  var L = [];
  L.push("// Generated by gen_dump_three.cjs. DO NOT EDIT.");
  L.push("import 'dart:convert';");
  L.push("import 'dart:typed_data';");
  L.push("");
  L.push("String _ds(String v) {");
  L.push("  final b = StringBuffer();");
  L.push("  b.write('\"');");
  L.push("  for (final c in v.runes) {");
  L.push("    if (c == 0x22) {");
  L.push("      b.write(" + "'" + String.raw`\\\"` + "'" + ");");
  L.push("    } else if (c == 0x5C) {");
  L.push("      b.write(" + "'" + String.raw`\\\\` + "'" + ");");
  L.push("    } else if (c == 0x0A) {");
  L.push("      b.write(" + "'" + String.raw`\\n` + "'" + ");");
  L.push("    } else if (c == 0x09) {");
  L.push("      b.write(" + "'" + String.raw`\\t` + "'" + ");");
  L.push("    } else if (c == 0x0D) {");
  L.push("      b.write(" + "'" + String.raw`\\r` + "'" + ");");
  L.push("    } else if (c < 0x20) {");
  L.push("      b.write(" + "'" + String.raw`\\u` + "'" + ");");
  L.push("      b.write(c.toRadixString(16).padLeft(4, '0'));");
  L.push("    } else {");
  L.push("      b.writeCharCode(c);");
  L.push("    }");
  L.push("  }");
  L.push("  b.write('\"');");
  L.push("  return b.toString();");
  L.push("}");
  L.push("");
  L.push("String _dn(double v) {");
  L.push("  if (v == 0.0 && (1 / v).isNegative) return '-0';");
  L.push("  final s = v.toString();");
  L.push("  if (s.contains('.') || s.contains('e') || s.contains('E')) {");
  L.push("    if (s.endsWith('.0')) return s.substring(0, s.length - 2);");
  L.push("    return s;");
  L.push("  }");
  L.push("  return s;");
  L.push("}");
  L.push("");
  L.push("String _di(int v) => '\"' + v.toString() + '\"';");
  L.push("");
  L.push("String _du(BigInt v) => '\"' + v.toString() + '\"';");
  L.push("");
  L.push("String _db(Uint8List v) => base64.encode(v);");
  L.push("");

  for (const name of modelOrder) {
    var m = schema[name], cn = toPascal(name);
    L.push("String dump" + cn + "(" + cn + " o) {");
    L.push("  final parts = <String>[];");
    for (var f of m.fields) {
      var camel = toCamel(f.name), acc = "o." + camel;
      if (f.isArray) {
        var me = dartMapExpr(f, f.optional ? acc + "!" : acc);
        if (f.optional) {
          L.push("  if (" + acc + " != null) {");
          L.push("    final _a = " + me + ";");
          L.push(dartAddArr(f.name));
          L.push("  }");
        } else {
          L.push("  {");
          L.push("    final _a = " + me + ";");
          L.push(dartAddArr(f.name));
          L.push("  }");
        }
      } else if (f.isModel) {
        var val = f.optional ? acc + "!" : acc;
        if (f.optional) {
          L.push("  if (" + acc + " != null) {");
          L.push(dartAdd(f.name, "dump" + f.type + "(" + val + ")"));
          L.push("  }");
        } else {
          L.push(dartAdd(f.name, "dump" + f.type + "(" + val + ")"));
        }
      } else if (f.type === "bytes") {
        var bacc = f.optional ? acc + "!" : acc;
        if (f.optional) {
          L.push("  if (" + acc + " != null) {");
          L.push(dartAddBytes(f.name, bacc));
          L.push("  }");
        } else {
          L.push(dartAddBytes(f.name, bacc));
        }
      } else {
        var val = f.optional ? acc + "!" : acc;
        if (f.optional) {
          L.push("  if (" + acc + " != null) {");
          L.push(dartAdd(f.name, dartScalar(f.type, val)));
          L.push("  }");
        } else {
          L.push(dartAdd(f.name, dartScalar(f.type, val)));
        }
      }
    }
    L.push("  return '{' + parts.join(',') + '}';");
    L.push("}");
    L.push("");
  }
  return L.join("\n");
}

function generateSwift() {
  var L = [];
  L.push("// Generated by gen_dump_three.cjs. DO NOT EDIT.");
  L.push("import Foundation");
  L.push("");
  L.push("func _ds(_ v: String) -> String {");
  L.push("    var r = \"\"");
  L.push("    r.append(" + '"' + String.raw`\"` + '"' + ")");
  L.push("    for c in v {");
  L.push("        switch c {");
  L.push("        case " + '"' + String.raw`\"` + '"' + ": r.append(" + '"' + String.raw`\\\"` + '"' + ")");
  L.push("        case " + '"' + String.raw`\\` + '"' + ": r.append(" + '"' + String.raw`\\\\` + '"' + ")");
  L.push("        case " + '"' + String.raw`\n` + '"' + ": r.append(" + '"' + String.raw`\\n` + '"' + ")");
  L.push("        case " + '"' + String.raw`\t` + '"' + ": r.append(" + '"' + String.raw`\\t` + '"' + ")");
  L.push("        case " + '"' + String.raw`\r` + '"' + ": r.append(" + '"' + String.raw`\\r` + '"' + ")");
  L.push("        default:");
  L.push("            let sv = String(c)");
  L.push("            if let code = c.utf16.first, code < 0x20 {");
  L.push("                r.append(String(format: " + '"' + String.raw`\\u%04x` + '"' + ", code))");
  L.push("            } else {");
  L.push("                r.append(sv)");
  L.push("            }");
  L.push("        }");
  L.push("    }");
  L.push("    r.append(" + '"' + String.raw`\"` + '"' + ")");
  L.push("    return r");
  L.push("}");
  L.push("");
  L.push("func _dn(_ v: Double) -> String {");
  L.push("    if v == 0.0 && v.sign == .minus { return \"-0\" }");
  L.push("    let s = String(v)");
  L.push("    if s.contains(\".\") {");
  L.push("        if s.hasSuffix(\".0\") { return String(s.dropLast(2)) }");
  L.push("        return s");
  L.push("    }");
  L.push("    return s");
  L.push("}");
  L.push("");
  L.push("func _di(_ v: Int64) -> String { " + '"' + Q + '"' + " + String(v) + " + '"' + Q + '"' + " }");
  L.push("");
  L.push("func _du(_ v: UInt64) -> String { " + '"' + Q + '"' + " + String(v) + " + '"' + Q + '"' + " }");
  L.push("");
  L.push("func _db(_ v: Data) -> String { v.base64EncodedString() }");
  L.push("");

  for (const name of modelOrder) {
    var m = schema[name], cn = toPascal(name);
    L.push("func dump" + cn + "(_ o: " + cn + ") -> String {");
    L.push("    var parts: [String] = []");
    for (var f of m.fields) {
      var camel = toCamel(f.name), acc = "o." + camel;
      if (f.isArray) {
        if (f.optional) {
          var me = swiftMapExpr(f, "_v");
          L.push("    if let _v = " + acc + " {");
          L.push("        let _a = " + me);
          L.push(swiftAddArr(f.name).replace("    ", "        "));
          L.push("    }");
        } else {
          var me = swiftMapExpr(f, acc);
          L.push("    do {");
          L.push("        let _a = " + me);
          L.push(swiftAddArr(f.name).replace("    ", "        "));
          L.push("    }");
        }
      } else if (f.isModel) {
        if (f.optional) {
          L.push("    if let v = " + acc + " {");
          L.push(swiftAdd(f.name, "dump" + f.type + "(v)").replace("    ", "        "));
          L.push("    }");
        } else {
          L.push(swiftAdd(f.name, "dump" + f.type + "(" + acc + ")"));
        }
      } else if (f.type === "bytes") {
        if (f.optional) {
          L.push("    if let v = " + acc + " {");
          L.push(swiftAddBytes(f.name, "v").replace("    ", "        "));
          L.push("    }");
        } else {
          L.push(swiftAddBytes(f.name, acc));
        }
      } else {
        if (f.optional) {
          L.push("    if let v = " + acc + " {");
          L.push(swiftAdd(f.name, swiftScalar(f.type, "v")).replace("    ", "        "));
          L.push("    }");
        } else {
          L.push(swiftAdd(f.name, swiftScalar(f.type, acc)));
        }
      }
    }
    L.push("    return \"{\"+parts.joined(separator: \",\")+\"}\"");
    L.push("}");
    L.push("");
  }
  return L.join("\n");
}

var ktDir = path.join(__dirname, "emit_kotlin", "src");
var dartDir = path.join(__dirname, "emit_dart", "bin");
var swiftDir = path.join(__dirname, "emit_swift", "Sources", "run_swift");
fs.mkdirSync(ktDir, { recursive: true });
fs.mkdirSync(dartDir, { recursive: true });
fs.mkdirSync(swiftDir, { recursive: true });

var kt = generateKotlin();
var dart = generateDart();
var swift = generateSwift();
fs.writeFileSync(path.join(ktDir, "dump_emit.kt"), kt);
fs.writeFileSync(path.join(dartDir, "dump_emit.dart"), dart);
fs.writeFileSync(path.join(swiftDir, "dump_emit.swift"), swift);
console.log("Kotlin:", kt.length, "Dart:", dart.length, "Swift:", swift.length, "Models:", modelOrder.length);
