import { FieldDef, ModelDef, models } from '../gen.ts';
import { getDumpFnName } from '../field-naming.ts';

export function generateDartDump(): string {
  const dumpFunctions = Object.entries(models).map(([name, m]) => 
    dartDumpFunction(name, m)
  ).join('\n');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
import 'dart:convert';
import 'dart:typed_data';
import '../lib/test_service_types.dart';

String _ds(String v) {
  final b = StringBuffer();
  b.write('"');
  for (final c in v.runes) {
    if (c == 0x22) b.write('\\\\"');
    else if (c == 0x5C) b.write('\\\\\\\\');
    else if (c == 0x0A) b.write('\\\\n');
    else if (c == 0x09) b.write('\\\\t');
    else if (c == 0x0D) b.write('\\\\r');
    else if (c < 0x20) b.write('\\\\u' + c.toRadixString(16).padLeft(4, '0'));
    else b.writeCharCode(c);
  }
  b.write('"');
  return b.toString();
}

String _dn(double v) {
  if (v == 0.0 && (1 / v).isNegative) return '-0';
  final s = v.toString();
  if (s.endsWith('.0')) return s.substring(0, s.length - 2);
  return s;
}

String _di(BigInt v) => '"' + v.toString() + '"';
String _du(BigInt v) => '"' + v.toString() + '"';
String _db(Uint8List v) => base64.encode(v);

${dumpFunctions}
`;
}

function dartDumpFunction(name: string, m: ModelDef): string {
  const fn = `dump${name}`;
  const lines: string[] = [];
  
  for (const field of m.fields) {
    lines.push(dartFieldLine(field));
  }
  
  const body = lines.length === 0 
    ? "  return '{}';"
    : `  final parts = <String>[];
${lines.join('\n')}
  return '{' + parts.join(',') + '}';`;
  
  return `String ${fn}(${name} o) {
${body}
}`;
}

function dartFieldLine(field: FieldDef): string {
  const expr = dartValueExpr(field, `o.${field.name}`);
  
  if (field.optional) {
    const derefExpr = dartValueExpr(field, `o.${field.name}!`);
    return `  if (o.${field.name} != null) { parts.add('"${field.name}":' + ${derefExpr}); }`;
  }
  
  return `  parts.add('"${field.name}":' + ${expr});`;
}

function dartValueExpr(field: FieldDef, expr: string): string {
  if (field.isArray) {
    if (field.isModel) {
      return `'[' + ${expr}.map((e) => dump${field.type}(e)).join(',') + ']'`;
    }
    if (field.type === 'string') {
      return `'[' + ${expr}.map((e) => _ds(e)).join(',') + ']'`;
    }
    if (field.type === 'boolean') {
      return `'[' + ${expr}.map((e) => e ? 'true' : 'false').join(',') + ']'`;
    }
    if (field.type === 'bytes') {
      return `'[' + ${expr}.map((e) => '"'+_db(e)+'"').join(',') + ']'`;
    }
    if (field.type === 'int64') {
      return `'[' + ${expr}.map((e) => _di(e)).join(',') + ']'`;
    }
    if (field.type === 'uint64') {
      return `'[' + ${expr}.map((e) => _du(e)).join(',') + ']'`;
    }
    if (field.type === 'float32' || field.type === 'float64') {
      return `'[' + ${expr}.map((e) => _dn(e)).join(',') + ']'`;
    }
    return `'[' + ${expr}.map((e) => e.toString()).join(',') + ']'`;
  }
  
  if (field.isModel) {
    return `dump${field.type}(${expr})`;
  }
  
  if (field.type === 'string') {
    return `_ds(${expr})`;
  }
  if (field.type === 'boolean') {
    return `(${expr} ? 'true' : 'false')`;
  }
  if (field.type === 'bytes') {
    return `'"' + _db(${expr}) + '"'`;
  }
  if (field.type === 'int64') {
    return `_di(${expr})`;
  }
  if (field.type === 'uint64') {
    return `_du(${expr})`;
  }
  if (field.type === 'float32' || field.type === 'float64') {
    return `_dn(${expr})`;
  }
  
  return `${expr}.toString()`;
}