import { FieldDef, ModelDef, models } from '../gen.ts';
import { toGoField, getDumpFnName } from '../field-naming.ts';

export function generateGoDump(): string {
  const dumpFunctions = Object.entries(models).map(([name, m]) => 
    goDumpFunction(name, m)
  ).join('\n');
  
return `// Generated by gen_types.cjs. DO NOT EDIT.
package main

import (
	"encoding/base64"
	"fmt"
	"math"
	"strconv"
	"strings"
	. "test/emit_gen"
)

func _ds(v string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(v); i++ {
		c := v[i]
		switch c {
		case 0x22: b.WriteString("\\\\\\"")
		case 0x5c: b.WriteString("\\\\\\\\")
		case 0x0a: b.WriteString("\\\\n")
		case 0x09: b.WriteString("\\\\t")
		case 0x0d: b.WriteString("\\\\r")
		default:
			if c < 0x20 { b.WriteString(fmt.Sprintf("\\\\u%04x", c)) } else { b.WriteByte(c) }
		}
	}
	b.WriteByte('"')
	return b.String()
}

func _dn(v float64) string {
	if v == 0 && math.Signbit(v) { return "-0" }
	s := strconv.FormatFloat(v, 'f', -1, 64)
	if strings.HasSuffix(s, ".0") { return s[:len(s)-2] }
	return s
}

func _di(v int64) string { return "\\\"" + strconv.FormatInt(v, 10) + "\\\"" }
func _du(v uint64) string { return "\\\"" + strconv.FormatUint(v, 10) + "\\\"" }
func _db(v []byte) string { return base64.StdEncoding.EncodeToString(v) }

${dumpFunctions}
`;
}

function goDumpFunction(name: string, m: ModelDef): string {
  const fn = `dump${name}`;
  const lines: string[] = [];
  
  for (const field of m.fields) {
    const goField = toGoField(field.name);
    lines.push(goFieldLine(field, goField));
  }
  
  const body = lines.length === 0 
    ? '	return "{}"'
    : `	parts := []string{}
${lines.join('\n')}
	return "{"+strings.Join(parts, ",")+"}"`;
  
  return `func ${fn}(o ${name}) string {
${body}
}`;
}

function goFieldLine(field: FieldDef, goField: string): string {
  const expr = goValueExpr(field, `o.${goField}`, field.optional);
  
  if (field.optional) {
    // In Go, optional arrays/bytes are just slices (not pointers), so don't dereference
    if (field.isArray || field.type === 'bytes') {
      return `	if o.${goField} != nil { parts = append(parts, "\\\"${field.name}\\":"+${expr}) }`;
    }
    const derefExpr = goValueExpr(field, `*o.${goField}`, false);
    return `	if o.${goField} != nil { parts = append(parts, "\\\"${field.name}\\":"+${derefExpr}) }`;
  }
  
  return `	parts = append(parts, "\\\"${field.name}\\":"+${expr})`;
}

function goValueExpr(field: FieldDef, expr: string, optional: boolean): string {
  if (field.isArray) {
    if (field.isModel) {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, dump${field.type}(e)) }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'string') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'boolean') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, func() string { if e { return "true" }; return "false" }()) }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'bytes') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, "\\\""+_db(e)+"\\\"") }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'int64') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, _di(e)) }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'uint64') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, _du(e)) }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'float32') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]"`;
    }
    if (field.type === 'float64') {
      return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, _dn(e)) }; return arr }(), ",")+"]"`;
    }
    return `"["+strings.Join(func() []string { var arr []string; for _, e := range ${expr} { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]"`;
  }
  
  if (field.isModel) {
    return `dump${field.type}(${expr})`;
  }
  
  if (field.type === 'string') {
    return `_ds(${expr})`;
  }
  if (field.type === 'boolean') {
    return `func() string { if ${expr} { return "true" }; return "false" }()`;
  }
  if (field.type === 'bytes') {
    return `"\\\""+_db(${expr})+"\\\""`;
  }
  if (field.type === 'int64') {
    return `_di(${expr})`;
  }
  if (field.type === 'uint64') {
    return `_du(${expr})`;
  }
  if (field.type === 'float32') {
    return `_dn(float64(${expr}))`;
  }
  if (field.type === 'float64') {
    return `_dn(${expr})`;
  }
  
  return `strconv.Itoa(int(${expr}))`;
}