import { FieldDef, ModelDef, models } from '../gen.ts';
import { getDumpFnName } from '../field-naming.ts';

export function generateKotlinDump(): string {
  const dumpFunctions = Object.entries(models).map(([name, m]) => 
    kotlinDumpFunction(name, m)
  ).join('\n');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
package alltypes
import java.util.Base64

fun _ds(v: String): String {
    val b = StringBuilder()
    b.append('"')
    for (c in v) {
        when (c) {
            '"' -> b.append("\\\\\\"")
            '\\\\' -> b.append("\\\\\\\\")
            '\\n' -> b.append("\\\\n")
            '\\t' -> b.append("\\\\t")
            '\\r' -> b.append("\\\\r")
            else -> if (c.code < 32) b.append("\\\\u%04x".format(c.code)) else b.append(c)
        }
    }
    b.append('"')
    return b.toString()
}

fun _dn(v: Double): String {
    if (v == 0.0 && v < 0) return "-0"
    val s = v.toString()
    return if (s.endsWith(".0")) s.dropLast(2) else s
}
fun _dnf(v: Float): String = _dn(v.toDouble())

fun _di(v: Long): String = "\\\"" + v.toString() + "\\\""
fun _du(v: ULong): String = "\\\"" + v.toString() + "\\\""
fun _db(v: ByteArray): String = Base64.getEncoder().encodeToString(v)

${dumpFunctions}
`;
}

function kotlinDumpFunction(name: string, m: ModelDef): string {
  const fn = `dump${name}`;
  const lines: string[] = [];
  
  for (const field of m.fields) {
    lines.push(kotlinFieldLine(field));
  }
  
  const body = lines.length === 0 
    ? '    return "{}"'
    : `    val parts = mutableListOf<String>()
${lines.join('\n')}
    return "{" + parts.joinToString(",") + "}"`;
  
  return `fun ${fn}(o: ${name}): String {
${body}
}`;
}

function kotlinFieldLine(field: FieldDef): string {
  let valExpr = kotlinValueExpr(field, `o.${field.name}`);
  let addQuotes = false;
  
  if (!field.isArray && field.type === 'bytes') {
    addQuotes = false;
    valExpr = `"\\\"" + _db(o.${field.name}) + "\\\""`;
  }
  
  if (field.optional) {
    const regex = new RegExp(`o\\.${field.name}`, 'g');
    const optValExpr = addQuotes ? `"\\\"" + ${valExpr.replace(regex, 'it')} + "\\\""` : valExpr.replace(regex, 'it');
    const keyPart = addQuotes ? `"\\\"${field.name}\\\":\\\""` : `"\\\"${field.name}\\":"`;
    return `    o.${field.name}?.let { parts.add(${keyPart} + ${optValExpr}) }`;
  }
  
  const quotedValExpr = addQuotes ? `"\\\"" + ${valExpr} + "\\\""` : valExpr;
  const keyPart = addQuotes ? `"\\\"${field.name}\\\":\\\""` : `"\\\"${field.name}\\":"`;
  return `    parts.add(${keyPart} + ${quotedValExpr})`;
}

function kotlinValueExpr(field: FieldDef, expr: string): string {
  if (field.isArray) {
    if (field.isModel) {
      return `${expr}.joinToString(",", "[", "]") { dump${field.type}(it) }`;
    }
    if (field.type === 'string') {
      return `${expr}.joinToString(",", "[", "]") { _ds(it) }`;
    }
    if (field.type === 'boolean') {
      return `${expr}.joinToString(",", "[", "]") { if (it) "true" else "false" }`;
    }
    if (field.type === 'bytes') {
      return `${expr}.joinToString(",", "[", "]") { "\\\""+_db(it)+"\\\"" }`;
    }
    if (field.type === 'int64') {
      return `${expr}.joinToString(",", "[", "]") { _di(it) }`;
    }
    if (field.type === 'uint64') {
      return `${expr}.joinToString(",", "[", "]") { _du(it) }`;
    }
    if (field.type === 'float32' || field.type === 'float64') {
      return field.type === 'float32' 
        ? `${expr}.joinToString(",", "[", "]") { _dnf(it) }`
        : `${expr}.joinToString(",", "[", "]") { _dn(it) }`;
    }
    return `${expr}.joinToString(",", "[", "]") { it.toString() }`;
  }
  
  if (field.isModel) {
    return `dump${field.type}(${expr})`;
  }
  
  if (field.type === 'string') {
    return `_ds(${expr})`;
  }
  if (field.type === 'boolean') {
    return `(if (${expr}) "true" else "false")`;
  }
  if (field.type === 'int64') {
    return `_di(${expr})`;
  }
  if (field.type === 'uint64') {
    return `_du(${expr})`;
  }
  if (field.type === 'float32' || field.type === 'float64') {
    return field.type === 'float32' ? `_dnf(${expr})` : `_dn(${expr})`;
  }
  
  return `${expr}.toString()`;
}