import { models } from '../gen.ts';

export function generatePyDump(): string {
  const schemaEntries = Object.entries(models).map(([name, m]) => {
    const fields = m.fields.map(f => {
      const parts = [`'n':'${f.name}'`, `'t':'${f.type}'`];
      if (f.optional) parts.push("'o':True");
      if (f.isArray) parts.push("'a':True");
      if (f.isModel) parts.push("'m':True");
      return `{${parts.join(',')}}`;
    }).join(',');
    return `'${name}':[${fields}]`;
  }).join(',');
  
  return `# Generated by gen_types.cjs. DO NOT EDIT.
import base64, json, math

_sch = {${schemaEntries}}

def _dn(v):
    if isinstance(v, float) and math.copysign(1, v) < 0 and v == 0:
        return '-0'
    if isinstance(v, float) and v == int(v) and not math.isinf(v):
        return str(int(v))
    return repr(v)

def _dv(v, f):
    if v is None:
        return 'null'
    if f.get('a'):
        return '[' + ','.join(_dv(e, {**f, 'a': False}) for e in v) + ']'
    if f.get('m'):
        return dump_model(f['t'], v)
    t = f['t']
    if t == 'string': return json.dumps(v)
    if t == 'boolean': return 'true' if v else 'false'
    if t in ('float32', 'float64'): return _dn(v)
    if t == 'int64': return '"' + str(v) + '"'
    if t == 'uint64': return '"' + str(v) + '"'
    if t == 'bytes': return '"' + base64.b64encode(v).decode() + '"'
    return str(v)

def dump_model(name, obj):
    fields = _sch.get(name)
    if fields is None:
        raise ValueError('unknown model: ' + name)
    parts = []
    for f in fields:
        v = getattr(obj, f['n'], None)
        if f.get('o') and v is None:
            continue
        parts.append('"' + f['n'] + '":' + _dv(v, f))
    return '{' + ','.join(parts) + '}'
`;
}