import { FieldDef, ModelDef, models } from '../gen.ts';
import { toSnakeRust, toRustDumpFn } from '../field-naming.ts';

export function generateRustDump(): string {
  const dumpFunctions = Object.entries(models).map(([name, m]) => 
    rustDumpFunction(name, m)
  ).join('\n');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
use std::fmt::Write;

fn _ds(v: &str) -> String {
    let mut r = String::new();
    r.push('"');
    for c in v.chars() {
        match c {
            c if c as u32 == 0x22 => { r.push('\\u{5c}'); r.push('"'); }
            c if c as u32 == 0x5c => { r.push('\\u{5c}'); r.push('\\u{5c}'); }
            c if c as u32 == 0x0a => { r.push('\\u{5c}'); r.push('n'); }
            c if c as u32 == 0x09 => { r.push('\\u{5c}'); r.push('t'); }
            c if c as u32 == 0x0d => { r.push('\\u{5c}'); r.push('r'); }
            c if (c as u32) < 0x20 => { write!(r, "\\\\u{:04x}", c as u32).unwrap(); }
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

fn _dn(v: f64) -> String {
    if v == 0.0 && v.is_sign_negative() { return "-0".to_string(); }
    format!("{}", v)
}

fn _di(v: i64) -> String { format!("\\\"{}\\\"", v) }
fn _du(v: u64) -> String { format!("\\\"{}\\\"", v) }
fn _db(v: &[u8]) -> String {
    const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut r = String::new();
    for ch in v.chunks(3) {
        let b0 = ch[0] as u32;
        let b1 = if ch.len() > 1 { ch[1] as u32 } else { 0 };
        let b2 = if ch.len() > 2 { ch[2] as u32 } else { 0 };
        let n = (b0 << 16) | (b1 << 8) | b2;
        r.push(T[((n >> 18) & 0x3F) as usize] as char);
        r.push(T[((n >> 12) & 0x3F) as usize] as char);
        if ch.len() > 1 { r.push(T[((n >> 6) & 0x3F) as usize] as char); } else { r.push('='); }
        if ch.len() > 2 { r.push(T[(n & 0x3F) as usize] as char); } else { r.push('='); }
    }
    r
}

${dumpFunctions}
`;
}

function rustDumpFunction(name: string, m: ModelDef): string {
  const fn = toRustDumpFn(name);
  const lines: string[] = [];
  
  for (const field of m.fields) {
    lines.push(rustFieldLine(field));
  }
  
  const body = lines.length === 0 
    ? '    "{}".to_string()'
    : `    let mut parts: Vec<String> = Vec::new();
${lines.join('\n')}
    format!("{{{}}}", parts.join(","))`;
  
  return `fn ${fn}(o: &${name}) -> String {
${body}
}`;
}

function rustFieldLine(field: FieldDef): string {
  const expr = rustValueExpr(field, `o.${field.name}`);
  
  if (field.optional) {
    const derefExpr = rustValueExpr(field, 'v');
    return `    if let Some(v) = &o.${field.name} { parts.push(format!("\\"${field.name}\\":{}", ${derefExpr})); }`;
  }
  
  return `    parts.push(format!("\\"${field.name}\\":{}", ${expr}));`;
}

function rustValueExpr(field: FieldDef, expr: string): string {
  if (field.isArray) {
    if (field.isModel) {
      return `"[\".to_string() + &${expr}.iter().map(|e| ${toRustDumpFn(field.type)}(e)).collect::<Vec<String>>().join(",") + "]"`;
    }
    if (field.type === 'string') {
      return `"[\".to_string() + &${expr}.iter().map(|e| _ds(e)).collect::<Vec<String>>().join(",") + "]"`;
    }
    if (field.type === 'boolean') {
      return `"[\".to_string() + &${expr}.iter().map(|e| if *e { "true" } else { "false" }).collect::<Vec<&str>>().join(",") + "]"`;
    }
    if (field.type === 'bytes') {
      return `"[\".to_string() + &${expr}.iter().map(|e| "\\"".to_string() + &_db(e) + "\\"").collect::<Vec<String>>().join(",") + "]"`;
    }
    if (field.type === 'int64') {
      return `"[\".to_string() + &${expr}.iter().map(|e| _di(*e)).collect::<Vec<String>>().join(",") + "]"`;
    }
    if (field.type === 'uint64') {
      return `"[\".to_string() + &${expr}.iter().map(|e| _du(*e)).collect::<Vec<String>>().join(",") + "]"`;
    }
    if (field.type === 'float32' || field.type === 'float64') {
      return `"[\".to_string() + &${expr}.iter().map(|e| _dn(*e as f64)).collect::<Vec<String>>().join(",") + "]"`;
    }
    return `"[\".to_string() + &${expr}.iter().map(|e| e.to_string()).collect::<Vec<String>>().join(",") + "]"`;
  }
  
  if (field.isModel) {
    const ref = expr === 'v' ? '' : '&';
    return `${toRustDumpFn(field.type)}(${ref}${expr})`;
  }
  
  if (field.type === 'string') {
    const ref = expr === 'v' ? '' : '&';
    return `_ds(${ref}${expr})`;
  }
  if (field.type === 'boolean') {
    const deref = expr === 'v' ? '*' : '';
    return `if ${deref}${expr} { "true" } else { "false" }`;
  }
if (field.type === 'bytes') {
    const ref = expr === 'v' ? '' : '&';
    return `"\\\"".to_string() + &_db(${ref}${expr}) + "\\\""`;
  }
  if (field.type === 'int64') {
    const deref = expr === 'v' ? '*' : '';
    return `_di(${deref}${expr})`;
  }
  if (field.type === 'uint64') {
    const deref = expr === 'v' ? '*' : '';
    return `_du(${deref}${expr})`;
  }
  if (field.type === 'float32' || field.type === 'float64') {
    const deref = expr === 'v' ? '*' : '';
    return `_dn(${deref}${expr} as f64)`;
  }
  
  return `${expr}.to_string()`;
}