import { FieldDef, ModelDef, models } from '../gen.ts';
import { getDumpFnName } from '../field-naming.ts';

export function generateSwiftDump(): string {
  const dumpFunctions = Object.entries(models).map(([name, m]) => 
    swiftDumpFunction(name, m)
  ).join('\n');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
import Foundation

func _ds(_ v: String) -> String {
    var r = ""
    r.append("\\\"")
    for c in v {
        switch c {
        case "\\\"": r.append("\\\\\\\"")
        case "\\\\": r.append("\\\\\\\\")
        case "\\n": r.append("\\\\n")
        case "\\t": r.append("\\\\t")
        case "\\r": r.append("\\\\r")
default: 
            if let a = c.asciiValue, a < 32 {
                r.write(String(format: "\\\\u%04x", a))
            } else {
                r.append(c)
            }
        }
    }
    r.append("\\\"")
    return r
}

func _dn(_ v: Double) -> String {
    if v == 0.0 && v < 0 { return "-0" }
    let s = String(v)
    return s.hasSuffix(".0") ? String(s.dropLast(2)) : s
}
func _dnf(_ v: Float) -> String { return _dn(Double(v)) }

func _di(_ v: Int64) -> String { return "\\\""+String(v)+"\\\"" }
func _du(_ v: UInt64) -> String { return "\\\""+String(v)+"\\\"" }
func _db(_ v: Data) -> String { return v.base64EncodedString() }

${dumpFunctions}
`;
}

function swiftDumpFunction(name: string, m: ModelDef): string {
  const fn = `dump${name}`;
  const lines: string[] = [];
  
  for (const field of m.fields) {
    lines.push(swiftFieldLine(field));
  }
  
  const body = lines.length === 0 
    ? '    return "{}"'
    : `    var parts: [String] = []
${lines.join('\n')}
    return "{" + parts.joined(separator: ",") + "}"`;
  
  return `func ${fn}(_ o: ${name}) -> String {
${body}
}`;
}

function swiftFieldLine(field: FieldDef): string {
  let valExpr = swiftValueExpr(field, `o.${field.name}`);
  let addQuotes = false;
  
  if (!field.isArray && field.type === 'bytes') {
    addQuotes = true;
    valExpr = `_db(o.${field.name})`;
  }
  
  if (field.optional) {
    const regex = new RegExp(`o\\.${field.name}`, 'g');
    const optValExpr = addQuotes ? `"\\\"" + ${valExpr.replace(regex, 'v')} + "\\\""` : valExpr.replace(regex, 'v');
    return `    if let v = o.${field.name} { parts.append("\\\"${field.name}\\\": " + ${optValExpr}) }`;
  }
  
  const quotedValExpr = addQuotes ? `"\\\"" + ${valExpr} + "\\\""` : valExpr;
  return `    parts.append("\\\"${field.name}\\\": " + ${quotedValExpr})`;
}

function swiftValueExpr(field: FieldDef, expr: string): string {
  if (field.isArray) {
    if (field.isModel) {
      return `"[" + ${expr}.map { dump${field.type}($0) }.joined(separator: ",") + "]"`;
    }
    if (field.type === 'string') {
      return `"[" + ${expr}.map { _ds($0) }.joined(separator: ",") + "]"`;
    }
    if (field.type === 'boolean') {
      return `"[" + ${expr}.map { $0 ? "true" : "false" }.joined(separator: ",") + "]"`;
    }
    if (field.type === 'bytes') {
      return `"[" + ${expr}.map { "\\\"" + _db($0) + "\\\"" }.joined(separator: ",") + "]"`;
    }
    if (field.type === 'int64') {
      return `"[" + ${expr}.map { _di($0) }.joined(separator: ",") + "]"`;
    }
    if (field.type === 'uint64') {
      return `"[" + ${expr}.map { _du($0) }.joined(separator: ",") + "]"`;
    }
    if (field.type === 'float32' || field.type === 'float64') {
      return field.type === 'float32'
        ? `"[" + ${expr}.map { _dnf($0) }.joined(separator: ",") + "]"`
        : `"[" + ${expr}.map { _dn($0) }.joined(separator: ",") + "]"`;
    }
    return `"[" + ${expr}.map { String($0) }.joined(separator: ",") + "]"`;
  }
  
  if (field.isModel) {
    return `dump${field.type}(${expr})`;
  }
  
  if (field.type === 'string') {
    return `_ds(${expr})`;
  }
  if (field.type === 'boolean') {
    return `(${expr} ? "true" : "false")`;
  }
  if (field.type === 'int64') {
    return `_di(${expr})`;
  }
  if (field.type === 'uint64') {
    return `_du(${expr})`;
  }
  if (field.type === 'float32' || field.type === 'float64') {
    return field.type === 'float32' ? `_dnf(${expr})` : `_dn(${expr})`;
  }
  
  return `String(${expr})`;
}