import { models } from '../gen.ts';

export function generateTsDump(): string {
  const schemaEntries = Object.entries(models).map(([name, m]) => {
    const fields = m.fields.map(f => {
      const parts = [`n:"${f.name}"`, `t:"${f.type}"`];
      if (f.optional) parts.push('o:true');
      if (f.isArray) parts.push('a:true');
      if (f.isModel) parts.push('m:true');
      return `{${parts.join(',')}}`;
    }).join(',');
    return `"${name}":[${fields}]`;
  }).join(',');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
const _sch: Record<string,{n:string,t:string,o?:boolean,a?:boolean,m?:boolean}[]> = {${schemaEntries}};

function _dn(v: number): string { return Object.is(v, -0) ? "-0" : String(v); }

function _dv(v: any, f: {t:string,o?:boolean,a?:boolean,m?:boolean}): string {
  if (v === undefined || v === null) return "null";
  if (f.a) return "[" + (v as any[]).map((e:any) => _dv(e, {...f, a: false as any})).join(",") + "]";
  if (f.m) return dumpModel(f.t, v);
  switch (f.t) {
    case "string": return JSON.stringify(v);
    case "boolean": return v ? "true" : "false";
    case "float32": case "float64": return _dn(v);
    case "int64": return '"' + v.toString() + '"';
    case "uint64": return '"' + v.toString() + '"';
    case "bytes": return '"' + Buffer.from(v).toString("base64") + '"';
    default: return String(v);
  }
}

export function dumpModel(name: string, obj: any): string {
  const fields = _sch[name];
  if (!fields) throw new Error("unknown model: " + name);
  const p: string[] = [];
  for (const f of fields) {
    const v = obj[f.n];
    if (f.o && v === undefined) continue;
    p.push('"' + f.n + '":' + _dv(v, f));
  }
  return "{" + p.join(",") + "}";
}
`;
}