// Generated by gen_types.cjs. DO NOT EDIT.
package alltypes
import java.util.Base64

fun _ds(v: String): String {
    val b = StringBuilder()
    b.append('"')
    for (c in v) {
        when (c) {
            '"' -> b.append("\\\"")
            '\\' -> b.append("\\\\")
            '\n' -> b.append("\\n")
            '\t' -> b.append("\\t")
            '\r' -> b.append("\\r")
            else -> if (c.code < 32) b.append("\\u%04x".format(c.code)) else b.append(c)
        }
    }
    b.append('"')
    return b.toString()
}

fun _dn(v: Double): String {
    if (v == 0.0 && v < 0) return "-0"
    val s = v.toString()
    return if (s.endsWith(".0")) s.dropLast(2) else s
}
fun _dnf(v: Float): String = _dn(v.toDouble())

fun _di(v: Long): String = "\"" + v.toString() + "\""
fun _du(v: ULong): String = "\"" + v.toString() + "\""
fun _db(v: ByteArray): String = Base64.getEncoder().encodeToString(v)

fun dumpInner(o: Inner): String {
    val parts = mutableListOf<String>()
    parts.add("\"x\":" + o.x.toString())
    parts.add("\"y\":" + o.y.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpCoord(o: Coord): String {
    val parts = mutableListOf<String>()
    parts.add("\"lat\":" + _dn(o.lat))
    parts.add("\"lng\":" + _dn(o.lng))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpIdVal(o: IdVal): String {
    val parts = mutableListOf<String>()
    parts.add("\"id\":" + _ds(o.id))
    parts.add("\"value\":" + o.value.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpLabel(o: Label): String {
    val parts = mutableListOf<String>()
    parts.add("\"key\":" + _ds(o.key))
    parts.add("\"text\":" + _ds(o.text))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMoney(o: Money): String {
    val parts = mutableListOf<String>()
    parts.add("\"amount\":" + _di(o.amount))
    parts.add("\"currency\":" + _ds(o.currency))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpRange32(o: Range32): String {
    val parts = mutableListOf<String>()
    parts.add("\"min\":" + o.min.toString())
    parts.add("\"max\":" + o.max.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpAddr(o: Addr): String {
    val parts = mutableListOf<String>()
    parts.add("\"street\":" + _ds(o.street))
    parts.add("\"city\":" + _ds(o.city))
    parts.add("\"zip\":" + _ds(o.zip))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPoint3(o: Point3): String {
    val parts = mutableListOf<String>()
    parts.add("\"x\":" + _dn(o.x))
    parts.add("\"y\":" + _dn(o.y))
    parts.add("\"z\":" + _dn(o.z))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptInner(o: OptInner): String {
    val parts = mutableListOf<String>()
    o.name?.let { parts.add("\"name\":" + _ds(it)) }
    o.score?.let { parts.add("\"score\":" + _dn(it)) }
    o.tag?.let { parts.add("\"tag\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleString(o: SingleString): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + _ds(o.v))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleBoolean(o: SingleBoolean): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + (if (o.v) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleInt8(o: SingleInt8): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + o.v.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleInt16(o: SingleInt16): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + o.v.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleInt32(o: SingleInt32): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + o.v.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleInt64(o: SingleInt64): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + _di(o.v))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleUint8(o: SingleUint8): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + o.v.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleUint16(o: SingleUint16): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + o.v.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleUint32(o: SingleUint32): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + o.v.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleUint64(o: SingleUint64): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + _du(o.v))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleFloat32(o: SingleFloat32): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + _dnf(o.v))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleFloat64(o: SingleFloat64): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + _dn(o.v))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpSingleBytes(o: SingleBytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":\"" + _db(o.v) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleString(o: OptSingleString): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleBoolean(o: OptSingleBoolean): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + (if (it) "true" else "false")) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleInt8(o: OptSingleInt8): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleInt16(o: OptSingleInt16): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleInt32(o: OptSingleInt32): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleInt64(o: OptSingleInt64): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + _di(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleUint8(o: OptSingleUint8): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleUint16(o: OptSingleUint16): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleUint32(o: OptSingleUint32): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleUint64(o: OptSingleUint64): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + _du(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleFloat32(o: OptSingleFloat32): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + _dnf(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleFloat64(o: OptSingleFloat64): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":" + _dn(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptSingleBytes(o: OptSingleBytes): String {
    val parts = mutableListOf<String>()
    o.v?.let { parts.add("\"v\":\"" + _db(it) + "\"") }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairString(o: PairString): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + _ds(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairBoolean(o: PairBoolean): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + (if (o.a) "true" else "false"))
    parts.add("\"b\":" + (if (o.b) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairInt8(o: PairInt8): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairInt16(o: PairInt16): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairInt32(o: PairInt32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairInt64(o: PairInt64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _di(o.a))
    parts.add("\"b\":" + _di(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairUint8(o: PairUint8): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairUint16(o: PairUint16): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairUint32(o: PairUint32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairUint64(o: PairUint64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _du(o.a))
    parts.add("\"b\":" + _du(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairFloat32(o: PairFloat32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dnf(o.a))
    parts.add("\"b\":" + _dnf(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairFloat64(o: PairFloat64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dn(o.a))
    parts.add("\"b\":" + _dn(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpPairBytes(o: PairBytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":\"" + _db(o.a) + "\"")
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualStringInt32(o: DualStringInt32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualStringBoolean(o: DualStringBoolean): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + (if (o.b) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualStringFloat64(o: DualStringFloat64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + _dn(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualStringBytes(o: DualStringBytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt32Boolean(o: DualInt32Boolean): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + (if (o.b) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt32Float64(o: DualInt32Float64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _dn(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt32Int64(o: DualInt32Int64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _di(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt32Uint32(o: DualInt32Uint32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt64Uint64(o: DualInt64Uint64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _di(o.a))
    parts.add("\"b\":" + _du(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualFloat32Float64(o: DualFloat32Float64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dnf(o.a))
    parts.add("\"b\":" + _dn(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualFloat64Boolean(o: DualFloat64Boolean): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dn(o.a))
    parts.add("\"b\":" + (if (o.b) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualFloat64Bytes(o: DualFloat64Bytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dn(o.a))
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualUint32Uint64(o: DualUint32Uint64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _du(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualBooleanBytes(o: DualBooleanBytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + (if (o.a) "true" else "false"))
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt8Uint8(o: DualInt8Uint8): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt16Uint16(o: DualInt16Uint16): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualStringInt64(o: DualStringInt64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + _di(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualStringUint64(o: DualStringUint64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + _du(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt32Bytes(o: DualInt32Bytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualFloat64Int32(o: DualFloat64Int32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dn(o.a))
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualBooleanInt32(o: DualBooleanInt32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + (if (o.a) "true" else "false"))
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualBytesInt64(o: DualBytesInt64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":\"" + _db(o.a) + "\"")
    parts.add("\"b\":" + _di(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt8Float32(o: DualInt8Float32): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _dnf(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualUint8Int16(o: DualUint8Int16): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualInt64Float64(o: DualInt64Float64): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _di(o.a))
    parts.add("\"b\":" + _dn(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDualUint64String(o: DualUint64String): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _du(o.a))
    parts.add("\"b\":" + _ds(o.b))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple01(o: Triple01): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + o.b.toString())
    parts.add("\"c\":" + (if (o.c) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple02(o: Triple02): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dn(o.a))
    parts.add("\"b\":" + _dn(o.b))
    parts.add("\"c\":" + _dn(o.c))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple03(o: Triple03): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    parts.add("\"c\":" + o.c.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple04(o: Triple04): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + _ds(o.b))
    parts.add("\"c\":" + o.c.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple05(o: Triple05): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _di(o.a))
    parts.add("\"b\":" + _ds(o.b))
    parts.add("\"c\":" + (if (o.c) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple06(o: Triple06): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _du(o.b))
    parts.add("\"c\":" + _ds(o.c))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple07(o: Triple07): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":\"" + _db(o.a) + "\"")
    parts.add("\"b\":" + _ds(o.b))
    parts.add("\"c\":" + o.c.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple08(o: Triple08): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dnf(o.a))
    parts.add("\"b\":" + o.b.toString())
    parts.add("\"c\":" + (if (o.c) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple09(o: Triple09): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":" + _di(o.b))
    parts.add("\"c\":" + _dn(o.c))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple10(o: Triple10): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + (if (o.a) "true" else "false"))
    parts.add("\"b\":" + (if (o.b) "true" else "false"))
    parts.add("\"c\":" + (if (o.c) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple11(o: Triple11): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    parts.add("\"c\":" + o.c.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple12(o: Triple12): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + o.b.toString())
    parts.add("\"c\":" + o.c.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple13(o: Triple13): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    parts.add("\"c\":" + _dn(o.c))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple14(o: Triple14): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _di(o.a))
    parts.add("\"b\":" + _du(o.b))
    parts.add("\"c\":" + (if (o.c) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTriple15(o: Triple15): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _dn(o.a))
    parts.add("\"b\":" + _ds(o.b))
    parts.add("\"c\":\"" + _db(o.c) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive01(o: Five01): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _ds(o.f1))
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + (if (o.f3) "true" else "false"))
    parts.add("\"f4\":" + _dn(o.f4))
    parts.add("\"f5\":\"" + _db(o.f5) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive02(o: Five02): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + o.f5.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive03(o: Five03): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _ds(o.f1))
    parts.add("\"f2\":" + _ds(o.f2))
    parts.add("\"f3\":" + _ds(o.f3))
    parts.add("\"f4\":" + _ds(o.f4))
    parts.add("\"f5\":" + _ds(o.f5))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive04(o: Five04): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _dn(o.f1))
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + _ds(o.f3))
    parts.add("\"f4\":" + (if (o.f4) "true" else "false"))
    parts.add("\"f5\":\"" + _db(o.f5) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive05(o: Five05): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _di(o.f1))
    parts.add("\"f2\":" + _du(o.f2))
    parts.add("\"f3\":" + _ds(o.f3))
    parts.add("\"f4\":" + _dnf(o.f4))
    parts.add("\"f5\":" + o.f5.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive06(o: Five06): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + (if (o.f1) "true" else "false"))
    parts.add("\"f2\":" + _ds(o.f2))
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + _dn(o.f4))
    parts.add("\"f5\":" + o.f5.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive07(o: Five07): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":\"" + _db(o.f1) + "\"")
    parts.add("\"f2\":\"" + _db(o.f2) + "\"")
    parts.add("\"f3\":" + _ds(o.f3))
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + _dn(o.f5))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive08(o: Five08): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + o.f5.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive09(o: Five09): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _dnf(o.f1))
    parts.add("\"f2\":" + _dn(o.f2))
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + _di(o.f4))
    parts.add("\"f5\":" + _ds(o.f5))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpFive10(o: Five10): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _ds(o.f1))
    parts.add("\"f2\":" + (if (o.f2) "true" else "false"))
    parts.add("\"f3\":" + _di(o.f3))
    parts.add("\"f4\":" + _du(o.f4))
    parts.add("\"f5\":" + _dn(o.f5))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTen01(o: Ten01): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _ds(o.f1))
    parts.add("\"f2\":" + (if (o.f2) "true" else "false"))
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + o.f5.toString())
    parts.add("\"f6\":" + _di(o.f6))
    parts.add("\"f7\":" + o.f7.toString())
    parts.add("\"f8\":" + o.f8.toString())
    parts.add("\"f9\":" + o.f9.toString())
    parts.add("\"f10\":" + _du(o.f10))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTen02(o: Ten02): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + _di(o.f3))
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + o.f5.toString())
    parts.add("\"f6\":" + o.f6.toString())
    parts.add("\"f7\":" + _du(o.f7))
    parts.add("\"f8\":" + _dnf(o.f8))
    parts.add("\"f9\":" + _dn(o.f9))
    parts.add("\"f10\":\"" + _db(o.f10) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTen03(o: Ten03): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + _du(o.f4))
    parts.add("\"f5\":" + _dnf(o.f5))
    parts.add("\"f6\":" + _dn(o.f6))
    parts.add("\"f7\":\"" + _db(o.f7) + "\"")
    parts.add("\"f8\":" + _ds(o.f8))
    parts.add("\"f9\":" + (if (o.f9) "true" else "false"))
    parts.add("\"f10\":" + o.f10.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTen04(o: Ten04): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _du(o.f1))
    parts.add("\"f2\":" + _dnf(o.f2))
    parts.add("\"f3\":" + _dn(o.f3))
    parts.add("\"f4\":\"" + _db(o.f4) + "\"")
    parts.add("\"f5\":" + _ds(o.f5))
    parts.add("\"f6\":" + (if (o.f6) "true" else "false"))
    parts.add("\"f7\":" + o.f7.toString())
    parts.add("\"f8\":" + o.f8.toString())
    parts.add("\"f9\":" + o.f9.toString())
    parts.add("\"f10\":" + _di(o.f10))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTen05(o: Ten05): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":\"" + _db(o.f1) + "\"")
    parts.add("\"f2\":" + _ds(o.f2))
    parts.add("\"f3\":" + (if (o.f3) "true" else "false"))
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + o.f5.toString())
    parts.add("\"f6\":" + o.f6.toString())
    parts.add("\"f7\":" + _di(o.f7))
    parts.add("\"f8\":" + o.f8.toString())
    parts.add("\"f9\":" + o.f9.toString())
    parts.add("\"f10\":" + o.f10.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrString(o: ArrString): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { _ds(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrInt32(o: ArrInt32): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { it.toString() })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrBoolean(o: ArrBoolean): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { if (it) "true" else "false" })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrFloat64(o: ArrFloat64): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { _dn(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrBytes(o: ArrBytes): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { "\"" + _db(it) + "\"" })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrInt64(o: ArrInt64): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { _di(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpArrUint64(o: ArrUint64): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { _du(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMultiArr1(o: MultiArr1): String {
    val parts = mutableListOf<String>()
    parts.add("\"names\":" + o.names.joinToString(",", "[", "]") { _ds(it) })
    parts.add("\"scores\":" + o.scores.joinToString(",", "[", "]") { it.toString() })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMultiArr2(o: MultiArr2): String {
    val parts = mutableListOf<String>()
    parts.add("\"flags\":" + o.flags.joinToString(",", "[", "]") { if (it) "true" else "false" })
    parts.add("\"values\":" + o.values.joinToString(",", "[", "]") { _dn(it) })
    parts.add("\"payload\":" + o.payload.joinToString(",", "[", "]") { "\"" + _db(it) + "\"" })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMultiArr3(o: MultiArr3): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.joinToString(",", "[", "]") { _ds(it) })
    parts.add("\"b\":" + o.b.joinToString(",", "[", "]") { it.toString() })
    parts.add("\"c\":" + o.c.joinToString(",", "[", "]") { _dn(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMultiArr4(o: MultiArr4): String {
    val parts = mutableListOf<String>()
    parts.add("\"ids\":" + o.ids.joinToString(",", "[", "]") { _di(it) })
    parts.add("\"tags\":" + o.tags.joinToString(",", "[", "]") { _ds(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMultiArr5(o: MultiArr5): String {
    val parts = mutableListOf<String>()
    parts.add("\"xs\":" + o.xs.joinToString(",", "[", "]") { _du(it) })
    parts.add("\"ys\":" + o.ys.joinToString(",", "[", "]") { _dnf(it) })
    parts.add("\"zs\":" + o.zs.joinToString(",", "[", "]") { if (it) "true" else "false" })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo1(o: OptCombo1): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + _ds(o.req))
    o.opt_a?.let { parts.add("\"opt_a\":" + it.toString()) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo2(o: OptCombo2): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + _ds(o.req))
    o.opt_a?.let { parts.add("\"opt_a\":" + it.toString()) }
    o.opt_b?.let { parts.add("\"opt_b\":" + (if (it) "true" else "false")) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo3(o: OptCombo3): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + _ds(o.req))
    o.opt_a?.let { parts.add("\"opt_a\":" + it.toString()) }
    o.opt_b?.let { parts.add("\"opt_b\":" + (if (it) "true" else "false")) }
    o.opt_c?.let { parts.add("\"opt_c\":" + _dn(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo4(o: OptCombo4): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + o.req.toString())
    o.opt_a?.let { parts.add("\"opt_a\":" + _ds(it)) }
    o.opt_b?.let { parts.add("\"opt_b\":\"" + _db(it) + "\"") }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo5(o: OptCombo5): String {
    val parts = mutableListOf<String>()
    parts.add("\"req1\":" + _ds(o.req1))
    parts.add("\"req2\":" + o.req2.toString())
    o.opt_a?.let { parts.add("\"opt_a\":" + (if (it) "true" else "false")) }
    o.opt_b?.let { parts.add("\"opt_b\":" + _dn(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo6(o: OptCombo6): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + _ds(o.req))
    o.opt_s?.let { parts.add("\"opt_s\":" + _ds(it)) }
    o.opt_i?.let { parts.add("\"opt_i\":" + it.toString()) }
    o.opt_f?.let { parts.add("\"opt_f\":" + _dn(it)) }
    o.opt_b?.let { parts.add("\"opt_b\":\"" + _db(it) + "\"") }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo7(o: OptCombo7): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + _di(o.req))
    o.opt_u64?.let { parts.add("\"opt_u64\":" + _du(it)) }
    o.opt_str?.let { parts.add("\"opt_str\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo8(o: OptCombo8): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + _ds(o.a))
    o.b?.let { parts.add("\"b\":" + it.toString()) }
    o.c?.let { parts.add("\"c\":" + _dn(it)) }
    o.d?.let { parts.add("\"d\":" + (if (it) "true" else "false")) }
    o.e?.let { parts.add("\"e\":\"" + _db(it) + "\"") }
    o.f?.let { parts.add("\"f\":" + _di(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo9(o: OptCombo9): String {
    val parts = mutableListOf<String>()
    parts.add("\"id\":" + _ds(o.id))
    o.name?.let { parts.add("\"name\":" + _ds(it)) }
    o.age?.let { parts.add("\"age\":" + it.toString()) }
    o.score?.let { parts.add("\"score\":" + _dn(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptCombo10(o: OptCombo10): String {
    val parts = mutableListOf<String>()
    parts.add("\"code\":" + o.code.toString())
    o.msg?.let { parts.add("\"msg\":" + _ds(it)) }
    o.detail?.let { parts.add("\"detail\":" + _ds(it)) }
    o.retry?.let { parts.add("\"retry\":" + (if (it) "true" else "false")) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestInner(o: NestInner): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpInner(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestCoord(o: NestCoord): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpCoord(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestIdVal(o: NestIdVal): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpIdVal(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestLabel(o: NestLabel): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpLabel(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestMoney(o: NestMoney): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpMoney(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestRange32(o: NestRange32): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpRange32(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestAddr(o: NestAddr): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpAddr(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestPoint3(o: NestPoint3): String {
    val parts = mutableListOf<String>()
    parts.add("\"nested\":" + dumpPoint3(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestInner(o: OptNestInner): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpInner(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestCoord(o: OptNestCoord): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpCoord(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestIdVal(o: OptNestIdVal): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpIdVal(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestLabel(o: OptNestLabel): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpLabel(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestMoney(o: OptNestMoney): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpMoney(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestRange32(o: OptNestRange32): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpRange32(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestAddr(o: OptNestAddr): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpAddr(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptNestPoint3(o: OptNestPoint3): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    o.nested?.let { parts.add("\"nested\":" + dumpPoint3(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpModelArr1(o: ModelArr1): String {
    val parts = mutableListOf<String>()
    parts.add("\"points\":" + o.points.joinToString(",", "[", "]") { dumpInner(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpModelArr2(o: ModelArr2): String {
    val parts = mutableListOf<String>()
    parts.add("\"coords\":" + o.coords.joinToString(",", "[", "]") { dumpCoord(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpModelArr3(o: ModelArr3): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { dumpIdVal(it) })
    parts.add("\"tag\":" + _ds(o.tag))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpModelArr4(o: ModelArr4): String {
    val parts = mutableListOf<String>()
    parts.add("\"labels\":" + o.labels.joinToString(",", "[", "]") { dumpLabel(it) })
    parts.add("\"count\":" + o.count.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpModelArr5(o: ModelArr5): String {
    val parts = mutableListOf<String>()
    parts.add("\"arr\":" + o.arr.joinToString(",", "[", "]") { dumpMoney(it) })
    parts.add("\"bs\":" + o.bs.joinToString(",", "[", "]") { dumpAddr(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix01(o: Mix01): String {
    val parts = mutableListOf<String>()
    parts.add("\"name\":" + _ds(o.name))
    parts.add("\"value\":" + o.value.toString())
    parts.add("\"point\":" + dumpInner(o.point))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix02(o: Mix02): String {
    val parts = mutableListOf<String>()
    parts.add("\"id\":" + _ds(o.id))
    parts.add("\"loc\":" + dumpCoord(o.loc))
    parts.add("\"tags\":" + o.tags.joinToString(",", "[", "]") { _ds(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix03(o: Mix03): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    parts.add("\"value_range\":" + dumpRange32(o.value_range))
    parts.add("\"active\":" + (if (o.active) "true" else "false"))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix04(o: Mix04): String {
    val parts = mutableListOf<String>()
    parts.add("\"title\":" + _ds(o.title))
    parts.add("\"price\":" + dumpMoney(o.price))
    parts.add("\"inStock\":" + (if (o.inStock) "true" else "false"))
    parts.add("\"rating\":" + _dn(o.rating))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix05(o: Mix05): String {
    val parts = mutableListOf<String>()
    parts.add("\"addr\":" + dumpAddr(o.addr))
    parts.add("\"coords\":" + o.coords.joinToString(",", "[", "]") { dumpCoord(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix06(o: Mix06): String {
    val parts = mutableListOf<String>()
    parts.add("\"name\":" + _ds(o.name))
    parts.add("\"age\":" + o.age.toString())
    o.address?.let { parts.add("\"address\":" + dumpAddr(it)) }
    o.email?.let { parts.add("\"email\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix07(o: Mix07): String {
    val parts = mutableListOf<String>()
    parts.add("\"origin\":" + dumpPoint3(o.origin))
    parts.add("\"dest\":" + dumpPoint3(o.dest))
    parts.add("\"distance\":" + _dn(o.distance))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix08(o: Mix08): String {
    val parts = mutableListOf<String>()
    parts.add("\"keys\":" + o.keys.joinToString(",", "[", "]") { _ds(it) })
    parts.add("\"values\":" + o.values.joinToString(",", "[", "]") { it.toString() })
    o.meta?.let { parts.add("\"meta\":" + dumpLabel(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix09(o: Mix09): String {
    val parts = mutableListOf<String>()
    parts.add("\"id\":" + _di(o.id))
    parts.add("\"payload\":\"" + _db(o.payload) + "\"")
    parts.add("\"checksum\":" + o.checksum.toString())
    o.prev?.let { parts.add("\"prev\":" + dumpIdVal(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix10(o: Mix10): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { _ds(it) })
    parts.add("\"total\":" + o.total.toString())
    parts.add("\"avg\":" + _dn(o.avg))
    parts.add("\"value_range\":" + dumpRange32(o.value_range))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix11(o: Mix11): String {
    val parts = mutableListOf<String>()
    parts.add("\"name\":" + _ds(o.name))
    parts.add("\"values\":" + o.values.joinToString(",", "[", "]") { _dn(it) })
    o.nested?.let { parts.add("\"nested\":" + dumpInner(it)) }
    o.flag?.let { parts.add("\"flag\":" + (if (it) "true" else "false")) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix12(o: Mix12): String {
    val parts = mutableListOf<String>()
    parts.add("\"header\":" + _ds(o.header))
    parts.add("\"entries\":" + o.entries.joinToString(",", "[", "]") { dumpIdVal(it) })
    o.footer?.let { parts.add("\"footer\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix13(o: Mix13): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _dn(o.b))
    parts.add("\"c\":" + _ds(o.c))
    parts.add("\"d\":" + (if (o.d) "true" else "false"))
    parts.add("\"e\":\"" + _db(o.e) + "\"")
    parts.add("\"nested\":" + dumpInner(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix14(o: Mix14): String {
    val parts = mutableListOf<String>()
    parts.add("\"amounts\":" + o.amounts.joinToString(",", "[", "]") { dumpMoney(it) })
    parts.add("\"total\":" + _di(o.total))
    parts.add("\"currency\":" + _ds(o.currency))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpMix15(o: Mix15): String {
    val parts = mutableListOf<String>()
    parts.add("\"src_addr\":" + dumpAddr(o.src_addr))
    parts.add("\"dst_addr\":" + dumpAddr(o.dst_addr))
    parts.add("\"distance\":" + _dn(o.distance))
    parts.add("\"duration\":" + _dn(o.duration))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpAllOpt1(o: AllOpt1): String {
    val parts = mutableListOf<String>()
    o.a?.let { parts.add("\"a\":" + _ds(it)) }
    o.b?.let { parts.add("\"b\":" + it.toString()) }
    o.c?.let { parts.add("\"c\":" + (if (it) "true" else "false")) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpAllOpt2(o: AllOpt2): String {
    val parts = mutableListOf<String>()
    o.x?.let { parts.add("\"x\":" + _dn(it)) }
    o.y?.let { parts.add("\"y\":\"" + _db(it) + "\"") }
    o.z?.let { parts.add("\"z\":" + _di(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpAllOpt3(o: AllOpt3): String {
    val parts = mutableListOf<String>()
    o.name?.let { parts.add("\"name\":" + _ds(it)) }
    o.age?.let { parts.add("\"age\":" + it.toString()) }
    o.score?.let { parts.add("\"score\":" + _dn(it)) }
    o.active?.let { parts.add("\"active\":" + (if (it) "true" else "false")) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpAllOpt4(o: AllOpt4): String {
    val parts = mutableListOf<String>()
    o.a?.let { parts.add("\"a\":" + it.toString()) }
    o.b?.let { parts.add("\"b\":" + _du(it)) }
    o.c?.let { parts.add("\"c\":" + it.toString()) }
    o.d?.let { parts.add("\"d\":" + _ds(it)) }
    o.e?.let { parts.add("\"e\":\"" + _db(it) + "\"") }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpAllOpt5(o: AllOpt5): String {
    val parts = mutableListOf<String>()
    o.p?.let { parts.add("\"p\":" + dumpInner(it)) }
    o.q?.let { parts.add("\"q\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpRecList(o: RecList): String {
    val parts = mutableListOf<String>()
    parts.add("\"value\":" + o.value.toString())
    o.next?.let { parts.add("\"next\":" + dumpRecList(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpRecTree(o: RecTree): String {
    val parts = mutableListOf<String>()
    parts.add("\"value\":" + _ds(o.value))
    o.left_node?.let { parts.add("\"left_node\":" + dumpRecTree(it)) }
    o.right_node?.let { parts.add("\"right_node\":" + dumpRecTree(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpRecChain(o: RecChain): String {
    val parts = mutableListOf<String>()
    parts.add("\"id\":" + o.id.toString())
    parts.add("\"label\":" + _ds(o.label))
    o.next?.let { parts.add("\"next\":" + dumpRecChain(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpRecWrap(o: RecWrap): String {
    val parts = mutableListOf<String>()
    parts.add("\"payload\":\"" + _db(o.payload) + "\"")
    o.nested?.let { parts.add("\"nested\":" + dumpRecWrap(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpRecWide(o: RecWide): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + o.a.toString())
    parts.add("\"b\":" + _ds(o.b))
    parts.add("\"c\":" + _dn(o.c))
    o.child?.let { parts.add("\"child\":" + dumpRecWide(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpWide20(o: Wide20): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + _ds(o.f1))
    parts.add("\"f2\":" + (if (o.f2) "true" else "false"))
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + o.f5.toString())
    parts.add("\"f6\":" + _di(o.f6))
    parts.add("\"f7\":" + o.f7.toString())
    parts.add("\"f8\":" + o.f8.toString())
    parts.add("\"f9\":" + o.f9.toString())
    parts.add("\"f10\":" + _du(o.f10))
    parts.add("\"f11\":" + _dnf(o.f11))
    parts.add("\"f12\":" + _dn(o.f12))
    parts.add("\"f13\":\"" + _db(o.f13) + "\"")
    parts.add("\"f14\":" + _ds(o.f14))
    parts.add("\"f15\":" + (if (o.f15) "true" else "false"))
    parts.add("\"f16\":" + o.f16.toString())
    parts.add("\"f17\":" + o.f17.toString())
    parts.add("\"f18\":" + o.f18.toString())
    parts.add("\"f19\":" + _di(o.f19))
    parts.add("\"f20\":" + o.f20.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpWide25(o: Wide25): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + _du(o.f3))
    parts.add("\"f4\":" + _dnf(o.f4))
    parts.add("\"f5\":" + _dn(o.f5))
    parts.add("\"f6\":\"" + _db(o.f6) + "\"")
    parts.add("\"f7\":" + _ds(o.f7))
    parts.add("\"f8\":" + (if (o.f8) "true" else "false"))
    parts.add("\"f9\":" + o.f9.toString())
    parts.add("\"f10\":" + o.f10.toString())
    parts.add("\"f11\":" + o.f11.toString())
    parts.add("\"f12\":" + _di(o.f12))
    parts.add("\"f13\":" + o.f13.toString())
    parts.add("\"f14\":" + o.f14.toString())
    parts.add("\"f15\":" + o.f15.toString())
    parts.add("\"f16\":" + _du(o.f16))
    parts.add("\"f17\":" + _dnf(o.f17))
    parts.add("\"f18\":" + _dn(o.f18))
    parts.add("\"f19\":\"" + _db(o.f19) + "\"")
    parts.add("\"f20\":" + _ds(o.f20))
    parts.add("\"f21\":" + (if (o.f21) "true" else "false"))
    parts.add("\"f22\":" + o.f22.toString())
    parts.add("\"f23\":" + o.f23.toString())
    parts.add("\"f24\":" + o.f24.toString())
    parts.add("\"f25\":" + _di(o.f25))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpWide30(o: Wide30): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + (if (o.f1) "true" else "false"))
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + o.f4.toString())
    parts.add("\"f5\":" + _di(o.f5))
    parts.add("\"f6\":" + o.f6.toString())
    parts.add("\"f7\":" + o.f7.toString())
    parts.add("\"f8\":" + o.f8.toString())
    parts.add("\"f9\":" + _du(o.f9))
    parts.add("\"f10\":" + _dnf(o.f10))
    parts.add("\"f11\":" + _dn(o.f11))
    parts.add("\"f12\":\"" + _db(o.f12) + "\"")
    parts.add("\"f13\":" + _ds(o.f13))
    parts.add("\"f14\":" + (if (o.f14) "true" else "false"))
    parts.add("\"f15\":" + o.f15.toString())
    parts.add("\"f16\":" + o.f16.toString())
    parts.add("\"f17\":" + o.f17.toString())
    parts.add("\"f18\":" + _di(o.f18))
    parts.add("\"f19\":" + o.f19.toString())
    parts.add("\"f20\":" + o.f20.toString())
    parts.add("\"f21\":" + o.f21.toString())
    parts.add("\"f22\":" + _du(o.f22))
    parts.add("\"f23\":" + _dnf(o.f23))
    parts.add("\"f24\":" + _dn(o.f24))
    parts.add("\"f25\":\"" + _db(o.f25) + "\"")
    parts.add("\"f26\":" + _ds(o.f26))
    parts.add("\"f27\":" + (if (o.f27) "true" else "false"))
    parts.add("\"f28\":" + o.f28.toString())
    parts.add("\"f29\":" + o.f29.toString())
    parts.add("\"f30\":" + o.f30.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpWide35(o: Wide35): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + _du(o.f2))
    parts.add("\"f3\":" + _dnf(o.f3))
    parts.add("\"f4\":" + _dn(o.f4))
    parts.add("\"f5\":\"" + _db(o.f5) + "\"")
    parts.add("\"f6\":" + _ds(o.f6))
    parts.add("\"f7\":" + (if (o.f7) "true" else "false"))
    parts.add("\"f8\":" + o.f8.toString())
    parts.add("\"f9\":" + o.f9.toString())
    parts.add("\"f10\":" + o.f10.toString())
    parts.add("\"f11\":" + _di(o.f11))
    parts.add("\"f12\":" + o.f12.toString())
    parts.add("\"f13\":" + o.f13.toString())
    parts.add("\"f14\":" + o.f14.toString())
    parts.add("\"f15\":" + _du(o.f15))
    parts.add("\"f16\":" + _dnf(o.f16))
    parts.add("\"f17\":" + _dn(o.f17))
    parts.add("\"f18\":\"" + _db(o.f18) + "\"")
    parts.add("\"f19\":" + _ds(o.f19))
    parts.add("\"f20\":" + (if (o.f20) "true" else "false"))
    parts.add("\"f21\":" + o.f21.toString())
    parts.add("\"f22\":" + o.f22.toString())
    parts.add("\"f23\":" + o.f23.toString())
    parts.add("\"f24\":" + _di(o.f24))
    parts.add("\"f25\":" + o.f25.toString())
    parts.add("\"f26\":" + o.f26.toString())
    parts.add("\"f27\":" + o.f27.toString())
    parts.add("\"f28\":" + _du(o.f28))
    parts.add("\"f29\":" + _dnf(o.f29))
    parts.add("\"f30\":" + _dn(o.f30))
    parts.add("\"f31\":\"" + _db(o.f31) + "\"")
    parts.add("\"f32\":" + _ds(o.f32))
    parts.add("\"f33\":" + (if (o.f33) "true" else "false"))
    parts.add("\"f34\":" + o.f34.toString())
    parts.add("\"f35\":" + o.f35.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpWide40(o: Wide40): String {
    val parts = mutableListOf<String>()
    parts.add("\"f1\":" + o.f1.toString())
    parts.add("\"f2\":" + o.f2.toString())
    parts.add("\"f3\":" + o.f3.toString())
    parts.add("\"f4\":" + _di(o.f4))
    parts.add("\"f5\":" + o.f5.toString())
    parts.add("\"f6\":" + o.f6.toString())
    parts.add("\"f7\":" + o.f7.toString())
    parts.add("\"f8\":" + _du(o.f8))
    parts.add("\"f9\":" + _dnf(o.f9))
    parts.add("\"f10\":" + _dn(o.f10))
    parts.add("\"f11\":\"" + _db(o.f11) + "\"")
    parts.add("\"f12\":" + _ds(o.f12))
    parts.add("\"f13\":" + (if (o.f13) "true" else "false"))
    parts.add("\"f14\":" + o.f14.toString())
    parts.add("\"f15\":" + o.f15.toString())
    parts.add("\"f16\":" + o.f16.toString())
    parts.add("\"f17\":" + _di(o.f17))
    parts.add("\"f18\":" + o.f18.toString())
    parts.add("\"f19\":" + o.f19.toString())
    parts.add("\"f20\":" + o.f20.toString())
    parts.add("\"f21\":" + _du(o.f21))
    parts.add("\"f22\":" + _dnf(o.f22))
    parts.add("\"f23\":" + _dn(o.f23))
    parts.add("\"f24\":\"" + _db(o.f24) + "\"")
    parts.add("\"f25\":" + _ds(o.f25))
    parts.add("\"f26\":" + (if (o.f26) "true" else "false"))
    parts.add("\"f27\":" + o.f27.toString())
    parts.add("\"f28\":" + o.f28.toString())
    parts.add("\"f29\":" + o.f29.toString())
    parts.add("\"f30\":" + _di(o.f30))
    parts.add("\"f31\":" + o.f31.toString())
    parts.add("\"f32\":" + o.f32.toString())
    parts.add("\"f33\":" + o.f33.toString())
    parts.add("\"f34\":" + _du(o.f34))
    parts.add("\"f35\":" + _dnf(o.f35))
    parts.add("\"f36\":" + _dn(o.f36))
    parts.add("\"f37\":\"" + _db(o.f37) + "\"")
    parts.add("\"f38\":" + _ds(o.f38))
    parts.add("\"f39\":" + (if (o.f39) "true" else "false"))
    parts.add("\"f40\":" + o.f40.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeEmpty(o: EdgeEmpty): String {
    val parts = mutableListOf<String>()

    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeOneOpt(o: EdgeOneOpt): String {
    val parts = mutableListOf<String>()
    o.maybe?.let { parts.add("\"maybe\":" + _ds(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeBigNums(o: EdgeBigNums): String {
    val parts = mutableListOf<String>()
    parts.add("\"i8\":" + o.i8.toString())
    parts.add("\"i16\":" + o.i16.toString())
    parts.add("\"i32\":" + o.i32.toString())
    parts.add("\"i64\":" + _di(o.i64))
    parts.add("\"u8\":" + o.u8.toString())
    parts.add("\"u16\":" + o.u16.toString())
    parts.add("\"u32\":" + o.u32.toString())
    parts.add("\"u64\":" + _du(o.u64))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeZeroVals(o: EdgeZeroVals): String {
    val parts = mutableListOf<String>()
    parts.add("\"s\":" + _ds(o.s))
    parts.add("\"i\":" + o.i.toString())
    parts.add("\"f\":" + _dn(o.f))
    parts.add("\"b\":" + (if (o.b) "true" else "false"))
    parts.add("\"by_field\":\"" + _db(o.by_field) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeNullable(o: EdgeNullable): String {
    val parts = mutableListOf<String>()
    o.a?.let { parts.add("\"a\":" + _ds(it)) }
    o.b?.let { parts.add("\"b\":" + it.toString()) }
    o.c?.let { parts.add("\"c\":" + dumpInner(it)) }
    o.d?.let { parts.add("\"d\":" + it.joinToString(",", "[", "]") { _ds(it) }) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeNegZero(o: EdgeNegZero): String {
    val parts = mutableListOf<String>()
    parts.add("\"v\":" + _dn(o.v))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeNullByte(o: EdgeNullByte): String {
    val parts = mutableListOf<String>()
    parts.add("\"s\":" + _ds(o.s))
    parts.add("\"b\":\"" + _db(o.b) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeBoundary(o: EdgeBoundary): String {
    val parts = mutableListOf<String>()
    parts.add("\"i32_neg129\":" + o.i32_neg129.toString())
    parts.add("\"i32_128\":" + o.i32_128.toString())
    parts.add("\"i32_256\":" + o.i32_256.toString())
    parts.add("\"i32_65536\":" + o.i32_65536.toString())
    parts.add("\"i32_neg32769\":" + o.i32_neg32769.toString())
    parts.add("\"u32_65536\":" + o.u32_65536.toString())
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeStrLen(o: EdgeStrLen): String {
    val parts = mutableListOf<String>()
    parts.add("\"s31\":" + _ds(o.s31))
    parts.add("\"s32\":" + _ds(o.s32))
    parts.add("\"s255\":" + _ds(o.s255))
    parts.add("\"s256\":" + _ds(o.s256))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeBytesLen(o: EdgeBytesLen): String {
    val parts = mutableListOf<String>()
    parts.add("\"b31\":\"" + _db(o.b31) + "\"")
    parts.add("\"b32\":\"" + _db(o.b32) + "\"")
    parts.add("\"b255\":\"" + _db(o.b255) + "\"")
    parts.add("\"b256\":\"" + _db(o.b256) + "\"")
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeArrEmpty(o: EdgeArrEmpty): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { _ds(it) })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpEdgeArrBoundary(o: EdgeArrBoundary): String {
    val parts = mutableListOf<String>()
    parts.add("\"a15\":" + o.a15.joinToString(",", "[", "]") { it.toString() })
    parts.add("\"a16\":" + o.a16.joinToString(",", "[", "]") { it.toString() })
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptArr1(o: OptArr1): String {
    val parts = mutableListOf<String>()
    parts.add("\"req\":" + _ds(o.req))
    o.items?.let { parts.add("\"items\":" + it.joinToString(",", "[", "]") { it.toString() }) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptArr2(o: OptArr2): String {
    val parts = mutableListOf<String>()
    parts.add("\"id\":" + o.id.toString())
    o.names?.let { parts.add("\"names\":" + it.joinToString(",", "[", "]") { _ds(it) }) }
    o.flags?.let { parts.add("\"flags\":" + it.joinToString(",", "[", "]") { if (it) "true" else "false" }) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptArr3(o: OptArr3): String {
    val parts = mutableListOf<String>()
    o.a?.let { parts.add("\"a\":" + it.joinToString(",", "[", "]") { _ds(it) }) }
    o.b?.let { parts.add("\"b\":" + it.joinToString(",", "[", "]") { _dn(it) }) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptArr4(o: OptArr4): String {
    val parts = mutableListOf<String>()
    parts.add("\"payload\":\"" + _db(o.payload) + "\"")
    o.chunks?.let { parts.add("\"chunks\":" + it.joinToString(",", "[", "]") { "\"" + _db(it) + "\"" }) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpOptArr5(o: OptArr5): String {
    val parts = mutableListOf<String>()
    o.models?.let { parts.add("\"models\":" + it.joinToString(",", "[", "]") { dumpInner(it) }) }
    parts.add("\"name\":" + _ds(o.name))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOpt1(o: NestOpt1): String {
    val parts = mutableListOf<String>()
    parts.add("\"outer\":" + dumpLabel(o.outer))
    parts.add("\"name\":" + _ds(o.name))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOpt2(o: NestOpt2): String {
    val parts = mutableListOf<String>()
    o.a?.let { parts.add("\"a\":" + dumpIdVal(it)) }
    o.b?.let { parts.add("\"b\":" + dumpIdVal(it)) }
    o.c?.let { parts.add("\"c\":" + dumpIdVal(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOpt3(o: NestOpt3): String {
    val parts = mutableListOf<String>()
    parts.add("\"money\":" + dumpMoney(o.money))
    o.value_range?.let { parts.add("\"value_range\":" + dumpRange32(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOpt4(o: NestOpt4): String {
    val parts = mutableListOf<String>()
    o.addr?.let { parts.add("\"addr\":" + dumpAddr(it)) }
    o.coord?.let { parts.add("\"coord\":" + dumpCoord(it)) }
    parts.add("\"name\":" + _ds(o.name))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOpt5(o: NestOpt5): String {
    val parts = mutableListOf<String>()
    parts.add("\"point\":" + dumpPoint3(o.point))
    parts.add("\"addr\":" + dumpAddr(o.addr))
    o.label?.let { parts.add("\"label\":" + dumpLabel(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOptInner1(o: NestOptInner1): String {
    val parts = mutableListOf<String>()
    parts.add("\"tag\":" + _ds(o.tag))
    o.nested?.let { parts.add("\"nested\":" + dumpOptInner(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOptInner2(o: NestOptInner2): String {
    val parts = mutableListOf<String>()
    parts.add("\"tag\":" + _ds(o.tag))
    parts.add("\"nested\":" + dumpOptInner(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpNestOptInner3(o: NestOptInner3): String {
    val parts = mutableListOf<String>()
    o.outer?.let { parts.add("\"outer\":" + dumpOptInner(it)) }
    o.nested?.let { parts.add("\"nested\":" + dumpOptInner(it)) }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest1(o: DeepNest1): String {
    val parts = mutableListOf<String>()
    parts.add("\"label\":" + _ds(o.label))
    parts.add("\"nested\":" + dumpAddr(o.nested))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest2(o: DeepNest2): String {
    val parts = mutableListOf<String>()
    parts.add("\"name\":" + _ds(o.name))
    parts.add("\"money\":" + dumpMoney(o.money))
    parts.add("\"addr\":" + dumpAddr(o.addr))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest3(o: DeepNest3): String {
    val parts = mutableListOf<String>()
    parts.add("\"title\":" + _ds(o.title))
    parts.add("\"point\":" + dumpPoint3(o.point))
    parts.add("\"value_range\":" + dumpRange32(o.value_range))
    parts.add("\"money\":" + dumpMoney(o.money))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest4(o: DeepNest4): String {
    val parts = mutableListOf<String>()
    parts.add("\"coords\":" + o.coords.joinToString(",", "[", "]") { dumpCoord(it) })
    parts.add("\"nested\":" + dumpInner(o.nested))
    parts.add("\"tag\":" + _ds(o.tag))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest5(o: DeepNest5): String {
    val parts = mutableListOf<String>()
    parts.add("\"labels\":" + o.labels.joinToString(",", "[", "]") { dumpLabel(it) })
    parts.add("\"money\":" + dumpMoney(o.money))
    parts.add("\"name\":" + _ds(o.name))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest6(o: DeepNest6): String {
    val parts = mutableListOf<String>()
    parts.add("\"items\":" + o.items.joinToString(",", "[", "]") { dumpIdVal(it) })
    o.addr?.let { parts.add("\"addr\":" + dumpAddr(it)) }
    parts.add("\"coord\":" + dumpCoord(o.coord))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpDeepNest7(o: DeepNest7): String {
    val parts = mutableListOf<String>()
    parts.add("\"a\":" + dumpAddr(o.a))
    parts.add("\"b\":" + dumpAddr(o.b))
    parts.add("\"c\":" + dumpAddr(o.c))
    return "{" + parts.joinToString(",") + "}"
}
fun dumpTimestampEntry(o: TimestampEntry): String {
    val parts = mutableListOf<String>()
    parts.add("\"ts\":" + _di(o.ts))
    parts.add("\"event\":" + _ds(o.event))
    o.payload?.let { parts.add("\"payload\":\"" + _db(it) + "\"") }
    return "{" + parts.joinToString(",") + "}"
}
fun dumpConfigEntry(o: ConfigEntry): String {
    val parts = mutableListOf<String>()
    parts.add("\"key\":" + _ds(o.key))
    o.intValue?.let { parts.add("\"intValue\":" + it.toString()) }
    o.strValue?.let { parts.add("\"strValue\":" + _ds(it)) }
    o.boolValue?.let { parts.add("\"boolValue\":" + (if (it) "true" else "false")) }
    o.floatValue?.let { parts.add("\"floatValue\":" + _dn(it)) }
    return "{" + parts.joinToString(",") + "}"
}
