import { testModels } from '../gen.ts';

export function generateDartRunner(): string {
  const mpEntries = testModels.map(n =>
    `  '${n}': (b) { final w = MsgPackWriter(); ${n}Codec.encode(w, ${n}Codec.decode(MsgPackReader(b))); return w.toBytes(); },`
  ).join('\n');
  
  const jsonEntries = testModels.map(n =>
    `  '${n}': (b) { final w = JsonWriter(); ${n}Codec.encode(w, ${n}Codec.decode(JsonReader(b))); return w.toBytes(); },`
  ).join('\n');
  
  const dumpEntries = testModels.map(n =>
    `  '${n}': (b, isMp) => dump${n}(${n}Codec.decode(isMp ? MsgPackReader(b) : JsonReader(b))),`
  ).join('\n');
  
  const names = testModels.map(n => `'${n}'`).join(', ');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
import 'dart:io';
import 'dart:typed_data';
import 'package:specodec/specodec.dart';
import '../lib/test_service_types.dart';
import 'dump_emit.dart';

final _vec = Platform.environment['VEC_DIR']!;
final _out = Platform.environment['OUT_DIR']!;

const testModels = [${names}];

final mpRoundtrip = <String, Uint8List Function(Uint8List)>{
${mpEntries}
};

final jsonRoundtrip = <String, Uint8List Function(Uint8List)>{
${jsonEntries}
};

final dumpRoundtrip = <String, String Function(Uint8List, bool)>{
${dumpEntries}
};

void main() {
  Directory(_out).createSync(recursive: true);
  var fail = 0;

  for (final name in testModels) {
    try {
      final b = File('\$_vec/\$name.msgpack').readAsBytesSync();
      File('\$_out/\$name.msgpack').writeAsBytesSync(mpRoundtrip[name]!(b));
      File('\$_out/\$name.decoded.json').writeAsStringSync(dumpRoundtrip[name]!(b, true));
    } catch (e) { print('FAIL \$name mp: \$e'); fail++; }
    try {
      final b = File('\$_vec/\$name.json').readAsBytesSync();
      File('\$_out/\$name.json').writeAsBytesSync(jsonRoundtrip[name]!(b));
      File('\$_out/\$name.decoded.json').writeAsStringSync(dumpRoundtrip[name]!(b, false));
    } catch (e) { print('FAIL \$name json: \$e'); fail++; }
  }

  print('emit-dart: \${testModels.length * 2 - fail} passed, \$fail failed');
  if (fail > 0) exit(1);
}
`;
}