import { testModels } from '../gen.ts';
import { getDumpFnName } from '../field-naming.ts';

export function generateGoRunner(): string {
  const mpEntries = testModels.map(n =>
    `        "${n}": func(b []byte) []byte {
            r := specodec.NewMsgPackReader(b)
            obj := ${n}Codec.Decode(r)
            w := specodec.NewMsgPackWriter()
            ${n}Codec.Encode(w, obj)
            return w.ToBytes()
        },`
  ).join('\n');
  
  const jsonEntries = testModels.map(n =>
    `        "${n}": func(b []byte) []byte {
            r := specodec.NewJsonReader(b)
            obj := ${n}Codec.Decode(r)
            w := specodec.NewJsonWriter()
            ${n}Codec.Encode(w, obj)
            return w.ToBytes()
        },`
  ).join('\n');
  
  const dumpEntries = testModels.map(n =>
    `        "${n}": func(b []byte, isMp bool) string {
            var obj = ${n}Codec.Decode(func() specodec.SpecReader {
                if isMp { return specodec.NewMsgPackReader(b) }
                return specodec.NewJsonReader(b)
            }())
            return dump${n}(*obj)
        },`
  ).join('\n');
  
  const names = testModels.map(n => `"${n}"`).join(', ');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
package main

import (
    "fmt"
    "os"
    "path/filepath"
    specodec "github.com/specodec/specodec-go"
    . "test/emit_gen"
)

type rtFn func([]byte) []byte
type dumpFn func([]byte, bool) string

var testModels = []string{${names}}

func buildMp() map[string]rtFn {
    return map[string]rtFn{
${mpEntries}
    }
}

func buildJson() map[string]rtFn {
    return map[string]rtFn{
${jsonEntries}
    }
}

func buildDump() map[string]dumpFn {
    return map[string]dumpFn{
${dumpEntries}
    }
}

func runEmit(vecDir, outDir string) {
    mp := buildMp()
    js := buildJson()
    dump := buildDump()
    fail := 0

    for _, name := range testModels {
        n := name
        func() {
            defer func() {
                if r := recover(); r != nil {
                    fmt.Printf("FAIL %s mp: %v\\n", n, r); fail++
                }
            }()
            b, _ := os.ReadFile(filepath.Join(vecDir, n+".msgpack"))
            os.WriteFile(filepath.Join(outDir, n+".msgpack"), mp[n](b), 0644)
            os.WriteFile(filepath.Join(outDir, n+".decoded.json"), []byte(dump[n](b, true)), 0644)
        }()
        func() {
            defer func() {
                if r := recover(); r != nil {
                    fmt.Printf("FAIL %s json: %v\\n", n, r); fail++
                }
            }()
            b, _ := os.ReadFile(filepath.Join(vecDir, n+".json"))
            os.WriteFile(filepath.Join(outDir, n+".json"), js[n](b), 0644)
            os.WriteFile(filepath.Join(outDir, n+".decoded.json"), []byte(dump[n](b, false)), 0644)
        }()
    }

    total := len(testModels) * 2
    fmt.Printf("emit-go: %d passed, %d failed\\n", total-fail, fail)
    if fail > 0 { os.Exit(1) }
}
`;
}