import { testModels } from '../gen.ts';

export function generateKotlinRunner(): string {
  const mpEntries = testModels.map(n =>
    `    "${n}" to { b: ByteArray ->
        val w = MsgPackWriter(); ${n}Codec.encode(w, ${n}Codec.decode(MsgPackReader(b))); w.toBytes() },`
  ).join('\n');
  
  const jsonEntries = testModels.map(n =>
    `    "${n}" to { b: ByteArray ->
        val w = JsonWriter(); ${n}Codec.encode(w, ${n}Codec.decode(JsonReader(b))); w.toBytes() },`
  ).join('\n');
  
  const dumpEntries = testModels.map(n =>
    `    "${n}" to { b: ByteArray, isMp: Boolean ->
        val r = if (isMp) MsgPackReader(b) else JsonReader(b)
        dump${n}(${n}Codec.decode(r)) },`
  ).join('\n');
  
  const names = testModels.map(n => `"${n}"`).join(', ');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
package alltypes
import specodec.*
import java.io.File

val testModels = listOf(${names})

val mpRoundtrip: Map<String, (ByteArray) -> ByteArray> = mapOf(
${mpEntries}
)

val jsonRoundtrip: Map<String, (ByteArray) -> ByteArray> = mapOf(
${jsonEntries}
)

val dumpRoundtrip: Map<String, (ByteArray, Boolean) -> String> = mapOf(
${dumpEntries}
)

fun runEmit(vecDir: String, outDir: String) {
    File(outDir).mkdirs()
    var fail = 0

    for (name in testModels) {
        try {
            val b = File(vecDir, "$name.msgpack").readBytes()
            File(outDir, "$name.msgpack").writeBytes(mpRoundtrip[name]!!(b))
            File(outDir, "$name.decoded.json").writeText(dumpRoundtrip[name]!!(b, true))
        } catch (e: Exception) { println("FAIL $name mp: $e"); fail++ }
        try {
            val b = File(vecDir, "$name.json").readBytes()
            File(outDir, "$name.json").writeBytes(jsonRoundtrip[name]!!(b))
            File(outDir, "$name.decoded.json").writeText(dumpRoundtrip[name]!!(b, false))
        } catch (e: Exception) { println("FAIL $name json: $e"); fail++ }
    }

    val total = testModels.size * 2
    println("emit-kotlin: \${total - fail} passed, \$fail failed")
    if (fail > 0) System.exit(1)
}
`;
}