import { testModels } from '../gen.ts';

export function generatePyRunner(): string {
  const names = testModels.map(n => `    '${n}'`).join(',\n');
  
  return `# Generated by gen_types.cjs. DO NOT EDIT.
import sys, os
sys.path.insert(0, '/specodec-python/src')
from specodec import MsgPackReader, MsgPackWriter, JsonReader, JsonWriter
from gen.test_service_types import *
from dump_emit import dump_model

VEC = os.environ['VEC_DIR']
OUT = os.environ['OUT_DIR']
os.makedirs(OUT, exist_ok=True)

TEST_MODELS = [
${names},
]

fail = 0
for name in TEST_MODELS:
    codec = globals()[f'{name}Codec']
    try:
        b = open(f'{VEC}/{name}.msgpack', 'rb').read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(f'{OUT}/{name}.msgpack', 'wb').write(w.to_bytes())
        open(f'{OUT}/{name}.decoded.json', 'w').write(dump_model(name, obj))
    except Exception as e:
        print(f'FAIL {name} mp: {e}'); fail += 1
    try:
        b = open(f'{VEC}/{name}.json', 'rb').read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(f'{OUT}/{name}.json', 'wb').write(w.to_bytes())
        open(f'{OUT}/{name}.decoded.json', 'w').write(dump_model(name, obj))
    except Exception as e:
        print(f'FAIL {name} json: {e}'); fail += 1

print(f'emit-py: {len(TEST_MODELS)*2 - fail} passed, {fail} failed')
if fail: sys.exit(1)
`;
}