import { testModels } from '../gen.ts';
import { toScreamingRust, toSnakeRust, toRustCodecName, toRustDumpFn } from '../field-naming.ts';

export function generateRustRunner(): string {
  const mpEntries = testModels.map(n => {
    const s = toRustCodecName(n);
    return `    m.insert("${n}", Box::new(|b| {
        let mut r = MsgPackReader::new(b);
        let o = (${s}.decode)(&mut r).unwrap();
        let mut w = MsgPackWriter::new();
        (${s}.encode)(&o, &mut w);
        w.to_bytes()
    }));`;
  }).join('\n');
  
  const jsonEntries = testModels.map(n => {
    const s = toRustCodecName(n);
    return `    m.insert("${n}", Box::new(|b| {
        let mut r = JsonReader::new(b).unwrap();
        let o = (${s}.decode)(&mut r).unwrap();
        let mut w = JsonWriter::new();
        (${s}.encode)(&o, &mut w);
        w.to_bytes()
    }));`;
  }).join('\n');
  
  const dumpEntries = testModels.map(n => {
    const s = toRustCodecName(n);
    const fn = toRustDumpFn(n);
    return `    m.insert("${n}", Box::new(|b, v| {
        let o = if v {
            let mut r = MsgPackReader::new(b);
            (${s}.decode)(&mut r).unwrap()
        } else {
            let mut r = JsonReader::new(b).unwrap();
            (${s}.decode)(&mut r).unwrap()
        };
        ${fn}(&o)
    }));`;
  }).join('\n');
  
  const names = testModels.map(n => `"${n}"`).join(', ');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
use std::collections::HashMap;
use std::path::PathBuf;
use std::fs;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter};

type RtFn = Box<dyn Fn(&[u8]) -> Vec<u8>>;
type DumpFn = Box<dyn Fn(&[u8], bool) -> String>;

fn build_mp() -> HashMap<&'static str, RtFn> {
    let mut m: HashMap<&'static str, RtFn> = HashMap::new();
${mpEntries}
    m
}

fn build_json() -> HashMap<&'static str, RtFn> {
    let mut m: HashMap<&'static str, RtFn> = HashMap::new();
${jsonEntries}
    m
}

fn build_dump() -> HashMap<&'static str, DumpFn> {
    let mut m: HashMap<&'static str, DumpFn> = HashMap::new();
${dumpEntries}
    m
}

static TEST_MODELS: &[&str] = &[${names}];

pub fn run_emit(vec_dir: &PathBuf, out_dir: &PathBuf) {
    let mp = build_mp();
    let json = build_json();
    let dump = build_dump();
    let mut fail = 0usize;

    for &name in TEST_MODELS {
        match fs::read(vec_dir.join(format!("{name}.msgpack"))) {
            Ok(b) => {
                let out = mp[name](&b);
                fs::write(out_dir.join(format!("{name}.msgpack")), &out).unwrap();
                let decoded = dump[name](&b, true);
                fs::write(out_dir.join(format!("{name}.decoded.json")), decoded).unwrap();
            }
            Err(e) => { eprintln!("FAIL {name} mp: {e}"); fail += 1; }
        }
        match fs::read(vec_dir.join(format!("{name}.json"))) {
            Ok(b) => {
                let out = json[name](&b);
                fs::write(out_dir.join(format!("{name}.json")), &out).unwrap();
                let decoded = dump[name](&b, false);
                fs::write(out_dir.join(format!("{name}.decoded.json")), decoded).unwrap();
            }
            Err(e) => { eprintln!("FAIL {name} json: {e}"); fail += 1; }
        }
    }

    let total = TEST_MODELS.len() * 2;
    println!("emit-rust: {} passed, {} failed", total - fail, fail);
    if fail > 0 { std::process::exit(1); }
}
`;
}