import { testModels } from '../gen.ts';

export function generateSwiftRunner(): string {
  const mpEntries = testModels.map(n =>
    `    "${n}": { b in let w = MsgPackWriter(); ${n}Codec.codec.encode(w, try ${n}Codec.codec.decode(MsgPackReader(b))); return w.toBytes() },`
  ).join('\n');
  
  const jsonEntries = testModels.map(n =>
    `    "${n}": { b in let w = JsonWriter(); ${n}Codec.codec.encode(w, try ${n}Codec.codec.decode(JsonReader(b))); return w.toBytes() },`
  ).join('\n');
  
  const dumpEntries = testModels.map(n =>
    `    "${n}": { b, isMp in dump${n}(try ${n}Codec.codec.decode(isMp ? MsgPackReader(b) : JsonReader(b))) },`
  ).join('\n');
  
  const names = testModels.map(n => `"${n}"`).join(', ');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
import Foundation
import Specodec

private typealias RTFn = (Data) throws -> Data
private typealias DumpFn = (Data, Bool) throws -> String

nonisolated(unsafe) private let testModels: [String] = [${names}]

nonisolated(unsafe) private let mpRoundtrip: [String: RTFn] = [
${mpEntries}
]

nonisolated(unsafe) private let jsonRoundtrip: [String: RTFn] = [
${jsonEntries}
]

nonisolated(unsafe) private let dumpRoundtrip: [String: DumpFn] = [
${dumpEntries}
]

func runEmitMain() {
    do { try runEmit() } catch { print("Fatal: \\(error)"); exit(1) }
}

func runEmit() throws {
    let vecDir = ProcessInfo.processInfo.environment["VEC_DIR"]!
    let outDir = ProcessInfo.processInfo.environment["OUT_DIR"]!
    try FileManager.default.createDirectory(
        atPath: outDir, withIntermediateDirectories: true)
    var fail = 0

    for name in testModels {
        do {
            let b = try Data(contentsOf: URL(fileURLWithPath: "\\(vecDir)/\\(name).msgpack"))
            try mpRoundtrip[name]!(b).write(to: URL(fileURLWithPath: "\\(outDir)/\\(name).msgpack"))
            try dumpRoundtrip[name]!(b, true).write(to: URL(fileURLWithPath: "\\(outDir)/\\(name).decoded.json"), atomically: true, encoding: .utf8)
        } catch { print("FAIL \\(name) mp: \\(error)"); fail += 1 }
        do {
            let b = try Data(contentsOf: URL(fileURLWithPath: "\\(vecDir)/\\(name).json"))
            try jsonRoundtrip[name]!(b).write(to: URL(fileURLWithPath: "\\(outDir)/\\(name).json"))
            try dumpRoundtrip[name]!(b, false).write(to: URL(fileURLWithPath: "\\(outDir)/\\(name).decoded.json"), atomically: true, encoding: .utf8)
        } catch { print("FAIL \\(name) json: \\(error)"); fail += 1 }
    }

    let total = testModels.count * 2
    print("emit-swift: \\(total - fail) passed, \\(fail) failed")
    if fail > 0 { exit(1) }
}
`;
}