import { testModels } from '../gen.ts';

export function generateTsRunner(): string {
  const names = testModels.map(n => `"${n}"`).join(', ');
  
  return `// Generated by gen_types.cjs. DO NOT EDIT.
import { MsgPackReader, MsgPackWriter, JsonReader, JsonWriter } from "@specodec/specodec-ts";
import * as gen from "../gen/test-service.types.ts";
import * as fs from "fs";
import * as path from "path";
import { dumpModel } from "./dump_emit.ts";

const VEC = process.env.VEC_DIR!;
const OUT = process.env.OUT_DIR!;
fs.mkdirSync(OUT, { recursive: true });

const TEST_MODELS: string[] = [${names}];

let fail = 0;
for (const name of TEST_MODELS) {
  const codec = (gen as any)[\`\${name}Codec\`];
  try {
    const b = new Uint8Array(fs.readFileSync(path.join(VEC, \`\${name}.msgpack\`)));
    const obj = codec.decode(new MsgPackReader(b));
    const w = new MsgPackWriter();
    codec.encode(w, obj);
    fs.writeFileSync(path.join(OUT, \`\${name}.msgpack\`), Buffer.from(w.toBytes()));
    fs.writeFileSync(path.join(OUT, \`\${name}.decoded.json\`), dumpModel(name, obj));
  } catch(e: any) { console.error(\`FAIL \${name} mp: \${e.message}\`); fail++; }
  try {
    const b = new Uint8Array(fs.readFileSync(path.join(VEC, \`\${name}.json\`)));
    const obj = codec.decode(new JsonReader(b));
    const w = new JsonWriter();
    codec.encode(w, obj);
    fs.writeFileSync(path.join(OUT, \`\${name}.json\`), Buffer.from(w.toBytes()));
    fs.writeFileSync(path.join(OUT, \`\${name}.decoded.json\`), dumpModel(name, obj));
  } catch(e: any) { console.error(\`FAIL \${name} json: \${e.message}\`); fail++; }
}
console.log(\`emit-ts: \${TEST_MODELS.length * 2 - fail} passed, \${fail} failed\`);
if (fail > 0) process.exit(1);
`;
}