// Generated by gen_types.cjs. DO NOT EDIT.
import Foundation

func _ds(_ v: String) -> String {
    var r = ""
    r.append("\"")
    for c in v {
        switch c {
        case "\"": r.append("\\\"")
        case "\\": r.append("\\\\")
        case "\n": r.append("\\n")
        case "\t": r.append("\\t")
        case "\r": r.append("\\r")
        default: if c.asciiValue! < 32 { r.append("\\u" + String(format: "%04x", c.asciiValue!)) } else { r.append(c) }
        }
    }
    r.append("\"")
    return r
}

func _dn(_ v: Double) -> String {
    if v == 0.0 && v < 0 { return "-0" }
    let s = String(v)
    return s.hasSuffix(".0") ? String(s.dropLast(2)) : s
}
func _dnf(_ v: Float) -> String { return _dn(Double(v)) }

func _di(_ v: Int64) -> String { return "\""+String(v)+"\"" }
func _du(_ v: UInt64) -> String { return "\""+String(v)+"\"" }
func _db(_ v: Data) -> String { return v.base64EncodedString() }

func dumpInner(_ o: Inner) -> String {
    var parts: [String] = []
    parts.append("\"x\": " + String(o.x))
    parts.append("\"y\": " + String(o.y))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpCoord(_ o: Coord) -> String {
    var parts: [String] = []
    parts.append("\"lat\": " + _dn(o.lat))
    parts.append("\"lng\": " + _dn(o.lng))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpIdVal(_ o: IdVal) -> String {
    var parts: [String] = []
    parts.append("\"id\": " + _ds(o.id))
    parts.append("\"value\": " + String(o.value))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpLabel(_ o: Label) -> String {
    var parts: [String] = []
    parts.append("\"key\": " + _ds(o.key))
    parts.append("\"text\": " + _ds(o.text))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMoney(_ o: Money) -> String {
    var parts: [String] = []
    parts.append("\"amount\": " + _di(o.amount))
    parts.append("\"currency\": " + _ds(o.currency))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpRange32(_ o: Range32) -> String {
    var parts: [String] = []
    parts.append("\"min\": " + String(o.min))
    parts.append("\"max\": " + String(o.max))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpAddr(_ o: Addr) -> String {
    var parts: [String] = []
    parts.append("\"street\": " + _ds(o.street))
    parts.append("\"city\": " + _ds(o.city))
    parts.append("\"zip\": " + _ds(o.zip))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPoint3(_ o: Point3) -> String {
    var parts: [String] = []
    parts.append("\"x\": " + _dn(o.x))
    parts.append("\"y\": " + _dn(o.y))
    parts.append("\"z\": " + _dn(o.z))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptInner(_ o: OptInner) -> String {
    var parts: [String] = []
    if let v = o.name { parts.append("\"name\": " + _ds(v)) }
    if let v = o.score { parts.append("\"score\": " + _dn(v)) }
    if let v = o.tag { parts.append("\"tag\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleString(_ o: SingleString) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + _ds(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleBoolean(_ o: SingleBoolean) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + (o.v ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleInt8(_ o: SingleInt8) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + String(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleInt16(_ o: SingleInt16) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + String(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleInt32(_ o: SingleInt32) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + String(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleInt64(_ o: SingleInt64) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + _di(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleUint8(_ o: SingleUint8) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + String(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleUint16(_ o: SingleUint16) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + String(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleUint32(_ o: SingleUint32) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + String(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleUint64(_ o: SingleUint64) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + _du(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleFloat32(_ o: SingleFloat32) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + _dnf(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleFloat64(_ o: SingleFloat64) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + _dn(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpSingleBytes(_ o: SingleBytes) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + "\"" + _db(o.v) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleString(_ o: OptSingleString) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleBoolean(_ o: OptSingleBoolean) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + (v ? "true" : "false")) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleInt8(_ o: OptSingleInt8) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleInt16(_ o: OptSingleInt16) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleInt32(_ o: OptSingleInt32) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleInt64(_ o: OptSingleInt64) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + _di(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleUint8(_ o: OptSingleUint8) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleUint16(_ o: OptSingleUint16) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleUint32(_ o: OptSingleUint32) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleUint64(_ o: OptSingleUint64) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + _du(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleFloat32(_ o: OptSingleFloat32) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + _dnf(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleFloat64(_ o: OptSingleFloat64) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + _dn(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptSingleBytes(_ o: OptSingleBytes) -> String {
    var parts: [String] = []
    if let v = o.v { parts.append("\"v\": " + "\"" + _db(v) + "\"") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairString(_ o: PairString) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + _ds(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairBoolean(_ o: PairBoolean) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + (o.a ? "true" : "false"))
    parts.append("\"b\": " + (o.b ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairInt8(_ o: PairInt8) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairInt16(_ o: PairInt16) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairInt32(_ o: PairInt32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairInt64(_ o: PairInt64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _di(o.a))
    parts.append("\"b\": " + _di(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairUint8(_ o: PairUint8) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairUint16(_ o: PairUint16) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairUint32(_ o: PairUint32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairUint64(_ o: PairUint64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _du(o.a))
    parts.append("\"b\": " + _du(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairFloat32(_ o: PairFloat32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dnf(o.a))
    parts.append("\"b\": " + _dnf(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairFloat64(_ o: PairFloat64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dn(o.a))
    parts.append("\"b\": " + _dn(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpPairBytes(_ o: PairBytes) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + "\"" + _db(o.a) + "\"")
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualStringInt32(_ o: DualStringInt32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualStringBoolean(_ o: DualStringBoolean) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + (o.b ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualStringFloat64(_ o: DualStringFloat64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + _dn(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualStringBytes(_ o: DualStringBytes) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt32Boolean(_ o: DualInt32Boolean) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + (o.b ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt32Float64(_ o: DualInt32Float64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _dn(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt32Int64(_ o: DualInt32Int64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _di(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt32Uint32(_ o: DualInt32Uint32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt64Uint64(_ o: DualInt64Uint64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _di(o.a))
    parts.append("\"b\": " + _du(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualFloat32Float64(_ o: DualFloat32Float64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dnf(o.a))
    parts.append("\"b\": " + _dn(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualFloat64Boolean(_ o: DualFloat64Boolean) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dn(o.a))
    parts.append("\"b\": " + (o.b ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualFloat64Bytes(_ o: DualFloat64Bytes) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dn(o.a))
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualUint32Uint64(_ o: DualUint32Uint64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _du(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualBooleanBytes(_ o: DualBooleanBytes) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + (o.a ? "true" : "false"))
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt8Uint8(_ o: DualInt8Uint8) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt16Uint16(_ o: DualInt16Uint16) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualStringInt64(_ o: DualStringInt64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + _di(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualStringUint64(_ o: DualStringUint64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + _du(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt32Bytes(_ o: DualInt32Bytes) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualFloat64Int32(_ o: DualFloat64Int32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dn(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualBooleanInt32(_ o: DualBooleanInt32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + (o.a ? "true" : "false"))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualBytesInt64(_ o: DualBytesInt64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + "\"" + _db(o.a) + "\"")
    parts.append("\"b\": " + _di(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt8Float32(_ o: DualInt8Float32) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _dnf(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualUint8Int16(_ o: DualUint8Int16) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualInt64Float64(_ o: DualInt64Float64) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _di(o.a))
    parts.append("\"b\": " + _dn(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDualUint64String(_ o: DualUint64String) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _du(o.a))
    parts.append("\"b\": " + _ds(o.b))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple01(_ o: Triple01) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + String(o.b))
    parts.append("\"c\": " + (o.c ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple02(_ o: Triple02) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dn(o.a))
    parts.append("\"b\": " + _dn(o.b))
    parts.append("\"c\": " + _dn(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple03(_ o: Triple03) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    parts.append("\"c\": " + String(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple04(_ o: Triple04) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + _ds(o.b))
    parts.append("\"c\": " + String(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple05(_ o: Triple05) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _di(o.a))
    parts.append("\"b\": " + _ds(o.b))
    parts.append("\"c\": " + (o.c ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple06(_ o: Triple06) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _du(o.b))
    parts.append("\"c\": " + _ds(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple07(_ o: Triple07) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + "\"" + _db(o.a) + "\"")
    parts.append("\"b\": " + _ds(o.b))
    parts.append("\"c\": " + String(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple08(_ o: Triple08) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dnf(o.a))
    parts.append("\"b\": " + String(o.b))
    parts.append("\"c\": " + (o.c ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple09(_ o: Triple09) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + _di(o.b))
    parts.append("\"c\": " + _dn(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple10(_ o: Triple10) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + (o.a ? "true" : "false"))
    parts.append("\"b\": " + (o.b ? "true" : "false"))
    parts.append("\"c\": " + (o.c ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple11(_ o: Triple11) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    parts.append("\"c\": " + String(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple12(_ o: Triple12) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + String(o.b))
    parts.append("\"c\": " + String(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple13(_ o: Triple13) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    parts.append("\"c\": " + _dn(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple14(_ o: Triple14) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _di(o.a))
    parts.append("\"b\": " + _du(o.b))
    parts.append("\"c\": " + (o.c ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTriple15(_ o: Triple15) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _dn(o.a))
    parts.append("\"b\": " + _ds(o.b))
    parts.append("\"c\": " + "\"" + _db(o.c) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive01(_ o: Five01) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _ds(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + (o.f3 ? "true" : "false"))
    parts.append("\"f4\": " + _dn(o.f4))
    parts.append("\"f5\": " + "\"" + _db(o.f5) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive02(_ o: Five02) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive03(_ o: Five03) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _ds(o.f1))
    parts.append("\"f2\": " + _ds(o.f2))
    parts.append("\"f3\": " + _ds(o.f3))
    parts.append("\"f4\": " + _ds(o.f4))
    parts.append("\"f5\": " + _ds(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive04(_ o: Five04) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _dn(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + _ds(o.f3))
    parts.append("\"f4\": " + (o.f4 ? "true" : "false"))
    parts.append("\"f5\": " + "\"" + _db(o.f5) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive05(_ o: Five05) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _di(o.f1))
    parts.append("\"f2\": " + _du(o.f2))
    parts.append("\"f3\": " + _ds(o.f3))
    parts.append("\"f4\": " + _dnf(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive06(_ o: Five06) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + (o.f1 ? "true" : "false"))
    parts.append("\"f2\": " + _ds(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + _dn(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive07(_ o: Five07) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + "\"" + _db(o.f1) + "\"")
    parts.append("\"f2\": " + "\"" + _db(o.f2) + "\"")
    parts.append("\"f3\": " + _ds(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + _dn(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive08(_ o: Five08) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive09(_ o: Five09) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _dnf(o.f1))
    parts.append("\"f2\": " + _dn(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + _di(o.f4))
    parts.append("\"f5\": " + _ds(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpFive10(_ o: Five10) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _ds(o.f1))
    parts.append("\"f2\": " + (o.f2 ? "true" : "false"))
    parts.append("\"f3\": " + _di(o.f3))
    parts.append("\"f4\": " + _du(o.f4))
    parts.append("\"f5\": " + _dn(o.f5))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTen01(_ o: Ten01) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _ds(o.f1))
    parts.append("\"f2\": " + (o.f2 ? "true" : "false"))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    parts.append("\"f6\": " + _di(o.f6))
    parts.append("\"f7\": " + String(o.f7))
    parts.append("\"f8\": " + String(o.f8))
    parts.append("\"f9\": " + String(o.f9))
    parts.append("\"f10\": " + _du(o.f10))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTen02(_ o: Ten02) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + _di(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    parts.append("\"f6\": " + String(o.f6))
    parts.append("\"f7\": " + _du(o.f7))
    parts.append("\"f8\": " + _dnf(o.f8))
    parts.append("\"f9\": " + _dn(o.f9))
    parts.append("\"f10\": " + "\"" + _db(o.f10) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTen03(_ o: Ten03) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + _du(o.f4))
    parts.append("\"f5\": " + _dnf(o.f5))
    parts.append("\"f6\": " + _dn(o.f6))
    parts.append("\"f7\": " + "\"" + _db(o.f7) + "\"")
    parts.append("\"f8\": " + _ds(o.f8))
    parts.append("\"f9\": " + (o.f9 ? "true" : "false"))
    parts.append("\"f10\": " + String(o.f10))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTen04(_ o: Ten04) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _du(o.f1))
    parts.append("\"f2\": " + _dnf(o.f2))
    parts.append("\"f3\": " + _dn(o.f3))
    parts.append("\"f4\": " + "\"" + _db(o.f4) + "\"")
    parts.append("\"f5\": " + _ds(o.f5))
    parts.append("\"f6\": " + (o.f6 ? "true" : "false"))
    parts.append("\"f7\": " + String(o.f7))
    parts.append("\"f8\": " + String(o.f8))
    parts.append("\"f9\": " + String(o.f9))
    parts.append("\"f10\": " + _di(o.f10))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTen05(_ o: Ten05) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + "\"" + _db(o.f1) + "\"")
    parts.append("\"f2\": " + _ds(o.f2))
    parts.append("\"f3\": " + (o.f3 ? "true" : "false"))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    parts.append("\"f6\": " + String(o.f6))
    parts.append("\"f7\": " + _di(o.f7))
    parts.append("\"f8\": " + String(o.f8))
    parts.append("\"f9\": " + String(o.f9))
    parts.append("\"f10\": " + String(o.f10))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrString(_ o: ArrString) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { _ds($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrInt32(_ o: ArrInt32) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { String($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrBoolean(_ o: ArrBoolean) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { $0 ? "true" : "false" }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrFloat64(_ o: ArrFloat64) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { _dn($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrBytes(_ o: ArrBytes) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { "\"" + _db($0) + "\"" }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrInt64(_ o: ArrInt64) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { _di($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpArrUint64(_ o: ArrUint64) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { _du($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMultiArr1(_ o: MultiArr1) -> String {
    var parts: [String] = []
    parts.append("\"names\": " + "[" + o.names.map { _ds($0) }.joined(separator: ",") + "]")
    parts.append("\"scores\": " + "[" + o.scores.map { String($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMultiArr2(_ o: MultiArr2) -> String {
    var parts: [String] = []
    parts.append("\"flags\": " + "[" + o.flags.map { $0 ? "true" : "false" }.joined(separator: ",") + "]")
    parts.append("\"values\": " + "[" + o.values.map { _dn($0) }.joined(separator: ",") + "]")
    parts.append("\"payload\": " + "[" + o.payload.map { "\"" + _db($0) + "\"" }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMultiArr3(_ o: MultiArr3) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + "[" + o.a.map { _ds($0) }.joined(separator: ",") + "]")
    parts.append("\"b\": " + "[" + o.b.map { String($0) }.joined(separator: ",") + "]")
    parts.append("\"c\": " + "[" + o.c.map { _dn($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMultiArr4(_ o: MultiArr4) -> String {
    var parts: [String] = []
    parts.append("\"ids\": " + "[" + o.ids.map { _di($0) }.joined(separator: ",") + "]")
    parts.append("\"tags\": " + "[" + o.tags.map { _ds($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMultiArr5(_ o: MultiArr5) -> String {
    var parts: [String] = []
    parts.append("\"xs\": " + "[" + o.xs.map { _du($0) }.joined(separator: ",") + "]")
    parts.append("\"ys\": " + "[" + o.ys.map { _dnf($0) }.joined(separator: ",") + "]")
    parts.append("\"zs\": " + "[" + o.zs.map { $0 ? "true" : "false" }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo1(_ o: OptCombo1) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + _ds(o.req))
    if let v = o.opt_a { parts.append("\"opt_a\": " + String(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo2(_ o: OptCombo2) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + _ds(o.req))
    if let v = o.opt_a { parts.append("\"opt_a\": " + String(v)) }
    if let v = o.opt_b { parts.append("\"opt_b\": " + (v ? "true" : "false")) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo3(_ o: OptCombo3) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + _ds(o.req))
    if let v = o.opt_a { parts.append("\"opt_a\": " + String(v)) }
    if let v = o.opt_b { parts.append("\"opt_b\": " + (v ? "true" : "false")) }
    if let v = o.opt_c { parts.append("\"opt_c\": " + _dn(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo4(_ o: OptCombo4) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + String(o.req))
    if let v = o.opt_a { parts.append("\"opt_a\": " + _ds(v)) }
    if let v = o.opt_b { parts.append("\"opt_b\": " + "\"" + _db(v) + "\"") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo5(_ o: OptCombo5) -> String {
    var parts: [String] = []
    parts.append("\"req1\": " + _ds(o.req1))
    parts.append("\"req2\": " + String(o.req2))
    if let v = o.opt_a { parts.append("\"opt_a\": " + (v ? "true" : "false")) }
    if let v = o.opt_b { parts.append("\"opt_b\": " + _dn(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo6(_ o: OptCombo6) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + _ds(o.req))
    if let v = o.opt_s { parts.append("\"opt_s\": " + _ds(v)) }
    if let v = o.opt_i { parts.append("\"opt_i\": " + String(v)) }
    if let v = o.opt_f { parts.append("\"opt_f\": " + _dn(v)) }
    if let v = o.opt_b { parts.append("\"opt_b\": " + "\"" + _db(v) + "\"") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo7(_ o: OptCombo7) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + _di(o.req))
    if let v = o.opt_u64 { parts.append("\"opt_u64\": " + _du(v)) }
    if let v = o.opt_str { parts.append("\"opt_str\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo8(_ o: OptCombo8) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + _ds(o.a))
    if let v = o.b { parts.append("\"b\": " + String(v)) }
    if let v = o.c { parts.append("\"c\": " + _dn(v)) }
    if let v = o.d { parts.append("\"d\": " + (v ? "true" : "false")) }
    if let v = o.e { parts.append("\"e\": " + "\"" + _db(v) + "\"") }
    if let v = o.f { parts.append("\"f\": " + _di(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo9(_ o: OptCombo9) -> String {
    var parts: [String] = []
    parts.append("\"id\": " + _ds(o.id))
    if let v = o.name { parts.append("\"name\": " + _ds(v)) }
    if let v = o.age { parts.append("\"age\": " + String(v)) }
    if let v = o.score { parts.append("\"score\": " + _dn(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptCombo10(_ o: OptCombo10) -> String {
    var parts: [String] = []
    parts.append("\"code\": " + String(o.code))
    if let v = o.msg { parts.append("\"msg\": " + _ds(v)) }
    if let v = o.detail { parts.append("\"detail\": " + _ds(v)) }
    if let v = o.retry { parts.append("\"retry\": " + (v ? "true" : "false")) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestInner(_ o: NestInner) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpInner(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestCoord(_ o: NestCoord) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpCoord(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestIdVal(_ o: NestIdVal) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpIdVal(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestLabel(_ o: NestLabel) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpLabel(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestMoney(_ o: NestMoney) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpMoney(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestRange32(_ o: NestRange32) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpRange32(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestAddr(_ o: NestAddr) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpAddr(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestPoint3(_ o: NestPoint3) -> String {
    var parts: [String] = []
    parts.append("\"nested\": " + dumpPoint3(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestInner(_ o: OptNestInner) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpInner(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestCoord(_ o: OptNestCoord) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpCoord(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestIdVal(_ o: OptNestIdVal) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpIdVal(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestLabel(_ o: OptNestLabel) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpLabel(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestMoney(_ o: OptNestMoney) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpMoney(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestRange32(_ o: OptNestRange32) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpRange32(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestAddr(_ o: OptNestAddr) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpAddr(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptNestPoint3(_ o: OptNestPoint3) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.nested { parts.append("\"nested\": " + dumpPoint3(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpModelArr1(_ o: ModelArr1) -> String {
    var parts: [String] = []
    parts.append("\"points\": " + "[" + o.points.map { dumpInner($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpModelArr2(_ o: ModelArr2) -> String {
    var parts: [String] = []
    parts.append("\"coords\": " + "[" + o.coords.map { dumpCoord($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpModelArr3(_ o: ModelArr3) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { dumpIdVal($0) }.joined(separator: ",") + "]")
    parts.append("\"tag\": " + _ds(o.tag))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpModelArr4(_ o: ModelArr4) -> String {
    var parts: [String] = []
    parts.append("\"labels\": " + "[" + o.labels.map { dumpLabel($0) }.joined(separator: ",") + "]")
    parts.append("\"count\": " + String(o.count))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpModelArr5(_ o: ModelArr5) -> String {
    var parts: [String] = []
    parts.append("\"arr\": " + "[" + o.arr.map { dumpMoney($0) }.joined(separator: ",") + "]")
    parts.append("\"bs\": " + "[" + o.bs.map { dumpAddr($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix01(_ o: Mix01) -> String {
    var parts: [String] = []
    parts.append("\"name\": " + _ds(o.name))
    parts.append("\"value\": " + String(o.value))
    parts.append("\"point\": " + dumpInner(o.point))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix02(_ o: Mix02) -> String {
    var parts: [String] = []
    parts.append("\"id\": " + _ds(o.id))
    parts.append("\"loc\": " + dumpCoord(o.loc))
    parts.append("\"tags\": " + "[" + o.tags.map { _ds($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix03(_ o: Mix03) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    parts.append("\"value_range\": " + dumpRange32(o.value_range))
    parts.append("\"active\": " + (o.active ? "true" : "false"))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix04(_ o: Mix04) -> String {
    var parts: [String] = []
    parts.append("\"title\": " + _ds(o.title))
    parts.append("\"price\": " + dumpMoney(o.price))
    parts.append("\"inStock\": " + (o.inStock ? "true" : "false"))
    parts.append("\"rating\": " + _dn(o.rating))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix05(_ o: Mix05) -> String {
    var parts: [String] = []
    parts.append("\"addr\": " + dumpAddr(o.addr))
    parts.append("\"coords\": " + "[" + o.coords.map { dumpCoord($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix06(_ o: Mix06) -> String {
    var parts: [String] = []
    parts.append("\"name\": " + _ds(o.name))
    parts.append("\"age\": " + String(o.age))
    if let v = o.address { parts.append("\"address\": " + dumpAddr(v)) }
    if let v = o.email { parts.append("\"email\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix07(_ o: Mix07) -> String {
    var parts: [String] = []
    parts.append("\"origin\": " + dumpPoint3(o.origin))
    parts.append("\"dest\": " + dumpPoint3(o.dest))
    parts.append("\"distance\": " + _dn(o.distance))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix08(_ o: Mix08) -> String {
    var parts: [String] = []
    parts.append("\"keys\": " + "[" + o.keys.map { _ds($0) }.joined(separator: ",") + "]")
    parts.append("\"values\": " + "[" + o.values.map { String($0) }.joined(separator: ",") + "]")
    if let v = o.meta { parts.append("\"meta\": " + dumpLabel(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix09(_ o: Mix09) -> String {
    var parts: [String] = []
    parts.append("\"id\": " + _di(o.id))
    parts.append("\"payload\": " + "\"" + _db(o.payload) + "\"")
    parts.append("\"checksum\": " + String(o.checksum))
    if let v = o.prev { parts.append("\"prev\": " + dumpIdVal(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix10(_ o: Mix10) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { _ds($0) }.joined(separator: ",") + "]")
    parts.append("\"total\": " + String(o.total))
    parts.append("\"avg\": " + _dn(o.avg))
    parts.append("\"value_range\": " + dumpRange32(o.value_range))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix11(_ o: Mix11) -> String {
    var parts: [String] = []
    parts.append("\"name\": " + _ds(o.name))
    parts.append("\"values\": " + "[" + o.values.map { _dn($0) }.joined(separator: ",") + "]")
    if let v = o.nested { parts.append("\"nested\": " + dumpInner(v)) }
    if let v = o.flag { parts.append("\"flag\": " + (v ? "true" : "false")) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix12(_ o: Mix12) -> String {
    var parts: [String] = []
    parts.append("\"header\": " + _ds(o.header))
    parts.append("\"entries\": " + "[" + o.entries.map { dumpIdVal($0) }.joined(separator: ",") + "]")
    if let v = o.footer { parts.append("\"footer\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix13(_ o: Mix13) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _dn(o.b))
    parts.append("\"c\": " + _ds(o.c))
    parts.append("\"d\": " + (o.d ? "true" : "false"))
    parts.append("\"e\": " + "\"" + _db(o.e) + "\"")
    parts.append("\"nested\": " + dumpInner(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix14(_ o: Mix14) -> String {
    var parts: [String] = []
    parts.append("\"amounts\": " + "[" + o.amounts.map { dumpMoney($0) }.joined(separator: ",") + "]")
    parts.append("\"total\": " + _di(o.total))
    parts.append("\"currency\": " + _ds(o.currency))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpMix15(_ o: Mix15) -> String {
    var parts: [String] = []
    parts.append("\"src_addr\": " + dumpAddr(o.src_addr))
    parts.append("\"dst_addr\": " + dumpAddr(o.dst_addr))
    parts.append("\"distance\": " + _dn(o.distance))
    parts.append("\"duration\": " + _dn(o.duration))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpAllOpt1(_ o: AllOpt1) -> String {
    var parts: [String] = []
    if let v = o.a { parts.append("\"a\": " + _ds(v)) }
    if let v = o.b { parts.append("\"b\": " + String(v)) }
    if let v = o.c { parts.append("\"c\": " + (v ? "true" : "false")) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpAllOpt2(_ o: AllOpt2) -> String {
    var parts: [String] = []
    if let v = o.x { parts.append("\"x\": " + _dn(v)) }
    if let v = o.y { parts.append("\"y\": " + "\"" + _db(v) + "\"") }
    if let v = o.z { parts.append("\"z\": " + _di(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpAllOpt3(_ o: AllOpt3) -> String {
    var parts: [String] = []
    if let v = o.name { parts.append("\"name\": " + _ds(v)) }
    if let v = o.age { parts.append("\"age\": " + String(v)) }
    if let v = o.score { parts.append("\"score\": " + _dn(v)) }
    if let v = o.active { parts.append("\"active\": " + (v ? "true" : "false")) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpAllOpt4(_ o: AllOpt4) -> String {
    var parts: [String] = []
    if let v = o.a { parts.append("\"a\": " + String(v)) }
    if let v = o.b { parts.append("\"b\": " + _du(v)) }
    if let v = o.c { parts.append("\"c\": " + String(v)) }
    if let v = o.d { parts.append("\"d\": " + _ds(v)) }
    if let v = o.e { parts.append("\"e\": " + "\"" + _db(v) + "\"") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpAllOpt5(_ o: AllOpt5) -> String {
    var parts: [String] = []
    if let v = o.p { parts.append("\"p\": " + dumpInner(v)) }
    if let v = o.q { parts.append("\"q\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpRecList(_ o: RecList) -> String {
    var parts: [String] = []
    parts.append("\"value\": " + String(o.value))
    if let v = o.next { parts.append("\"next\": " + dumpRecList(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpRecTree(_ o: RecTree) -> String {
    var parts: [String] = []
    parts.append("\"value\": " + _ds(o.value))
    if let v = o.left_node { parts.append("\"left_node\": " + dumpRecTree(v)) }
    if let v = o.right_node { parts.append("\"right_node\": " + dumpRecTree(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpRecChain(_ o: RecChain) -> String {
    var parts: [String] = []
    parts.append("\"id\": " + String(o.id))
    parts.append("\"label\": " + _ds(o.label))
    if let v = o.next { parts.append("\"next\": " + dumpRecChain(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpRecWrap(_ o: RecWrap) -> String {
    var parts: [String] = []
    parts.append("\"payload\": " + "\"" + _db(o.payload) + "\"")
    if let v = o.nested { parts.append("\"nested\": " + dumpRecWrap(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpRecWide(_ o: RecWide) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + String(o.a))
    parts.append("\"b\": " + _ds(o.b))
    parts.append("\"c\": " + _dn(o.c))
    if let v = o.child { parts.append("\"child\": " + dumpRecWide(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpWide20(_ o: Wide20) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + _ds(o.f1))
    parts.append("\"f2\": " + (o.f2 ? "true" : "false"))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    parts.append("\"f6\": " + _di(o.f6))
    parts.append("\"f7\": " + String(o.f7))
    parts.append("\"f8\": " + String(o.f8))
    parts.append("\"f9\": " + String(o.f9))
    parts.append("\"f10\": " + _du(o.f10))
    parts.append("\"f11\": " + _dnf(o.f11))
    parts.append("\"f12\": " + _dn(o.f12))
    parts.append("\"f13\": " + "\"" + _db(o.f13) + "\"")
    parts.append("\"f14\": " + _ds(o.f14))
    parts.append("\"f15\": " + (o.f15 ? "true" : "false"))
    parts.append("\"f16\": " + String(o.f16))
    parts.append("\"f17\": " + String(o.f17))
    parts.append("\"f18\": " + String(o.f18))
    parts.append("\"f19\": " + _di(o.f19))
    parts.append("\"f20\": " + String(o.f20))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpWide25(_ o: Wide25) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + _du(o.f3))
    parts.append("\"f4\": " + _dnf(o.f4))
    parts.append("\"f5\": " + _dn(o.f5))
    parts.append("\"f6\": " + "\"" + _db(o.f6) + "\"")
    parts.append("\"f7\": " + _ds(o.f7))
    parts.append("\"f8\": " + (o.f8 ? "true" : "false"))
    parts.append("\"f9\": " + String(o.f9))
    parts.append("\"f10\": " + String(o.f10))
    parts.append("\"f11\": " + String(o.f11))
    parts.append("\"f12\": " + _di(o.f12))
    parts.append("\"f13\": " + String(o.f13))
    parts.append("\"f14\": " + String(o.f14))
    parts.append("\"f15\": " + String(o.f15))
    parts.append("\"f16\": " + _du(o.f16))
    parts.append("\"f17\": " + _dnf(o.f17))
    parts.append("\"f18\": " + _dn(o.f18))
    parts.append("\"f19\": " + "\"" + _db(o.f19) + "\"")
    parts.append("\"f20\": " + _ds(o.f20))
    parts.append("\"f21\": " + (o.f21 ? "true" : "false"))
    parts.append("\"f22\": " + String(o.f22))
    parts.append("\"f23\": " + String(o.f23))
    parts.append("\"f24\": " + String(o.f24))
    parts.append("\"f25\": " + _di(o.f25))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpWide30(_ o: Wide30) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + (o.f1 ? "true" : "false"))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + String(o.f4))
    parts.append("\"f5\": " + _di(o.f5))
    parts.append("\"f6\": " + String(o.f6))
    parts.append("\"f7\": " + String(o.f7))
    parts.append("\"f8\": " + String(o.f8))
    parts.append("\"f9\": " + _du(o.f9))
    parts.append("\"f10\": " + _dnf(o.f10))
    parts.append("\"f11\": " + _dn(o.f11))
    parts.append("\"f12\": " + "\"" + _db(o.f12) + "\"")
    parts.append("\"f13\": " + _ds(o.f13))
    parts.append("\"f14\": " + (o.f14 ? "true" : "false"))
    parts.append("\"f15\": " + String(o.f15))
    parts.append("\"f16\": " + String(o.f16))
    parts.append("\"f17\": " + String(o.f17))
    parts.append("\"f18\": " + _di(o.f18))
    parts.append("\"f19\": " + String(o.f19))
    parts.append("\"f20\": " + String(o.f20))
    parts.append("\"f21\": " + String(o.f21))
    parts.append("\"f22\": " + _du(o.f22))
    parts.append("\"f23\": " + _dnf(o.f23))
    parts.append("\"f24\": " + _dn(o.f24))
    parts.append("\"f25\": " + "\"" + _db(o.f25) + "\"")
    parts.append("\"f26\": " + _ds(o.f26))
    parts.append("\"f27\": " + (o.f27 ? "true" : "false"))
    parts.append("\"f28\": " + String(o.f28))
    parts.append("\"f29\": " + String(o.f29))
    parts.append("\"f30\": " + String(o.f30))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpWide35(_ o: Wide35) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + _du(o.f2))
    parts.append("\"f3\": " + _dnf(o.f3))
    parts.append("\"f4\": " + _dn(o.f4))
    parts.append("\"f5\": " + "\"" + _db(o.f5) + "\"")
    parts.append("\"f6\": " + _ds(o.f6))
    parts.append("\"f7\": " + (o.f7 ? "true" : "false"))
    parts.append("\"f8\": " + String(o.f8))
    parts.append("\"f9\": " + String(o.f9))
    parts.append("\"f10\": " + String(o.f10))
    parts.append("\"f11\": " + _di(o.f11))
    parts.append("\"f12\": " + String(o.f12))
    parts.append("\"f13\": " + String(o.f13))
    parts.append("\"f14\": " + String(o.f14))
    parts.append("\"f15\": " + _du(o.f15))
    parts.append("\"f16\": " + _dnf(o.f16))
    parts.append("\"f17\": " + _dn(o.f17))
    parts.append("\"f18\": " + "\"" + _db(o.f18) + "\"")
    parts.append("\"f19\": " + _ds(o.f19))
    parts.append("\"f20\": " + (o.f20 ? "true" : "false"))
    parts.append("\"f21\": " + String(o.f21))
    parts.append("\"f22\": " + String(o.f22))
    parts.append("\"f23\": " + String(o.f23))
    parts.append("\"f24\": " + _di(o.f24))
    parts.append("\"f25\": " + String(o.f25))
    parts.append("\"f26\": " + String(o.f26))
    parts.append("\"f27\": " + String(o.f27))
    parts.append("\"f28\": " + _du(o.f28))
    parts.append("\"f29\": " + _dnf(o.f29))
    parts.append("\"f30\": " + _dn(o.f30))
    parts.append("\"f31\": " + "\"" + _db(o.f31) + "\"")
    parts.append("\"f32\": " + _ds(o.f32))
    parts.append("\"f33\": " + (o.f33 ? "true" : "false"))
    parts.append("\"f34\": " + String(o.f34))
    parts.append("\"f35\": " + String(o.f35))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpWide40(_ o: Wide40) -> String {
    var parts: [String] = []
    parts.append("\"f1\": " + String(o.f1))
    parts.append("\"f2\": " + String(o.f2))
    parts.append("\"f3\": " + String(o.f3))
    parts.append("\"f4\": " + _di(o.f4))
    parts.append("\"f5\": " + String(o.f5))
    parts.append("\"f6\": " + String(o.f6))
    parts.append("\"f7\": " + String(o.f7))
    parts.append("\"f8\": " + _du(o.f8))
    parts.append("\"f9\": " + _dnf(o.f9))
    parts.append("\"f10\": " + _dn(o.f10))
    parts.append("\"f11\": " + "\"" + _db(o.f11) + "\"")
    parts.append("\"f12\": " + _ds(o.f12))
    parts.append("\"f13\": " + (o.f13 ? "true" : "false"))
    parts.append("\"f14\": " + String(o.f14))
    parts.append("\"f15\": " + String(o.f15))
    parts.append("\"f16\": " + String(o.f16))
    parts.append("\"f17\": " + _di(o.f17))
    parts.append("\"f18\": " + String(o.f18))
    parts.append("\"f19\": " + String(o.f19))
    parts.append("\"f20\": " + String(o.f20))
    parts.append("\"f21\": " + _du(o.f21))
    parts.append("\"f22\": " + _dnf(o.f22))
    parts.append("\"f23\": " + _dn(o.f23))
    parts.append("\"f24\": " + "\"" + _db(o.f24) + "\"")
    parts.append("\"f25\": " + _ds(o.f25))
    parts.append("\"f26\": " + (o.f26 ? "true" : "false"))
    parts.append("\"f27\": " + String(o.f27))
    parts.append("\"f28\": " + String(o.f28))
    parts.append("\"f29\": " + String(o.f29))
    parts.append("\"f30\": " + _di(o.f30))
    parts.append("\"f31\": " + String(o.f31))
    parts.append("\"f32\": " + String(o.f32))
    parts.append("\"f33\": " + String(o.f33))
    parts.append("\"f34\": " + _du(o.f34))
    parts.append("\"f35\": " + _dnf(o.f35))
    parts.append("\"f36\": " + _dn(o.f36))
    parts.append("\"f37\": " + "\"" + _db(o.f37) + "\"")
    parts.append("\"f38\": " + _ds(o.f38))
    parts.append("\"f39\": " + (o.f39 ? "true" : "false"))
    parts.append("\"f40\": " + String(o.f40))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeEmpty(_ o: EdgeEmpty) -> String {
    var parts: [String] = []

    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeOneOpt(_ o: EdgeOneOpt) -> String {
    var parts: [String] = []
    if let v = o.maybe { parts.append("\"maybe\": " + _ds(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeBigNums(_ o: EdgeBigNums) -> String {
    var parts: [String] = []
    parts.append("\"i8\": " + String(o.i8))
    parts.append("\"i16\": " + String(o.i16))
    parts.append("\"i32\": " + String(o.i32))
    parts.append("\"i64\": " + _di(o.i64))
    parts.append("\"u8\": " + String(o.u8))
    parts.append("\"u16\": " + String(o.u16))
    parts.append("\"u32\": " + String(o.u32))
    parts.append("\"u64\": " + _du(o.u64))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeZeroVals(_ o: EdgeZeroVals) -> String {
    var parts: [String] = []
    parts.append("\"s\": " + _ds(o.s))
    parts.append("\"i\": " + String(o.i))
    parts.append("\"f\": " + _dn(o.f))
    parts.append("\"b\": " + (o.b ? "true" : "false"))
    parts.append("\"by_field\": " + "\"" + _db(o.by_field) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeNullable(_ o: EdgeNullable) -> String {
    var parts: [String] = []
    if let v = o.a { parts.append("\"a\": " + _ds(v)) }
    if let v = o.b { parts.append("\"b\": " + String(v)) }
    if let v = o.c { parts.append("\"c\": " + dumpInner(v)) }
    if let v = o.d { parts.append("\"d\": " + "[" + v.map { _ds($0) }.joined(separator: ",") + "]") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeNegZero(_ o: EdgeNegZero) -> String {
    var parts: [String] = []
    parts.append("\"v\": " + _dn(o.v))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeNullByte(_ o: EdgeNullByte) -> String {
    var parts: [String] = []
    parts.append("\"s\": " + _ds(o.s))
    parts.append("\"b\": " + "\"" + _db(o.b) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeBoundary(_ o: EdgeBoundary) -> String {
    var parts: [String] = []
    parts.append("\"i32_neg129\": " + String(o.i32_neg129))
    parts.append("\"i32_128\": " + String(o.i32_128))
    parts.append("\"i32_256\": " + String(o.i32_256))
    parts.append("\"i32_65536\": " + String(o.i32_65536))
    parts.append("\"i32_neg32769\": " + String(o.i32_neg32769))
    parts.append("\"u32_65536\": " + String(o.u32_65536))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeStrLen(_ o: EdgeStrLen) -> String {
    var parts: [String] = []
    parts.append("\"s31\": " + _ds(o.s31))
    parts.append("\"s32\": " + _ds(o.s32))
    parts.append("\"s255\": " + _ds(o.s255))
    parts.append("\"s256\": " + _ds(o.s256))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeBytesLen(_ o: EdgeBytesLen) -> String {
    var parts: [String] = []
    parts.append("\"b31\": " + "\"" + _db(o.b31) + "\"")
    parts.append("\"b32\": " + "\"" + _db(o.b32) + "\"")
    parts.append("\"b255\": " + "\"" + _db(o.b255) + "\"")
    parts.append("\"b256\": " + "\"" + _db(o.b256) + "\"")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeArrEmpty(_ o: EdgeArrEmpty) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { _ds($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpEdgeArrBoundary(_ o: EdgeArrBoundary) -> String {
    var parts: [String] = []
    parts.append("\"a15\": " + "[" + o.a15.map { String($0) }.joined(separator: ",") + "]")
    parts.append("\"a16\": " + "[" + o.a16.map { String($0) }.joined(separator: ",") + "]")
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptArr1(_ o: OptArr1) -> String {
    var parts: [String] = []
    parts.append("\"req\": " + _ds(o.req))
    if let v = o.items { parts.append("\"items\": " + "[" + v.map { String($0) }.joined(separator: ",") + "]") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptArr2(_ o: OptArr2) -> String {
    var parts: [String] = []
    parts.append("\"id\": " + String(o.id))
    if let v = o.names { parts.append("\"names\": " + "[" + v.map { _ds($0) }.joined(separator: ",") + "]") }
    if let v = o.flags { parts.append("\"flags\": " + "[" + v.map { $0 ? "true" : "false" }.joined(separator: ",") + "]") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptArr3(_ o: OptArr3) -> String {
    var parts: [String] = []
    if let v = o.a { parts.append("\"a\": " + "[" + v.map { _ds($0) }.joined(separator: ",") + "]") }
    if let v = o.b { parts.append("\"b\": " + "[" + v.map { _dn($0) }.joined(separator: ",") + "]") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptArr4(_ o: OptArr4) -> String {
    var parts: [String] = []
    parts.append("\"payload\": " + "\"" + _db(o.payload) + "\"")
    if let v = o.chunks { parts.append("\"chunks\": " + "[" + v.map { "\"" + _db($0) + "\"" }.joined(separator: ",") + "]") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpOptArr5(_ o: OptArr5) -> String {
    var parts: [String] = []
    if let v = o.models { parts.append("\"models\": " + "[" + v.map { dumpInner($0) }.joined(separator: ",") + "]") }
    parts.append("\"name\": " + _ds(o.name))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOpt1(_ o: NestOpt1) -> String {
    var parts: [String] = []
    parts.append("\"outer\": " + dumpLabel(o.outer))
    parts.append("\"name\": " + _ds(o.name))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOpt2(_ o: NestOpt2) -> String {
    var parts: [String] = []
    if let v = o.a { parts.append("\"a\": " + dumpIdVal(v)) }
    if let v = o.b { parts.append("\"b\": " + dumpIdVal(v)) }
    if let v = o.c { parts.append("\"c\": " + dumpIdVal(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOpt3(_ o: NestOpt3) -> String {
    var parts: [String] = []
    parts.append("\"money\": " + dumpMoney(o.money))
    if let v = o.value_range { parts.append("\"value_range\": " + dumpRange32(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOpt4(_ o: NestOpt4) -> String {
    var parts: [String] = []
    if let v = o.addr { parts.append("\"addr\": " + dumpAddr(v)) }
    if let v = o.coord { parts.append("\"coord\": " + dumpCoord(v)) }
    parts.append("\"name\": " + _ds(o.name))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOpt5(_ o: NestOpt5) -> String {
    var parts: [String] = []
    parts.append("\"point\": " + dumpPoint3(o.point))
    parts.append("\"addr\": " + dumpAddr(o.addr))
    if let v = o.label { parts.append("\"label\": " + dumpLabel(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOptInner1(_ o: NestOptInner1) -> String {
    var parts: [String] = []
    parts.append("\"tag\": " + _ds(o.tag))
    if let v = o.nested { parts.append("\"nested\": " + dumpOptInner(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOptInner2(_ o: NestOptInner2) -> String {
    var parts: [String] = []
    parts.append("\"tag\": " + _ds(o.tag))
    parts.append("\"nested\": " + dumpOptInner(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpNestOptInner3(_ o: NestOptInner3) -> String {
    var parts: [String] = []
    if let v = o.outer { parts.append("\"outer\": " + dumpOptInner(v)) }
    if let v = o.nested { parts.append("\"nested\": " + dumpOptInner(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest1(_ o: DeepNest1) -> String {
    var parts: [String] = []
    parts.append("\"label\": " + _ds(o.label))
    parts.append("\"nested\": " + dumpAddr(o.nested))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest2(_ o: DeepNest2) -> String {
    var parts: [String] = []
    parts.append("\"name\": " + _ds(o.name))
    parts.append("\"money\": " + dumpMoney(o.money))
    parts.append("\"addr\": " + dumpAddr(o.addr))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest3(_ o: DeepNest3) -> String {
    var parts: [String] = []
    parts.append("\"title\": " + _ds(o.title))
    parts.append("\"point\": " + dumpPoint3(o.point))
    parts.append("\"value_range\": " + dumpRange32(o.value_range))
    parts.append("\"money\": " + dumpMoney(o.money))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest4(_ o: DeepNest4) -> String {
    var parts: [String] = []
    parts.append("\"coords\": " + "[" + o.coords.map { dumpCoord($0) }.joined(separator: ",") + "]")
    parts.append("\"nested\": " + dumpInner(o.nested))
    parts.append("\"tag\": " + _ds(o.tag))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest5(_ o: DeepNest5) -> String {
    var parts: [String] = []
    parts.append("\"labels\": " + "[" + o.labels.map { dumpLabel($0) }.joined(separator: ",") + "]")
    parts.append("\"money\": " + dumpMoney(o.money))
    parts.append("\"name\": " + _ds(o.name))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest6(_ o: DeepNest6) -> String {
    var parts: [String] = []
    parts.append("\"items\": " + "[" + o.items.map { dumpIdVal($0) }.joined(separator: ",") + "]")
    if let v = o.addr { parts.append("\"addr\": " + dumpAddr(v)) }
    parts.append("\"coord\": " + dumpCoord(o.coord))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpDeepNest7(_ o: DeepNest7) -> String {
    var parts: [String] = []
    parts.append("\"a\": " + dumpAddr(o.a))
    parts.append("\"b\": " + dumpAddr(o.b))
    parts.append("\"c\": " + dumpAddr(o.c))
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpTimestampEntry(_ o: TimestampEntry) -> String {
    var parts: [String] = []
    parts.append("\"ts\": " + _di(o.ts))
    parts.append("\"event\": " + _ds(o.event))
    if let v = o.payload { parts.append("\"payload\": " + "\"" + _db(v) + "\"") }
    return "{" + parts.joined(separator: ",") + "}"
}
func dumpConfigEntry(_ o: ConfigEntry) -> String {
    var parts: [String] = []
    parts.append("\"key\": " + _ds(o.key))
    if let v = o.intValue { parts.append("\"intValue\": " + String(v)) }
    if let v = o.strValue { parts.append("\"strValue\": " + _ds(v)) }
    if let v = o.boolValue { parts.append("\"boolValue\": " + (v ? "true" : "false")) }
    if let v = o.floatValue { parts.append("\"floatValue\": " + _dn(v)) }
    return "{" + parts.joined(separator: ",") + "}"
}
