// Generated by gen_types.cjs. DO NOT EDIT.
use std::fmt::Write;

fn _ds(v: &str) -> String {
    let mut r = String::new();
    r.push('"');
    for c in v.chars() {
        match c {
            '\x22' => { r.push('\x5c'); r.push('\x22'); }
            '\x5c' => { r.push('\x5c'); r.push('\x5c'); }
            '\x0a' => { r.push('\x5c'); r.push('n'); }
            '\x09' => { r.push('\x5c'); r.push('t'); }
            '\x0d' => { r.push('\x5c'); r.push('r'); }
            c if (c as u32) < 0x20 => { write!(r, "\\u{:04x}", c as u32).unwrap(); }
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

fn _dn(v: f64) -> String {
    if v == 0.0 && v.is_sign_negative() { return "-0".to_string(); }
    let s = format!("{}", v);
    if s.ends_with(".0") { s[..s.len()-2].to_string() } else { s }
}

fn _di(v: i64) -> String { format!("\"{}\"", v) }
fn _du(v: u64) -> String { format!("\"{}\"", v) }
fn _db(v: &[u8]) -> String {
    use base64::{Engine as _, engine::general_purpose::STANDARD};
    STANDARD.encode(v)
}

fn dump_inner(o: &Inner) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"x\":{}", o.x.toString()));
    parts.push(format!("\"y\":{}", o.y.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_coord(o: &Coord) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"lat\":{}", _dn(o.lat)));
    parts.push(format!("\"lng\":{}", _dn(o.lng)));
    format!("{{{}}}", parts.join(","))
}
fn dump_id_val(o: &IdVal) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"id\":{}", _ds(&o.id)));
    parts.push(format!("\"value\":{}", o.value.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_label(o: &Label) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"key\":{}", _ds(&o.key)));
    parts.push(format!("\"text\":{}", _ds(&o.text)));
    format!("{{{}}}", parts.join(","))
}
fn dump_money(o: &Money) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"amount\":{}", _di(o.amount)));
    parts.push(format!("\"currency\":{}", _ds(&o.currency)));
    format!("{{{}}}", parts.join(","))
}
fn dump_range32(o: &Range32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"min\":{}", o.min.toString()));
    parts.push(format!("\"max\":{}", o.max.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_addr(o: &Addr) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"street\":{}", _ds(&o.street)));
    parts.push(format!("\"city\":{}", _ds(&o.city)));
    parts.push(format!("\"zip\":{}", _ds(&o.zip)));
    format!("{{{}}}", parts.join(","))
}
fn dump_point3(o: &Point3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"x\":{}", _dn(o.x)));
    parts.push(format!("\"y\":{}", _dn(o.y)));
    parts.push(format!("\"z\":{}", _dn(o.z)));
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_inner(o: &OptInner) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.name { parts.push(format!("\"name\":{}", _ds(v))); }
    if let Some(v) = &o.score { parts.push(format!("\"score\":{}", _dn(*v as f64))); }
    if let Some(v) = &o.tag { parts.push(format!("\"tag\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_single_string(o: &SingleString) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", _ds(&o.v)));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_boolean(o: &SingleBoolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", if o.v { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_int8(o: &SingleInt8) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", o.v.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_int16(o: &SingleInt16) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", o.v.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_int32(o: &SingleInt32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", o.v.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_int64(o: &SingleInt64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", _di(o.v)));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_uint8(o: &SingleUint8) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", o.v.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_uint16(o: &SingleUint16) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", o.v.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_uint32(o: &SingleUint32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", o.v.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_uint64(o: &SingleUint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", _du(o.v)));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_float32(o: &SingleFloat32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", _dnf(o.v)));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_float64(o: &SingleFloat64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", _dn(o.v)));
    format!("{{{}}}", parts.join(","))
}
fn dump_single_bytes(o: &SingleBytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", format!("\"{}\"", _db(&o.v))));
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_string(o: &OptSingleString) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_boolean(o: &OptSingleBoolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", if *v { "true" } else { "false" })); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_int8(o: &OptSingleInt8) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_int16(o: &OptSingleInt16) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_int32(o: &OptSingleInt32) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_int64(o: &OptSingleInt64) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", _di(*v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_uint8(o: &OptSingleUint8) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_uint16(o: &OptSingleUint16) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_uint32(o: &OptSingleUint32) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_uint64(o: &OptSingleUint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", _du(*v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_float32(o: &OptSingleFloat32) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", _dn(*v as f64))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_float64(o: &OptSingleFloat64) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", _dn(*v as f64))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_single_bytes(o: &OptSingleBytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.v { parts.push(format!("\"v\":{}", format!("\"{}\"", _db(v)))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_string(o: &PairString) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_boolean(o: &PairBoolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", if o.a { "true" } else { "false" }));
    parts.push(format!("\"b\":{}", if o.b { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_int8(o: &PairInt8) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_int16(o: &PairInt16) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_int32(o: &PairInt32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_int64(o: &PairInt64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _di(o.a)));
    parts.push(format!("\"b\":{}", _di(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_uint8(o: &PairUint8) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_uint16(o: &PairUint16) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_uint32(o: &PairUint32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_uint64(o: &PairUint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _du(o.a)));
    parts.push(format!("\"b\":{}", _du(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_float32(o: &PairFloat32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dnf(o.a)));
    parts.push(format!("\"b\":{}", _dnf(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_float64(o: &PairFloat64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dn(o.a)));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_pair_bytes(o: &PairBytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", format!("\"{}\"", _db(&o.a))));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_string_int32(o: &DualStringInt32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_string_boolean(o: &DualStringBoolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", if o.b { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_string_float64(o: &DualStringFloat64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_string_bytes(o: &DualStringBytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int32_boolean(o: &DualInt32Boolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", if o.b { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int32_float64(o: &DualInt32Float64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int32_int64(o: &DualInt32Int64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _di(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int32_uint32(o: &DualInt32Uint32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int64_uint64(o: &DualInt64Uint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _di(o.a)));
    parts.push(format!("\"b\":{}", _du(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_float32_float64(o: &DualFloat32Float64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dnf(o.a)));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_float64_boolean(o: &DualFloat64Boolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dn(o.a)));
    parts.push(format!("\"b\":{}", if o.b { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_float64_bytes(o: &DualFloat64Bytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dn(o.a)));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_uint32_uint64(o: &DualUint32Uint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _du(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_boolean_bytes(o: &DualBooleanBytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", if o.a { "true" } else { "false" }));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int8_uint8(o: &DualInt8Uint8) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int16_uint16(o: &DualInt16Uint16) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_string_int64(o: &DualStringInt64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", _di(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_string_uint64(o: &DualStringUint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", _du(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int32_bytes(o: &DualInt32Bytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_float64_int32(o: &DualFloat64Int32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dn(o.a)));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_boolean_int32(o: &DualBooleanInt32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", if o.a { "true" } else { "false" }));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_bytes_int64(o: &DualBytesInt64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", format!("\"{}\"", _db(&o.a))));
    parts.push(format!("\"b\":{}", _di(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int8_float32(o: &DualInt8Float32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _dnf(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_uint8_int16(o: &DualUint8Int16) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_int64_float64(o: &DualInt64Float64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _di(o.a)));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_dual_uint64_string(o: &DualUint64String) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _du(o.a)));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple01(o: &Triple01) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", o.b.toString()));
    parts.push(format!("\"c\":{}", if o.c { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple02(o: &Triple02) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dn(o.a)));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    parts.push(format!("\"c\":{}", _dn(o.c)));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple03(o: &Triple03) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    parts.push(format!("\"c\":{}", o.c.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple04(o: &Triple04) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    parts.push(format!("\"c\":{}", o.c.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple05(o: &Triple05) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _di(o.a)));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    parts.push(format!("\"c\":{}", if o.c { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple06(o: &Triple06) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _du(o.b)));
    parts.push(format!("\"c\":{}", _ds(&o.c)));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple07(o: &Triple07) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", format!("\"{}\"", _db(&o.a))));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    parts.push(format!("\"c\":{}", o.c.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple08(o: &Triple08) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dnf(o.a)));
    parts.push(format!("\"b\":{}", o.b.toString()));
    parts.push(format!("\"c\":{}", if o.c { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple09(o: &Triple09) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", _di(o.b)));
    parts.push(format!("\"c\":{}", _dn(o.c)));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple10(o: &Triple10) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", if o.a { "true" } else { "false" }));
    parts.push(format!("\"b\":{}", if o.b { "true" } else { "false" }));
    parts.push(format!("\"c\":{}", if o.c { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple11(o: &Triple11) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    parts.push(format!("\"c\":{}", o.c.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple12(o: &Triple12) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", o.b.toString()));
    parts.push(format!("\"c\":{}", o.c.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple13(o: &Triple13) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    parts.push(format!("\"c\":{}", _dn(o.c)));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple14(o: &Triple14) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _di(o.a)));
    parts.push(format!("\"b\":{}", _du(o.b)));
    parts.push(format!("\"c\":{}", if o.c { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_triple15(o: &Triple15) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _dn(o.a)));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    parts.push(format!("\"c\":{}", format!("\"{}\"", _db(&o.c))));
    format!("{{{}}}", parts.join(","))
}
fn dump_five01(o: &Five01) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _ds(&o.f1)));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", if o.f3 { "true" } else { "false" }));
    parts.push(format!("\"f4\":{}", _dn(o.f4)));
    parts.push(format!("\"f5\":{}", format!("\"{}\"", _db(&o.f5))));
    format!("{{{}}}", parts.join(","))
}
fn dump_five02(o: &Five02) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_five03(o: &Five03) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _ds(&o.f1)));
    parts.push(format!("\"f2\":{}", _ds(&o.f2)));
    parts.push(format!("\"f3\":{}", _ds(&o.f3)));
    parts.push(format!("\"f4\":{}", _ds(&o.f4)));
    parts.push(format!("\"f5\":{}", _ds(&o.f5)));
    format!("{{{}}}", parts.join(","))
}
fn dump_five04(o: &Five04) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _dn(o.f1)));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", _ds(&o.f3)));
    parts.push(format!("\"f4\":{}", if o.f4 { "true" } else { "false" }));
    parts.push(format!("\"f5\":{}", format!("\"{}\"", _db(&o.f5))));
    format!("{{{}}}", parts.join(","))
}
fn dump_five05(o: &Five05) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _di(o.f1)));
    parts.push(format!("\"f2\":{}", _du(o.f2)));
    parts.push(format!("\"f3\":{}", _ds(&o.f3)));
    parts.push(format!("\"f4\":{}", _dnf(o.f4)));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_five06(o: &Five06) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", if o.f1 { "true" } else { "false" }));
    parts.push(format!("\"f2\":{}", _ds(&o.f2)));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", _dn(o.f4)));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_five07(o: &Five07) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", format!("\"{}\"", _db(&o.f1))));
    parts.push(format!("\"f2\":{}", format!("\"{}\"", _db(&o.f2))));
    parts.push(format!("\"f3\":{}", _ds(&o.f3)));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", _dn(o.f5)));
    format!("{{{}}}", parts.join(","))
}
fn dump_five08(o: &Five08) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_five09(o: &Five09) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _dnf(o.f1)));
    parts.push(format!("\"f2\":{}", _dn(o.f2)));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", _di(o.f4)));
    parts.push(format!("\"f5\":{}", _ds(&o.f5)));
    format!("{{{}}}", parts.join(","))
}
fn dump_five10(o: &Five10) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _ds(&o.f1)));
    parts.push(format!("\"f2\":{}", if o.f2 { "true" } else { "false" }));
    parts.push(format!("\"f3\":{}", _di(o.f3)));
    parts.push(format!("\"f4\":{}", _du(o.f4)));
    parts.push(format!("\"f5\":{}", _dn(o.f5)));
    format!("{{{}}}", parts.join(","))
}
fn dump_ten01(o: &Ten01) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _ds(&o.f1)));
    parts.push(format!("\"f2\":{}", if o.f2 { "true" } else { "false" }));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    parts.push(format!("\"f6\":{}", _di(o.f6)));
    parts.push(format!("\"f7\":{}", o.f7.toString()));
    parts.push(format!("\"f8\":{}", o.f8.toString()));
    parts.push(format!("\"f9\":{}", o.f9.toString()));
    parts.push(format!("\"f10\":{}", _du(o.f10)));
    format!("{{{}}}", parts.join(","))
}
fn dump_ten02(o: &Ten02) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", _di(o.f3)));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    parts.push(format!("\"f6\":{}", o.f6.toString()));
    parts.push(format!("\"f7\":{}", _du(o.f7)));
    parts.push(format!("\"f8\":{}", _dnf(o.f8)));
    parts.push(format!("\"f9\":{}", _dn(o.f9)));
    parts.push(format!("\"f10\":{}", format!("\"{}\"", _db(&o.f10))));
    format!("{{{}}}", parts.join(","))
}
fn dump_ten03(o: &Ten03) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", _du(o.f4)));
    parts.push(format!("\"f5\":{}", _dnf(o.f5)));
    parts.push(format!("\"f6\":{}", _dn(o.f6)));
    parts.push(format!("\"f7\":{}", format!("\"{}\"", _db(&o.f7))));
    parts.push(format!("\"f8\":{}", _ds(&o.f8)));
    parts.push(format!("\"f9\":{}", if o.f9 { "true" } else { "false" }));
    parts.push(format!("\"f10\":{}", o.f10.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_ten04(o: &Ten04) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _du(o.f1)));
    parts.push(format!("\"f2\":{}", _dnf(o.f2)));
    parts.push(format!("\"f3\":{}", _dn(o.f3)));
    parts.push(format!("\"f4\":{}", format!("\"{}\"", _db(&o.f4))));
    parts.push(format!("\"f5\":{}", _ds(&o.f5)));
    parts.push(format!("\"f6\":{}", if o.f6 { "true" } else { "false" }));
    parts.push(format!("\"f7\":{}", o.f7.toString()));
    parts.push(format!("\"f8\":{}", o.f8.toString()));
    parts.push(format!("\"f9\":{}", o.f9.toString()));
    parts.push(format!("\"f10\":{}", _di(o.f10)));
    format!("{{{}}}", parts.join(","))
}
fn dump_ten05(o: &Ten05) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", format!("\"{}\"", _db(&o.f1))));
    parts.push(format!("\"f2\":{}", _ds(&o.f2)));
    parts.push(format!("\"f3\":{}", if o.f3 { "true" } else { "false" }));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    parts.push(format!("\"f6\":{}", o.f6.toString()));
    parts.push(format!("\"f7\":{}", _di(o.f7)));
    parts.push(format!("\"f8\":{}", o.f8.toString()));
    parts.push(format!("\"f9\":{}", o.f9.toString()));
    parts.push(format!("\"f10\":{}", o.f10.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_string(o: &ArrString) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_int32(o: &ArrInt32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_boolean(o: &ArrBoolean) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| if *e { "true" } else { "false" }).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_float64(o: &ArrFloat64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| _dn(*e as f64)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_bytes(o: &ArrBytes) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| format!("\"{}\"", _db(e))).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_int64(o: &ArrInt64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| _di(*e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_arr_uint64(o: &ArrUint64) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| _du(*e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_multi_arr1(o: &MultiArr1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"names\":{}", format!("[{}]", o.names.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"scores\":{}", format!("[{}]", o.scores.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_multi_arr2(o: &MultiArr2) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"flags\":{}", format!("[{}]", o.flags.iter().map(|e| if *e { "true" } else { "false" }).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"values\":{}", format!("[{}]", o.values.iter().map(|e| _dn(*e as f64)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"payload\":{}", format!("[{}]", o.payload.iter().map(|e| format!("\"{}\"", _db(e))).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_multi_arr3(o: &MultiArr3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", format!("[{}]", o.a.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"b\":{}", format!("[{}]", o.b.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"c\":{}", format!("[{}]", o.c.iter().map(|e| _dn(*e as f64)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_multi_arr4(o: &MultiArr4) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"ids\":{}", format!("[{}]", o.ids.iter().map(|e| _di(*e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"tags\":{}", format!("[{}]", o.tags.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_multi_arr5(o: &MultiArr5) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"xs\":{}", format!("[{}]", o.xs.iter().map(|e| _du(*e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"ys\":{}", format!("[{}]", o.ys.iter().map(|e| _dn(*e as f64)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"zs\":{}", format!("[{}]", o.zs.iter().map(|e| if *e { "true" } else { "false" }).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo1(o: &OptCombo1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", _ds(&o.req)));
    if let Some(v) = &o.opt_a { parts.push(format!("\"opt_a\":{}", (*v).to_string())); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo2(o: &OptCombo2) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", _ds(&o.req)));
    if let Some(v) = &o.opt_a { parts.push(format!("\"opt_a\":{}", (*v).to_string())); }
    if let Some(v) = &o.opt_b { parts.push(format!("\"opt_b\":{}", if *v { "true" } else { "false" })); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo3(o: &OptCombo3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", _ds(&o.req)));
    if let Some(v) = &o.opt_a { parts.push(format!("\"opt_a\":{}", (*v).to_string())); }
    if let Some(v) = &o.opt_b { parts.push(format!("\"opt_b\":{}", if *v { "true" } else { "false" })); }
    if let Some(v) = &o.opt_c { parts.push(format!("\"opt_c\":{}", _dn(*v as f64))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo4(o: &OptCombo4) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", o.req.toString()));
    if let Some(v) = &o.opt_a { parts.push(format!("\"opt_a\":{}", _ds(v))); }
    if let Some(v) = &o.opt_b { parts.push(format!("\"opt_b\":{}", format!("\"{}\"", _db(v)))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo5(o: &OptCombo5) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req1\":{}", _ds(&o.req1)));
    parts.push(format!("\"req2\":{}", o.req2.toString()));
    if let Some(v) = &o.opt_a { parts.push(format!("\"opt_a\":{}", if *v { "true" } else { "false" })); }
    if let Some(v) = &o.opt_b { parts.push(format!("\"opt_b\":{}", _dn(*v as f64))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo6(o: &OptCombo6) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", _ds(&o.req)));
    if let Some(v) = &o.opt_s { parts.push(format!("\"opt_s\":{}", _ds(v))); }
    if let Some(v) = &o.opt_i { parts.push(format!("\"opt_i\":{}", (*v).to_string())); }
    if let Some(v) = &o.opt_f { parts.push(format!("\"opt_f\":{}", _dn(*v as f64))); }
    if let Some(v) = &o.opt_b { parts.push(format!("\"opt_b\":{}", format!("\"{}\"", _db(v)))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo7(o: &OptCombo7) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", _di(o.req)));
    if let Some(v) = &o.opt_u64 { parts.push(format!("\"opt_u64\":{}", _du(*v))); }
    if let Some(v) = &o.opt_str { parts.push(format!("\"opt_str\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo8(o: &OptCombo8) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", _ds(&o.a)));
    if let Some(v) = &o.b { parts.push(format!("\"b\":{}", (*v).to_string())); }
    if let Some(v) = &o.c { parts.push(format!("\"c\":{}", _dn(*v as f64))); }
    if let Some(v) = &o.d { parts.push(format!("\"d\":{}", if *v { "true" } else { "false" })); }
    if let Some(v) = &o.e { parts.push(format!("\"e\":{}", format!("\"{}\"", _db(v)))); }
    if let Some(v) = &o.f { parts.push(format!("\"f\":{}", _di(*v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo9(o: &OptCombo9) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"id\":{}", _ds(&o.id)));
    if let Some(v) = &o.name { parts.push(format!("\"name\":{}", _ds(v))); }
    if let Some(v) = &o.age { parts.push(format!("\"age\":{}", (*v).to_string())); }
    if let Some(v) = &o.score { parts.push(format!("\"score\":{}", _dn(*v as f64))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_combo10(o: &OptCombo10) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"code\":{}", o.code.toString()));
    if let Some(v) = &o.msg { parts.push(format!("\"msg\":{}", _ds(v))); }
    if let Some(v) = &o.detail { parts.push(format!("\"detail\":{}", _ds(v))); }
    if let Some(v) = &o.retry { parts.push(format!("\"retry\":{}", if *v { "true" } else { "false" })); }
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_inner(o: &NestInner) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_inner(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_coord(o: &NestCoord) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_coord(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_id_val(o: &NestIdVal) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_id_val(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_label(o: &NestLabel) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_label(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_money(o: &NestMoney) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_money(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_range32(o: &NestRange32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_range32(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_addr(o: &NestAddr) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_addr(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_point3(o: &NestPoint3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"nested\":{}", dump_point3(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_inner(o: &OptNestInner) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_inner(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_coord(o: &OptNestCoord) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_coord(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_id_val(o: &OptNestIdVal) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_id_val(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_label(o: &OptNestLabel) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_label(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_money(o: &OptNestMoney) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_money(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_range32(o: &OptNestRange32) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_range32(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_addr(o: &OptNestAddr) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_addr(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_nest_point3(o: &OptNestPoint3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_point3(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_model_arr1(o: &ModelArr1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"points\":{}", format!("[{}]", o.points.iter().map(|e| dump_inner(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_model_arr2(o: &ModelArr2) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"coords\":{}", format!("[{}]", o.coords.iter().map(|e| dump_coord(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_model_arr3(o: &ModelArr3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| dump_id_val(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"tag\":{}", _ds(&o.tag)));
    format!("{{{}}}", parts.join(","))
}
fn dump_model_arr4(o: &ModelArr4) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"labels\":{}", format!("[{}]", o.labels.iter().map(|e| dump_label(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"count\":{}", o.count.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_model_arr5(o: &ModelArr5) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"arr\":{}", format!("[{}]", o.arr.iter().map(|e| dump_money(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"bs\":{}", format!("[{}]", o.bs.iter().map(|e| dump_addr(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix01(o: &Mix01) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    parts.push(format!("\"value\":{}", o.value.toString()));
    parts.push(format!("\"point\":{}", dump_inner(&o.point)));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix02(o: &Mix02) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"id\":{}", _ds(&o.id)));
    parts.push(format!("\"loc\":{}", dump_coord(&o.loc)));
    parts.push(format!("\"tags\":{}", format!("[{}]", o.tags.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix03(o: &Mix03) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    parts.push(format!("\"value_range\":{}", dump_range32(&o.value_range)));
    parts.push(format!("\"active\":{}", if o.active { "true" } else { "false" }));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix04(o: &Mix04) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"title\":{}", _ds(&o.title)));
    parts.push(format!("\"price\":{}", dump_money(&o.price)));
    parts.push(format!("\"inStock\":{}", if o.inStock { "true" } else { "false" }));
    parts.push(format!("\"rating\":{}", _dn(o.rating)));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix05(o: &Mix05) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"addr\":{}", dump_addr(&o.addr)));
    parts.push(format!("\"coords\":{}", format!("[{}]", o.coords.iter().map(|e| dump_coord(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix06(o: &Mix06) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    parts.push(format!("\"age\":{}", o.age.toString()));
    if let Some(v) = &o.address { parts.push(format!("\"address\":{}", dump_addr(v))); }
    if let Some(v) = &o.email { parts.push(format!("\"email\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_mix07(o: &Mix07) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"origin\":{}", dump_point3(&o.origin)));
    parts.push(format!("\"dest\":{}", dump_point3(&o.dest)));
    parts.push(format!("\"distance\":{}", _dn(o.distance)));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix08(o: &Mix08) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"keys\":{}", format!("[{}]", o.keys.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"values\":{}", format!("[{}]", o.values.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(","))));
    if let Some(v) = &o.meta { parts.push(format!("\"meta\":{}", dump_label(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_mix09(o: &Mix09) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"id\":{}", _di(o.id)));
    parts.push(format!("\"payload\":{}", format!("\"{}\"", _db(&o.payload))));
    parts.push(format!("\"checksum\":{}", o.checksum.toString()));
    if let Some(v) = &o.prev { parts.push(format!("\"prev\":{}", dump_id_val(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_mix10(o: &Mix10) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"total\":{}", o.total.toString()));
    parts.push(format!("\"avg\":{}", _dn(o.avg)));
    parts.push(format!("\"value_range\":{}", dump_range32(&o.value_range)));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix11(o: &Mix11) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    parts.push(format!("\"values\":{}", format!("[{}]", o.values.iter().map(|e| _dn(*e as f64)).collect::<Vec<_>>().join(","))));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_inner(v))); }
    if let Some(v) = &o.flag { parts.push(format!("\"flag\":{}", if *v { "true" } else { "false" })); }
    format!("{{{}}}", parts.join(","))
}
fn dump_mix12(o: &Mix12) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"header\":{}", _ds(&o.header)));
    parts.push(format!("\"entries\":{}", format!("[{}]", o.entries.iter().map(|e| dump_id_val(e)).collect::<Vec<_>>().join(","))));
    if let Some(v) = &o.footer { parts.push(format!("\"footer\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_mix13(o: &Mix13) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _dn(o.b)));
    parts.push(format!("\"c\":{}", _ds(&o.c)));
    parts.push(format!("\"d\":{}", if o.d { "true" } else { "false" }));
    parts.push(format!("\"e\":{}", format!("\"{}\"", _db(&o.e))));
    parts.push(format!("\"nested\":{}", dump_inner(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix14(o: &Mix14) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"amounts\":{}", format!("[{}]", o.amounts.iter().map(|e| dump_money(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"total\":{}", _di(o.total)));
    parts.push(format!("\"currency\":{}", _ds(&o.currency)));
    format!("{{{}}}", parts.join(","))
}
fn dump_mix15(o: &Mix15) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"src_addr\":{}", dump_addr(&o.src_addr)));
    parts.push(format!("\"dst_addr\":{}", dump_addr(&o.dst_addr)));
    parts.push(format!("\"distance\":{}", _dn(o.distance)));
    parts.push(format!("\"duration\":{}", _dn(o.duration)));
    format!("{{{}}}", parts.join(","))
}
fn dump_all_opt1(o: &AllOpt1) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.a { parts.push(format!("\"a\":{}", _ds(v))); }
    if let Some(v) = &o.b { parts.push(format!("\"b\":{}", (*v).to_string())); }
    if let Some(v) = &o.c { parts.push(format!("\"c\":{}", if *v { "true" } else { "false" })); }
    format!("{{{}}}", parts.join(","))
}
fn dump_all_opt2(o: &AllOpt2) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.x { parts.push(format!("\"x\":{}", _dn(*v as f64))); }
    if let Some(v) = &o.y { parts.push(format!("\"y\":{}", format!("\"{}\"", _db(v)))); }
    if let Some(v) = &o.z { parts.push(format!("\"z\":{}", _di(*v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_all_opt3(o: &AllOpt3) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.name { parts.push(format!("\"name\":{}", _ds(v))); }
    if let Some(v) = &o.age { parts.push(format!("\"age\":{}", (*v).to_string())); }
    if let Some(v) = &o.score { parts.push(format!("\"score\":{}", _dn(*v as f64))); }
    if let Some(v) = &o.active { parts.push(format!("\"active\":{}", if *v { "true" } else { "false" })); }
    format!("{{{}}}", parts.join(","))
}
fn dump_all_opt4(o: &AllOpt4) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.a { parts.push(format!("\"a\":{}", (*v).to_string())); }
    if let Some(v) = &o.b { parts.push(format!("\"b\":{}", _du(*v))); }
    if let Some(v) = &o.c { parts.push(format!("\"c\":{}", (*v).to_string())); }
    if let Some(v) = &o.d { parts.push(format!("\"d\":{}", _ds(v))); }
    if let Some(v) = &o.e { parts.push(format!("\"e\":{}", format!("\"{}\"", _db(v)))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_all_opt5(o: &AllOpt5) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.p { parts.push(format!("\"p\":{}", dump_inner(v))); }
    if let Some(v) = &o.q { parts.push(format!("\"q\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_rec_list(o: &RecList) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"value\":{}", o.value.toString()));
    if let Some(v) = &o.next { parts.push(format!("\"next\":{}", dump_rec_list(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_rec_tree(o: &RecTree) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"value\":{}", _ds(&o.value)));
    if let Some(v) = &o.left_node { parts.push(format!("\"left_node\":{}", dump_rec_tree(v))); }
    if let Some(v) = &o.right_node { parts.push(format!("\"right_node\":{}", dump_rec_tree(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_rec_chain(o: &RecChain) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"id\":{}", o.id.toString()));
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    if let Some(v) = &o.next { parts.push(format!("\"next\":{}", dump_rec_chain(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_rec_wrap(o: &RecWrap) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"payload\":{}", format!("\"{}\"", _db(&o.payload))));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_rec_wrap(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_rec_wide(o: &RecWide) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", o.a.toString()));
    parts.push(format!("\"b\":{}", _ds(&o.b)));
    parts.push(format!("\"c\":{}", _dn(o.c)));
    if let Some(v) = &o.child { parts.push(format!("\"child\":{}", dump_rec_wide(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_wide20(o: &Wide20) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", _ds(&o.f1)));
    parts.push(format!("\"f2\":{}", if o.f2 { "true" } else { "false" }));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    parts.push(format!("\"f6\":{}", _di(o.f6)));
    parts.push(format!("\"f7\":{}", o.f7.toString()));
    parts.push(format!("\"f8\":{}", o.f8.toString()));
    parts.push(format!("\"f9\":{}", o.f9.toString()));
    parts.push(format!("\"f10\":{}", _du(o.f10)));
    parts.push(format!("\"f11\":{}", _dnf(o.f11)));
    parts.push(format!("\"f12\":{}", _dn(o.f12)));
    parts.push(format!("\"f13\":{}", format!("\"{}\"", _db(&o.f13))));
    parts.push(format!("\"f14\":{}", _ds(&o.f14)));
    parts.push(format!("\"f15\":{}", if o.f15 { "true" } else { "false" }));
    parts.push(format!("\"f16\":{}", o.f16.toString()));
    parts.push(format!("\"f17\":{}", o.f17.toString()));
    parts.push(format!("\"f18\":{}", o.f18.toString()));
    parts.push(format!("\"f19\":{}", _di(o.f19)));
    parts.push(format!("\"f20\":{}", o.f20.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_wide25(o: &Wide25) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", _du(o.f3)));
    parts.push(format!("\"f4\":{}", _dnf(o.f4)));
    parts.push(format!("\"f5\":{}", _dn(o.f5)));
    parts.push(format!("\"f6\":{}", format!("\"{}\"", _db(&o.f6))));
    parts.push(format!("\"f7\":{}", _ds(&o.f7)));
    parts.push(format!("\"f8\":{}", if o.f8 { "true" } else { "false" }));
    parts.push(format!("\"f9\":{}", o.f9.toString()));
    parts.push(format!("\"f10\":{}", o.f10.toString()));
    parts.push(format!("\"f11\":{}", o.f11.toString()));
    parts.push(format!("\"f12\":{}", _di(o.f12)));
    parts.push(format!("\"f13\":{}", o.f13.toString()));
    parts.push(format!("\"f14\":{}", o.f14.toString()));
    parts.push(format!("\"f15\":{}", o.f15.toString()));
    parts.push(format!("\"f16\":{}", _du(o.f16)));
    parts.push(format!("\"f17\":{}", _dnf(o.f17)));
    parts.push(format!("\"f18\":{}", _dn(o.f18)));
    parts.push(format!("\"f19\":{}", format!("\"{}\"", _db(&o.f19))));
    parts.push(format!("\"f20\":{}", _ds(&o.f20)));
    parts.push(format!("\"f21\":{}", if o.f21 { "true" } else { "false" }));
    parts.push(format!("\"f22\":{}", o.f22.toString()));
    parts.push(format!("\"f23\":{}", o.f23.toString()));
    parts.push(format!("\"f24\":{}", o.f24.toString()));
    parts.push(format!("\"f25\":{}", _di(o.f25)));
    format!("{{{}}}", parts.join(","))
}
fn dump_wide30(o: &Wide30) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", if o.f1 { "true" } else { "false" }));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", o.f4.toString()));
    parts.push(format!("\"f5\":{}", _di(o.f5)));
    parts.push(format!("\"f6\":{}", o.f6.toString()));
    parts.push(format!("\"f7\":{}", o.f7.toString()));
    parts.push(format!("\"f8\":{}", o.f8.toString()));
    parts.push(format!("\"f9\":{}", _du(o.f9)));
    parts.push(format!("\"f10\":{}", _dnf(o.f10)));
    parts.push(format!("\"f11\":{}", _dn(o.f11)));
    parts.push(format!("\"f12\":{}", format!("\"{}\"", _db(&o.f12))));
    parts.push(format!("\"f13\":{}", _ds(&o.f13)));
    parts.push(format!("\"f14\":{}", if o.f14 { "true" } else { "false" }));
    parts.push(format!("\"f15\":{}", o.f15.toString()));
    parts.push(format!("\"f16\":{}", o.f16.toString()));
    parts.push(format!("\"f17\":{}", o.f17.toString()));
    parts.push(format!("\"f18\":{}", _di(o.f18)));
    parts.push(format!("\"f19\":{}", o.f19.toString()));
    parts.push(format!("\"f20\":{}", o.f20.toString()));
    parts.push(format!("\"f21\":{}", o.f21.toString()));
    parts.push(format!("\"f22\":{}", _du(o.f22)));
    parts.push(format!("\"f23\":{}", _dnf(o.f23)));
    parts.push(format!("\"f24\":{}", _dn(o.f24)));
    parts.push(format!("\"f25\":{}", format!("\"{}\"", _db(&o.f25))));
    parts.push(format!("\"f26\":{}", _ds(&o.f26)));
    parts.push(format!("\"f27\":{}", if o.f27 { "true" } else { "false" }));
    parts.push(format!("\"f28\":{}", o.f28.toString()));
    parts.push(format!("\"f29\":{}", o.f29.toString()));
    parts.push(format!("\"f30\":{}", o.f30.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_wide35(o: &Wide35) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", _du(o.f2)));
    parts.push(format!("\"f3\":{}", _dnf(o.f3)));
    parts.push(format!("\"f4\":{}", _dn(o.f4)));
    parts.push(format!("\"f5\":{}", format!("\"{}\"", _db(&o.f5))));
    parts.push(format!("\"f6\":{}", _ds(&o.f6)));
    parts.push(format!("\"f7\":{}", if o.f7 { "true" } else { "false" }));
    parts.push(format!("\"f8\":{}", o.f8.toString()));
    parts.push(format!("\"f9\":{}", o.f9.toString()));
    parts.push(format!("\"f10\":{}", o.f10.toString()));
    parts.push(format!("\"f11\":{}", _di(o.f11)));
    parts.push(format!("\"f12\":{}", o.f12.toString()));
    parts.push(format!("\"f13\":{}", o.f13.toString()));
    parts.push(format!("\"f14\":{}", o.f14.toString()));
    parts.push(format!("\"f15\":{}", _du(o.f15)));
    parts.push(format!("\"f16\":{}", _dnf(o.f16)));
    parts.push(format!("\"f17\":{}", _dn(o.f17)));
    parts.push(format!("\"f18\":{}", format!("\"{}\"", _db(&o.f18))));
    parts.push(format!("\"f19\":{}", _ds(&o.f19)));
    parts.push(format!("\"f20\":{}", if o.f20 { "true" } else { "false" }));
    parts.push(format!("\"f21\":{}", o.f21.toString()));
    parts.push(format!("\"f22\":{}", o.f22.toString()));
    parts.push(format!("\"f23\":{}", o.f23.toString()));
    parts.push(format!("\"f24\":{}", _di(o.f24)));
    parts.push(format!("\"f25\":{}", o.f25.toString()));
    parts.push(format!("\"f26\":{}", o.f26.toString()));
    parts.push(format!("\"f27\":{}", o.f27.toString()));
    parts.push(format!("\"f28\":{}", _du(o.f28)));
    parts.push(format!("\"f29\":{}", _dnf(o.f29)));
    parts.push(format!("\"f30\":{}", _dn(o.f30)));
    parts.push(format!("\"f31\":{}", format!("\"{}\"", _db(&o.f31))));
    parts.push(format!("\"f32\":{}", _ds(&o.f32)));
    parts.push(format!("\"f33\":{}", if o.f33 { "true" } else { "false" }));
    parts.push(format!("\"f34\":{}", o.f34.toString()));
    parts.push(format!("\"f35\":{}", o.f35.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_wide40(o: &Wide40) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"f1\":{}", o.f1.toString()));
    parts.push(format!("\"f2\":{}", o.f2.toString()));
    parts.push(format!("\"f3\":{}", o.f3.toString()));
    parts.push(format!("\"f4\":{}", _di(o.f4)));
    parts.push(format!("\"f5\":{}", o.f5.toString()));
    parts.push(format!("\"f6\":{}", o.f6.toString()));
    parts.push(format!("\"f7\":{}", o.f7.toString()));
    parts.push(format!("\"f8\":{}", _du(o.f8)));
    parts.push(format!("\"f9\":{}", _dnf(o.f9)));
    parts.push(format!("\"f10\":{}", _dn(o.f10)));
    parts.push(format!("\"f11\":{}", format!("\"{}\"", _db(&o.f11))));
    parts.push(format!("\"f12\":{}", _ds(&o.f12)));
    parts.push(format!("\"f13\":{}", if o.f13 { "true" } else { "false" }));
    parts.push(format!("\"f14\":{}", o.f14.toString()));
    parts.push(format!("\"f15\":{}", o.f15.toString()));
    parts.push(format!("\"f16\":{}", o.f16.toString()));
    parts.push(format!("\"f17\":{}", _di(o.f17)));
    parts.push(format!("\"f18\":{}", o.f18.toString()));
    parts.push(format!("\"f19\":{}", o.f19.toString()));
    parts.push(format!("\"f20\":{}", o.f20.toString()));
    parts.push(format!("\"f21\":{}", _du(o.f21)));
    parts.push(format!("\"f22\":{}", _dnf(o.f22)));
    parts.push(format!("\"f23\":{}", _dn(o.f23)));
    parts.push(format!("\"f24\":{}", format!("\"{}\"", _db(&o.f24))));
    parts.push(format!("\"f25\":{}", _ds(&o.f25)));
    parts.push(format!("\"f26\":{}", if o.f26 { "true" } else { "false" }));
    parts.push(format!("\"f27\":{}", o.f27.toString()));
    parts.push(format!("\"f28\":{}", o.f28.toString()));
    parts.push(format!("\"f29\":{}", o.f29.toString()));
    parts.push(format!("\"f30\":{}", _di(o.f30)));
    parts.push(format!("\"f31\":{}", o.f31.toString()));
    parts.push(format!("\"f32\":{}", o.f32.toString()));
    parts.push(format!("\"f33\":{}", o.f33.toString()));
    parts.push(format!("\"f34\":{}", _du(o.f34)));
    parts.push(format!("\"f35\":{}", _dnf(o.f35)));
    parts.push(format!("\"f36\":{}", _dn(o.f36)));
    parts.push(format!("\"f37\":{}", format!("\"{}\"", _db(&o.f37))));
    parts.push(format!("\"f38\":{}", _ds(&o.f38)));
    parts.push(format!("\"f39\":{}", if o.f39 { "true" } else { "false" }));
    parts.push(format!("\"f40\":{}", o.f40.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_empty(o: &EdgeEmpty) -> String {
    let mut parts: Vec<String> = Vec::new();

    format!("{{{}}}", parts.join(","))
}
fn dump_edge_one_opt(o: &EdgeOneOpt) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.maybe { parts.push(format!("\"maybe\":{}", _ds(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_big_nums(o: &EdgeBigNums) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"i8\":{}", o.i8.toString()));
    parts.push(format!("\"i16\":{}", o.i16.toString()));
    parts.push(format!("\"i32\":{}", o.i32.toString()));
    parts.push(format!("\"i64\":{}", _di(o.i64)));
    parts.push(format!("\"u8\":{}", o.u8.toString()));
    parts.push(format!("\"u16\":{}", o.u16.toString()));
    parts.push(format!("\"u32\":{}", o.u32.toString()));
    parts.push(format!("\"u64\":{}", _du(o.u64)));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_zero_vals(o: &EdgeZeroVals) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"s\":{}", _ds(&o.s)));
    parts.push(format!("\"i\":{}", o.i.toString()));
    parts.push(format!("\"f\":{}", _dn(o.f)));
    parts.push(format!("\"b\":{}", if o.b { "true" } else { "false" }));
    parts.push(format!("\"by_field\":{}", format!("\"{}\"", _db(&o.by_field))));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_nullable(o: &EdgeNullable) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.a { parts.push(format!("\"a\":{}", _ds(v))); }
    if let Some(v) = &o.b { parts.push(format!("\"b\":{}", (*v).to_string())); }
    if let Some(v) = &o.c { parts.push(format!("\"c\":{}", dump_inner(v))); }
    if let Some(v) = &o.d { parts.push(format!("\"d\":{}", format!("[{}]", v.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(",")))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_neg_zero(o: &EdgeNegZero) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"v\":{}", _dn(o.v)));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_null_byte(o: &EdgeNullByte) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"s\":{}", _ds(&o.s)));
    parts.push(format!("\"b\":{}", format!("\"{}\"", _db(&o.b))));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_boundary(o: &EdgeBoundary) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"i32_neg129\":{}", o.i32_neg129.toString()));
    parts.push(format!("\"i32_128\":{}", o.i32_128.toString()));
    parts.push(format!("\"i32_256\":{}", o.i32_256.toString()));
    parts.push(format!("\"i32_65536\":{}", o.i32_65536.toString()));
    parts.push(format!("\"i32_neg32769\":{}", o.i32_neg32769.toString()));
    parts.push(format!("\"u32_65536\":{}", o.u32_65536.toString()));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_str_len(o: &EdgeStrLen) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"s31\":{}", _ds(&o.s31)));
    parts.push(format!("\"s32\":{}", _ds(&o.s32)));
    parts.push(format!("\"s255\":{}", _ds(&o.s255)));
    parts.push(format!("\"s256\":{}", _ds(&o.s256)));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_bytes_len(o: &EdgeBytesLen) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"b31\":{}", format!("\"{}\"", _db(&o.b31))));
    parts.push(format!("\"b32\":{}", format!("\"{}\"", _db(&o.b32))));
    parts.push(format!("\"b255\":{}", format!("\"{}\"", _db(&o.b255))));
    parts.push(format!("\"b256\":{}", format!("\"{}\"", _db(&o.b256))));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_arr_empty(o: &EdgeArrEmpty) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_edge_arr_boundary(o: &EdgeArrBoundary) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a15\":{}", format!("[{}]", o.a15.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"a16\":{}", format!("[{}]", o.a16.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(","))));
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_arr1(o: &OptArr1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"req\":{}", _ds(&o.req)));
    if let Some(v) = &o.items { parts.push(format!("\"items\":{}", format!("[{}]", v.iter().map(|e| e.to_string()).collect::<Vec<_>>().join(",")))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_arr2(o: &OptArr2) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"id\":{}", o.id.toString()));
    if let Some(v) = &o.names { parts.push(format!("\"names\":{}", format!("[{}]", v.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(",")))); }
    if let Some(v) = &o.flags { parts.push(format!("\"flags\":{}", format!("[{}]", v.iter().map(|e| if *e { "true" } else { "false" }).collect::<Vec<_>>().join(",")))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_arr3(o: &OptArr3) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.a { parts.push(format!("\"a\":{}", format!("[{}]", v.iter().map(|e| _ds(e)).collect::<Vec<_>>().join(",")))); }
    if let Some(v) = &o.b { parts.push(format!("\"b\":{}", format!("[{}]", v.iter().map(|e| _dn(*e as f64)).collect::<Vec<_>>().join(",")))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_arr4(o: &OptArr4) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"payload\":{}", format!("\"{}\"", _db(&o.payload))));
    if let Some(v) = &o.chunks { parts.push(format!("\"chunks\":{}", format!("[{}]", v.iter().map(|e| format!("\"{}\"", _db(e))).collect::<Vec<_>>().join(",")))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_opt_arr5(o: &OptArr5) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.models { parts.push(format!("\"models\":{}", format!("[{}]", v.iter().map(|e| dump_inner(e)).collect::<Vec<_>>().join(",")))); }
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt1(o: &NestOpt1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"outer\":{}", dump_label(&o.outer)));
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt2(o: &NestOpt2) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.a { parts.push(format!("\"a\":{}", dump_id_val(v))); }
    if let Some(v) = &o.b { parts.push(format!("\"b\":{}", dump_id_val(v))); }
    if let Some(v) = &o.c { parts.push(format!("\"c\":{}", dump_id_val(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt3(o: &NestOpt3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"money\":{}", dump_money(&o.money)));
    if let Some(v) = &o.value_range { parts.push(format!("\"value_range\":{}", dump_range32(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt4(o: &NestOpt4) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.addr { parts.push(format!("\"addr\":{}", dump_addr(v))); }
    if let Some(v) = &o.coord { parts.push(format!("\"coord\":{}", dump_coord(v))); }
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt5(o: &NestOpt5) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"point\":{}", dump_point3(&o.point)));
    parts.push(format!("\"addr\":{}", dump_addr(&o.addr)));
    if let Some(v) = &o.label { parts.push(format!("\"label\":{}", dump_label(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt_inner1(o: &NestOptInner1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"tag\":{}", _ds(&o.tag)));
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_opt_inner(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt_inner2(o: &NestOptInner2) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"tag\":{}", _ds(&o.tag)));
    parts.push(format!("\"nested\":{}", dump_opt_inner(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_nest_opt_inner3(o: &NestOptInner3) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(v) = &o.outer { parts.push(format!("\"outer\":{}", dump_opt_inner(v))); }
    if let Some(v) = &o.nested { parts.push(format!("\"nested\":{}", dump_opt_inner(v))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest1(o: &DeepNest1) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"label\":{}", _ds(&o.label)));
    parts.push(format!("\"nested\":{}", dump_addr(&o.nested)));
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest2(o: &DeepNest2) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    parts.push(format!("\"money\":{}", dump_money(&o.money)));
    parts.push(format!("\"addr\":{}", dump_addr(&o.addr)));
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest3(o: &DeepNest3) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"title\":{}", _ds(&o.title)));
    parts.push(format!("\"point\":{}", dump_point3(&o.point)));
    parts.push(format!("\"value_range\":{}", dump_range32(&o.value_range)));
    parts.push(format!("\"money\":{}", dump_money(&o.money)));
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest4(o: &DeepNest4) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"coords\":{}", format!("[{}]", o.coords.iter().map(|e| dump_coord(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"nested\":{}", dump_inner(&o.nested)));
    parts.push(format!("\"tag\":{}", _ds(&o.tag)));
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest5(o: &DeepNest5) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"labels\":{}", format!("[{}]", o.labels.iter().map(|e| dump_label(e)).collect::<Vec<_>>().join(","))));
    parts.push(format!("\"money\":{}", dump_money(&o.money)));
    parts.push(format!("\"name\":{}", _ds(&o.name)));
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest6(o: &DeepNest6) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"items\":{}", format!("[{}]", o.items.iter().map(|e| dump_id_val(e)).collect::<Vec<_>>().join(","))));
    if let Some(v) = &o.addr { parts.push(format!("\"addr\":{}", dump_addr(v))); }
    parts.push(format!("\"coord\":{}", dump_coord(&o.coord)));
    format!("{{{}}}", parts.join(","))
}
fn dump_deep_nest7(o: &DeepNest7) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"a\":{}", dump_addr(&o.a)));
    parts.push(format!("\"b\":{}", dump_addr(&o.b)));
    parts.push(format!("\"c\":{}", dump_addr(&o.c)));
    format!("{{{}}}", parts.join(","))
}
fn dump_timestamp_entry(o: &TimestampEntry) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"ts\":{}", _di(o.ts)));
    parts.push(format!("\"event\":{}", _ds(&o.event)));
    if let Some(v) = &o.payload { parts.push(format!("\"payload\":{}", format!("\"{}\"", _db(v)))); }
    format!("{{{}}}", parts.join(","))
}
fn dump_config_entry(o: &ConfigEntry) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"key\":{}", _ds(&o.key)));
    if let Some(v) = &o.intValue { parts.push(format!("\"intValue\":{}", (*v).to_string())); }
    if let Some(v) = &o.strValue { parts.push(format!("\"strValue\":{}", _ds(v))); }
    if let Some(v) = &o.boolValue { parts.push(format!("\"boolValue\":{}", if *v { "true" } else { "false" })); }
    if let Some(v) = &o.floatValue { parts.push(format!("\"floatValue\":{}", _dn(*v as f64))); }
    format!("{{{}}}", parts.join(","))
}