// Generated by gen_types.cjs. DO NOT EDIT.
package main

import (
    "encoding/base64"
    "fmt"
    "math"
    "strconv"
    "strings"
    . "test/emit_gen"
)

func _ds(v string) string {
    var b strings.Builder
    b.WriteByte(34)
    for i := 0; i < len(v); i++ {
        c := v[i]
        switch c {
        case 34: b.WriteByte(92); b.WriteByte(34)
        case 92: b.WriteByte(92); b.WriteByte(92)
        case 10: b.WriteByte(92); b.WriteByte(110)
        case 9: b.WriteByte(92); b.WriteByte(116)
        case 13: b.WriteByte(92); b.WriteByte(114)
        default:
            if c < 32 {
                b.WriteByte(92); b.WriteByte(117); b.WriteString(fmt.Sprintf("%04x", c))
            } else {
                b.WriteByte(c)
            }
        }
    }
    b.WriteByte(34)
    return b.String()
}

func _dn(v float64) string {
    if v == 0 && math.Signbit(v) { return "-0" }
    s := strconv.FormatFloat(v, 'f', -1, 64)
    if strings.HasSuffix(s, ".0") { return s[:len(s)-2] }
    return s
}

func _dbool(v bool) string { if v { return "true" } else { return "false" } }
func _di(v int64) string { return string(34) + strconv.FormatInt(v, 10) + string(34) }
func _du(v uint64) string { return string(34) + strconv.FormatUint(v, 10) + string(34) }
func _db(v []byte) string { return base64.StdEncoding.EncodeToString(v) }

func dumpInner(o Inner) string {
	parts := []string{}
	parts = append(parts, "\"x\":"+strconv.Itoa(int(o.X)))
	parts = append(parts, "\"y\":"+strconv.Itoa(int(o.Y)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpCoord(o Coord) string {
	parts := []string{}
	parts = append(parts, "\"lat\":"+_dn(float64(o.Lat)))
	parts = append(parts, "\"lng\":"+_dn(float64(o.Lng)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpIdVal(o IdVal) string {
	parts := []string{}
	parts = append(parts, "\"id\":"+_ds(o.Id))
	parts = append(parts, "\"value\":"+strconv.Itoa(int(o.Value)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpLabel(o Label) string {
	parts := []string{}
	parts = append(parts, "\"key\":"+_ds(o.Key))
	parts = append(parts, "\"text\":"+_ds(o.Text))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMoney(o Money) string {
	parts := []string{}
	parts = append(parts, "\"amount\":"+_di(o.Amount))
	parts = append(parts, "\"currency\":"+_ds(o.Currency))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpRange32(o Range32) string {
	parts := []string{}
	parts = append(parts, "\"min\":"+strconv.Itoa(int(o.Min)))
	parts = append(parts, "\"max\":"+strconv.Itoa(int(o.Max)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpAddr(o Addr) string {
	parts := []string{}
	parts = append(parts, "\"street\":"+_ds(o.Street))
	parts = append(parts, "\"city\":"+_ds(o.City))
	parts = append(parts, "\"zip\":"+_ds(o.Zip))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPoint3(o Point3) string {
	parts := []string{}
	parts = append(parts, "\"x\":"+_dn(float64(o.X)))
	parts = append(parts, "\"y\":"+_dn(float64(o.Y)))
	parts = append(parts, "\"z\":"+_dn(float64(o.Z)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptInner(o OptInner) string {
	parts := []string{}
	if o.Name != nil { parts = append(parts, "\"name\":"+_ds(*o.Name)) }
	if o.Score != nil { parts = append(parts, "\"score\":"+_dn(float64(*o.Score))) }
	if o.Tag != nil { parts = append(parts, "\"tag\":"+_ds(*o.Tag)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleString(o SingleString) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_ds(o.V))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleBoolean(o SingleBoolean) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_dbool(o.V))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleInt8(o SingleInt8) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+strconv.Itoa(int(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleInt16(o SingleInt16) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+strconv.Itoa(int(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleInt32(o SingleInt32) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+strconv.Itoa(int(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleInt64(o SingleInt64) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_di(o.V))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleUint8(o SingleUint8) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+strconv.Itoa(int(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleUint16(o SingleUint16) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+strconv.Itoa(int(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleUint32(o SingleUint32) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+strconv.Itoa(int(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleUint64(o SingleUint64) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_du(o.V))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleFloat32(o SingleFloat32) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_dn(float64(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleFloat64(o SingleFloat64) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_dn(float64(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpSingleBytes(o SingleBytes) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+string(byte(34)) + _db(o.V) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleString(o OptSingleString) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+_ds(*o.V)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleBoolean(o OptSingleBoolean) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+_dbool(*o.V)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleInt8(o OptSingleInt8) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+strconv.Itoa(int(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleInt16(o OptSingleInt16) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+strconv.Itoa(int(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleInt32(o OptSingleInt32) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+strconv.Itoa(int(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleInt64(o OptSingleInt64) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+_di(*o.V)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleUint8(o OptSingleUint8) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+strconv.Itoa(int(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleUint16(o OptSingleUint16) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+strconv.Itoa(int(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleUint32(o OptSingleUint32) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+strconv.Itoa(int(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleUint64(o OptSingleUint64) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+_du(*o.V)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleFloat32(o OptSingleFloat32) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+_dn(float64(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleFloat64(o OptSingleFloat64) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+_dn(float64(*o.V))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptSingleBytes(o OptSingleBytes) string {
	parts := []string{}
	if o.V != nil { parts = append(parts, "\"v\":"+string(byte(34)) + _db(o.V) + string(byte(34))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairString(o PairString) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_ds(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairBoolean(o PairBoolean) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dbool(o.A))
	parts = append(parts, "\"b\":"+_dbool(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairInt8(o PairInt8) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairInt16(o PairInt16) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairInt32(o PairInt32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairInt64(o PairInt64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_di(o.A))
	parts = append(parts, "\"b\":"+_di(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairUint8(o PairUint8) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairUint16(o PairUint16) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairUint32(o PairUint32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairUint64(o PairUint64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_du(o.A))
	parts = append(parts, "\"b\":"+_du(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairFloat32(o PairFloat32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairFloat64(o PairFloat64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpPairBytes(o PairBytes) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+string(byte(34)) + _db(o.A) + string(byte(34)))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualStringInt32(o DualStringInt32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualStringBoolean(o DualStringBoolean) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_dbool(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualStringFloat64(o DualStringFloat64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualStringBytes(o DualStringBytes) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt32Boolean(o DualInt32Boolean) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_dbool(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt32Float64(o DualInt32Float64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt32Int64(o DualInt32Int64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_di(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt32Uint32(o DualInt32Uint32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt64Uint64(o DualInt64Uint64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_di(o.A))
	parts = append(parts, "\"b\":"+_du(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualFloat32Float64(o DualFloat32Float64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualFloat64Boolean(o DualFloat64Boolean) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+_dbool(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualFloat64Bytes(o DualFloat64Bytes) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualUint32Uint64(o DualUint32Uint64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_du(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualBooleanBytes(o DualBooleanBytes) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dbool(o.A))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt8Uint8(o DualInt8Uint8) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt16Uint16(o DualInt16Uint16) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualStringInt64(o DualStringInt64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_di(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualStringUint64(o DualStringUint64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_du(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt32Bytes(o DualInt32Bytes) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualFloat64Int32(o DualFloat64Int32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualBooleanInt32(o DualBooleanInt32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dbool(o.A))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualBytesInt64(o DualBytesInt64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+string(byte(34)) + _db(o.A) + string(byte(34)))
	parts = append(parts, "\"b\":"+_di(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt8Float32(o DualInt8Float32) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualUint8Int16(o DualUint8Int16) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualInt64Float64(o DualInt64Float64) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_di(o.A))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDualUint64String(o DualUint64String) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_du(o.A))
	parts = append(parts, "\"b\":"+_ds(o.B))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple01(o Triple01) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	parts = append(parts, "\"c\":"+_dbool(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple02(o Triple02) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	parts = append(parts, "\"c\":"+_dn(float64(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple03(o Triple03) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	parts = append(parts, "\"c\":"+strconv.Itoa(int(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple04(o Triple04) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_ds(o.B))
	parts = append(parts, "\"c\":"+strconv.Itoa(int(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple05(o Triple05) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_di(o.A))
	parts = append(parts, "\"b\":"+_ds(o.B))
	parts = append(parts, "\"c\":"+_dbool(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple06(o Triple06) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_du(o.B))
	parts = append(parts, "\"c\":"+_ds(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple07(o Triple07) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+string(byte(34)) + _db(o.A) + string(byte(34)))
	parts = append(parts, "\"b\":"+_ds(o.B))
	parts = append(parts, "\"c\":"+strconv.Itoa(int(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple08(o Triple08) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	parts = append(parts, "\"c\":"+_dbool(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple09(o Triple09) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+_di(o.B))
	parts = append(parts, "\"c\":"+_dn(float64(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple10(o Triple10) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dbool(o.A))
	parts = append(parts, "\"b\":"+_dbool(o.B))
	parts = append(parts, "\"c\":"+_dbool(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple11(o Triple11) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	parts = append(parts, "\"c\":"+strconv.Itoa(int(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple12(o Triple12) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+strconv.Itoa(int(o.B)))
	parts = append(parts, "\"c\":"+strconv.Itoa(int(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple13(o Triple13) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	parts = append(parts, "\"c\":"+_dn(float64(o.C)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple14(o Triple14) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_di(o.A))
	parts = append(parts, "\"b\":"+_du(o.B))
	parts = append(parts, "\"c\":"+_dbool(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTriple15(o Triple15) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_dn(float64(o.A)))
	parts = append(parts, "\"b\":"+_ds(o.B))
	parts = append(parts, "\"c\":"+string(byte(34)) + _db(o.C) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive01(o Five01) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_ds(o.F1))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+_dbool(o.F3))
	parts = append(parts, "\"f4\":"+_dn(float64(o.F4)))
	parts = append(parts, "\"f5\":"+string(byte(34)) + _db(o.F5) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive02(o Five02) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive03(o Five03) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_ds(o.F1))
	parts = append(parts, "\"f2\":"+_ds(o.F2))
	parts = append(parts, "\"f3\":"+_ds(o.F3))
	parts = append(parts, "\"f4\":"+_ds(o.F4))
	parts = append(parts, "\"f5\":"+_ds(o.F5))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive04(o Five04) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_dn(float64(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+_ds(o.F3))
	parts = append(parts, "\"f4\":"+_dbool(o.F4))
	parts = append(parts, "\"f5\":"+string(byte(34)) + _db(o.F5) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive05(o Five05) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_di(o.F1))
	parts = append(parts, "\"f2\":"+_du(o.F2))
	parts = append(parts, "\"f3\":"+_ds(o.F3))
	parts = append(parts, "\"f4\":"+_dn(float64(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive06(o Five06) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_dbool(o.F1))
	parts = append(parts, "\"f2\":"+_ds(o.F2))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+_dn(float64(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive07(o Five07) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+string(byte(34)) + _db(o.F1) + string(byte(34)))
	parts = append(parts, "\"f2\":"+string(byte(34)) + _db(o.F2) + string(byte(34)))
	parts = append(parts, "\"f3\":"+_ds(o.F3))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+_dn(float64(o.F5)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive08(o Five08) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive09(o Five09) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_dn(float64(o.F1)))
	parts = append(parts, "\"f2\":"+_dn(float64(o.F2)))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+_di(o.F4))
	parts = append(parts, "\"f5\":"+_ds(o.F5))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpFive10(o Five10) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_ds(o.F1))
	parts = append(parts, "\"f2\":"+_dbool(o.F2))
	parts = append(parts, "\"f3\":"+_di(o.F3))
	parts = append(parts, "\"f4\":"+_du(o.F4))
	parts = append(parts, "\"f5\":"+_dn(float64(o.F5)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTen01(o Ten01) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_ds(o.F1))
	parts = append(parts, "\"f2\":"+_dbool(o.F2))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	parts = append(parts, "\"f6\":"+_di(o.F6))
	parts = append(parts, "\"f7\":"+strconv.Itoa(int(o.F7)))
	parts = append(parts, "\"f8\":"+strconv.Itoa(int(o.F8)))
	parts = append(parts, "\"f9\":"+strconv.Itoa(int(o.F9)))
	parts = append(parts, "\"f10\":"+_du(o.F10))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTen02(o Ten02) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+_di(o.F3))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	parts = append(parts, "\"f6\":"+strconv.Itoa(int(o.F6)))
	parts = append(parts, "\"f7\":"+_du(o.F7))
	parts = append(parts, "\"f8\":"+_dn(float64(o.F8)))
	parts = append(parts, "\"f9\":"+_dn(float64(o.F9)))
	parts = append(parts, "\"f10\":"+string(byte(34)) + _db(o.F10) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTen03(o Ten03) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+_du(o.F4))
	parts = append(parts, "\"f5\":"+_dn(float64(o.F5)))
	parts = append(parts, "\"f6\":"+_dn(float64(o.F6)))
	parts = append(parts, "\"f7\":"+string(byte(34)) + _db(o.F7) + string(byte(34)))
	parts = append(parts, "\"f8\":"+_ds(o.F8))
	parts = append(parts, "\"f9\":"+_dbool(o.F9))
	parts = append(parts, "\"f10\":"+strconv.Itoa(int(o.F10)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTen04(o Ten04) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_du(o.F1))
	parts = append(parts, "\"f2\":"+_dn(float64(o.F2)))
	parts = append(parts, "\"f3\":"+_dn(float64(o.F3)))
	parts = append(parts, "\"f4\":"+string(byte(34)) + _db(o.F4) + string(byte(34)))
	parts = append(parts, "\"f5\":"+_ds(o.F5))
	parts = append(parts, "\"f6\":"+_dbool(o.F6))
	parts = append(parts, "\"f7\":"+strconv.Itoa(int(o.F7)))
	parts = append(parts, "\"f8\":"+strconv.Itoa(int(o.F8)))
	parts = append(parts, "\"f9\":"+strconv.Itoa(int(o.F9)))
	parts = append(parts, "\"f10\":"+_di(o.F10))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTen05(o Ten05) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+string(byte(34)) + _db(o.F1) + string(byte(34)))
	parts = append(parts, "\"f2\":"+_ds(o.F2))
	parts = append(parts, "\"f3\":"+_dbool(o.F3))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	parts = append(parts, "\"f6\":"+strconv.Itoa(int(o.F6)))
	parts = append(parts, "\"f7\":"+_di(o.F7))
	parts = append(parts, "\"f8\":"+strconv.Itoa(int(o.F8)))
	parts = append(parts, "\"f9\":"+strconv.Itoa(int(o.F9)))
	parts = append(parts, "\"f10\":"+strconv.Itoa(int(o.F10)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrString(o ArrString) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrInt32(o ArrInt32) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrBoolean(o ArrBoolean) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _dbool(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrFloat64(o ArrFloat64) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrBytes(o ArrBytes) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"[" + strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, string(byte(34)) + _db(e) + string(byte(34))) }; return arr }(), ",") + "]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrInt64(o ArrInt64) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _di(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpArrUint64(o ArrUint64) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _du(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMultiArr1(o MultiArr1) string {
	parts := []string{}
	parts = append(parts, "\"names\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Names { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"scores\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Scores { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMultiArr2(o MultiArr2) string {
	parts := []string{}
	parts = append(parts, "\"flags\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Flags { arr = append(arr, _dbool(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"values\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Values { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]")
	parts = append(parts, "\"payload\":"+"[" + strings.Join(func() []string { var arr []string; for _, e := range o.Payload { arr = append(arr, string(byte(34)) + _db(e) + string(byte(34))) }; return arr }(), ",") + "]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMultiArr3(o MultiArr3) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.A { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"b\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.B { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]")
	parts = append(parts, "\"c\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.C { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMultiArr4(o MultiArr4) string {
	parts := []string{}
	parts = append(parts, "\"ids\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Ids { arr = append(arr, _di(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"tags\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Tags { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMultiArr5(o MultiArr5) string {
	parts := []string{}
	parts = append(parts, "\"xs\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Xs { arr = append(arr, _du(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"ys\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Ys { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]")
	parts = append(parts, "\"zs\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Zs { arr = append(arr, _dbool(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo1(o OptCombo1) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+_ds(o.Req))
	if o.Opt_a != nil { parts = append(parts, "\"opt_a\":"+strconv.Itoa(int(*o.Opt_a))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo2(o OptCombo2) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+_ds(o.Req))
	if o.Opt_a != nil { parts = append(parts, "\"opt_a\":"+strconv.Itoa(int(*o.Opt_a))) }
	if o.Opt_b != nil { parts = append(parts, "\"opt_b\":"+_dbool(*o.Opt_b)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo3(o OptCombo3) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+_ds(o.Req))
	if o.Opt_a != nil { parts = append(parts, "\"opt_a\":"+strconv.Itoa(int(*o.Opt_a))) }
	if o.Opt_b != nil { parts = append(parts, "\"opt_b\":"+_dbool(*o.Opt_b)) }
	if o.Opt_c != nil { parts = append(parts, "\"opt_c\":"+_dn(float64(*o.Opt_c))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo4(o OptCombo4) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+strconv.Itoa(int(o.Req)))
	if o.Opt_a != nil { parts = append(parts, "\"opt_a\":"+_ds(*o.Opt_a)) }
	if o.Opt_b != nil { parts = append(parts, "\"opt_b\":"+string(byte(34)) + _db(o.Opt_b) + string(byte(34))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo5(o OptCombo5) string {
	parts := []string{}
	parts = append(parts, "\"req1\":"+_ds(o.Req1))
	parts = append(parts, "\"req2\":"+strconv.Itoa(int(o.Req2)))
	if o.Opt_a != nil { parts = append(parts, "\"opt_a\":"+_dbool(*o.Opt_a)) }
	if o.Opt_b != nil { parts = append(parts, "\"opt_b\":"+_dn(float64(*o.Opt_b))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo6(o OptCombo6) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+_ds(o.Req))
	if o.Opt_s != nil { parts = append(parts, "\"opt_s\":"+_ds(*o.Opt_s)) }
	if o.Opt_i != nil { parts = append(parts, "\"opt_i\":"+strconv.Itoa(int(*o.Opt_i))) }
	if o.Opt_f != nil { parts = append(parts, "\"opt_f\":"+_dn(float64(*o.Opt_f))) }
	if o.Opt_b != nil { parts = append(parts, "\"opt_b\":"+string(byte(34)) + _db(o.Opt_b) + string(byte(34))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo7(o OptCombo7) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+_di(o.Req))
	if o.Opt_u64 != nil { parts = append(parts, "\"opt_u64\":"+_du(*o.Opt_u64)) }
	if o.Opt_str != nil { parts = append(parts, "\"opt_str\":"+_ds(*o.Opt_str)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo8(o OptCombo8) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+_ds(o.A))
	if o.B != nil { parts = append(parts, "\"b\":"+strconv.Itoa(int(*o.B))) }
	if o.C != nil { parts = append(parts, "\"c\":"+_dn(float64(*o.C))) }
	if o.D != nil { parts = append(parts, "\"d\":"+_dbool(*o.D)) }
	if o.E != nil { parts = append(parts, "\"e\":"+string(byte(34)) + _db(o.E) + string(byte(34))) }
	if o.F != nil { parts = append(parts, "\"f\":"+_di(*o.F)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo9(o OptCombo9) string {
	parts := []string{}
	parts = append(parts, "\"id\":"+_ds(o.Id))
	if o.Name != nil { parts = append(parts, "\"name\":"+_ds(*o.Name)) }
	if o.Age != nil { parts = append(parts, "\"age\":"+strconv.Itoa(int(*o.Age))) }
	if o.Score != nil { parts = append(parts, "\"score\":"+_dn(float64(*o.Score))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptCombo10(o OptCombo10) string {
	parts := []string{}
	parts = append(parts, "\"code\":"+strconv.Itoa(int(o.Code)))
	if o.Msg != nil { parts = append(parts, "\"msg\":"+_ds(*o.Msg)) }
	if o.Detail != nil { parts = append(parts, "\"detail\":"+_ds(*o.Detail)) }
	if o.Retry != nil { parts = append(parts, "\"retry\":"+_dbool(*o.Retry)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestInner(o NestInner) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpInner(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestCoord(o NestCoord) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpCoord(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestIdVal(o NestIdVal) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpIdVal(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestLabel(o NestLabel) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpLabel(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestMoney(o NestMoney) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpMoney(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestRange32(o NestRange32) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpRange32(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestAddr(o NestAddr) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpAddr(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestPoint3(o NestPoint3) string {
	parts := []string{}
	parts = append(parts, "\"nested\":"+dumpPoint3(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestInner(o OptNestInner) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpInner(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestCoord(o OptNestCoord) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpCoord(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestIdVal(o OptNestIdVal) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpIdVal(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestLabel(o OptNestLabel) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpLabel(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestMoney(o OptNestMoney) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpMoney(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestRange32(o OptNestRange32) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpRange32(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestAddr(o OptNestAddr) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpAddr(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptNestPoint3(o OptNestPoint3) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpPoint3(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpModelArr1(o ModelArr1) string {
	parts := []string{}
	parts = append(parts, "\"points\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Points { arr = append(arr, dumpInner(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpModelArr2(o ModelArr2) string {
	parts := []string{}
	parts = append(parts, "\"coords\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Coords { arr = append(arr, dumpCoord(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpModelArr3(o ModelArr3) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, dumpIdVal(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"tag\":"+_ds(o.Tag))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpModelArr4(o ModelArr4) string {
	parts := []string{}
	parts = append(parts, "\"labels\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Labels { arr = append(arr, dumpLabel(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"count\":"+strconv.Itoa(int(o.Count)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpModelArr5(o ModelArr5) string {
	parts := []string{}
	parts = append(parts, "\"arr\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Arr { arr = append(arr, dumpMoney(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"bs\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Bs { arr = append(arr, dumpAddr(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix01(o Mix01) string {
	parts := []string{}
	parts = append(parts, "\"name\":"+_ds(o.Name))
	parts = append(parts, "\"value\":"+strconv.Itoa(int(o.Value)))
	parts = append(parts, "\"point\":"+dumpInner(o.Point))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix02(o Mix02) string {
	parts := []string{}
	parts = append(parts, "\"id\":"+_ds(o.Id))
	parts = append(parts, "\"loc\":"+dumpCoord(o.Loc))
	parts = append(parts, "\"tags\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Tags { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix03(o Mix03) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	parts = append(parts, "\"value_range\":"+dumpRange32(o.Value_range))
	parts = append(parts, "\"active\":"+_dbool(o.Active))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix04(o Mix04) string {
	parts := []string{}
	parts = append(parts, "\"title\":"+_ds(o.Title))
	parts = append(parts, "\"price\":"+dumpMoney(o.Price))
	parts = append(parts, "\"inStock\":"+_dbool(o.InStock))
	parts = append(parts, "\"rating\":"+_dn(float64(o.Rating)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix05(o Mix05) string {
	parts := []string{}
	parts = append(parts, "\"addr\":"+dumpAddr(o.Addr))
	parts = append(parts, "\"coords\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Coords { arr = append(arr, dumpCoord(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix06(o Mix06) string {
	parts := []string{}
	parts = append(parts, "\"name\":"+_ds(o.Name))
	parts = append(parts, "\"age\":"+strconv.Itoa(int(o.Age)))
	if o.Address != nil { parts = append(parts, "\"address\":"+dumpAddr(*o.Address)) }
	if o.Email != nil { parts = append(parts, "\"email\":"+_ds(*o.Email)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix07(o Mix07) string {
	parts := []string{}
	parts = append(parts, "\"origin\":"+dumpPoint3(o.Origin))
	parts = append(parts, "\"dest\":"+dumpPoint3(o.Dest))
	parts = append(parts, "\"distance\":"+_dn(float64(o.Distance)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix08(o Mix08) string {
	parts := []string{}
	parts = append(parts, "\"keys\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Keys { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"values\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Values { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]")
	if o.Meta != nil { parts = append(parts, "\"meta\":"+dumpLabel(*o.Meta)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix09(o Mix09) string {
	parts := []string{}
	parts = append(parts, "\"id\":"+_di(o.Id))
	parts = append(parts, "\"payload\":"+string(byte(34)) + _db(o.Payload) + string(byte(34)))
	parts = append(parts, "\"checksum\":"+strconv.Itoa(int(o.Checksum)))
	if o.Prev != nil { parts = append(parts, "\"prev\":"+dumpIdVal(*o.Prev)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix10(o Mix10) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"total\":"+strconv.Itoa(int(o.Total)))
	parts = append(parts, "\"avg\":"+_dn(float64(o.Avg)))
	parts = append(parts, "\"value_range\":"+dumpRange32(o.Value_range))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix11(o Mix11) string {
	parts := []string{}
	parts = append(parts, "\"name\":"+_ds(o.Name))
	parts = append(parts, "\"values\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Values { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]")
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpInner(*o.Nested)) }
	if o.Flag != nil { parts = append(parts, "\"flag\":"+_dbool(*o.Flag)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix12(o Mix12) string {
	parts := []string{}
	parts = append(parts, "\"header\":"+_ds(o.Header))
	parts = append(parts, "\"entries\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Entries { arr = append(arr, dumpIdVal(e)) }; return arr }(), ",")+"]")
	if o.Footer != nil { parts = append(parts, "\"footer\":"+_ds(*o.Footer)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix13(o Mix13) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_dn(float64(o.B)))
	parts = append(parts, "\"c\":"+_ds(o.C))
	parts = append(parts, "\"d\":"+_dbool(o.D))
	parts = append(parts, "\"e\":"+string(byte(34)) + _db(o.E) + string(byte(34)))
	parts = append(parts, "\"nested\":"+dumpInner(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix14(o Mix14) string {
	parts := []string{}
	parts = append(parts, "\"amounts\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Amounts { arr = append(arr, dumpMoney(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"total\":"+_di(o.Total))
	parts = append(parts, "\"currency\":"+_ds(o.Currency))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpMix15(o Mix15) string {
	parts := []string{}
	parts = append(parts, "\"src_addr\":"+dumpAddr(o.Src_addr))
	parts = append(parts, "\"dst_addr\":"+dumpAddr(o.Dst_addr))
	parts = append(parts, "\"distance\":"+_dn(float64(o.Distance)))
	parts = append(parts, "\"duration\":"+_dn(float64(o.Duration)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpAllOpt1(o AllOpt1) string {
	parts := []string{}
	if o.A != nil { parts = append(parts, "\"a\":"+_ds(*o.A)) }
	if o.B != nil { parts = append(parts, "\"b\":"+strconv.Itoa(int(*o.B))) }
	if o.C != nil { parts = append(parts, "\"c\":"+_dbool(*o.C)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpAllOpt2(o AllOpt2) string {
	parts := []string{}
	if o.X != nil { parts = append(parts, "\"x\":"+_dn(float64(*o.X))) }
	if o.Y != nil { parts = append(parts, "\"y\":"+string(byte(34)) + _db(o.Y) + string(byte(34))) }
	if o.Z != nil { parts = append(parts, "\"z\":"+_di(*o.Z)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpAllOpt3(o AllOpt3) string {
	parts := []string{}
	if o.Name != nil { parts = append(parts, "\"name\":"+_ds(*o.Name)) }
	if o.Age != nil { parts = append(parts, "\"age\":"+strconv.Itoa(int(*o.Age))) }
	if o.Score != nil { parts = append(parts, "\"score\":"+_dn(float64(*o.Score))) }
	if o.Active != nil { parts = append(parts, "\"active\":"+_dbool(*o.Active)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpAllOpt4(o AllOpt4) string {
	parts := []string{}
	if o.A != nil { parts = append(parts, "\"a\":"+strconv.Itoa(int(*o.A))) }
	if o.B != nil { parts = append(parts, "\"b\":"+_du(*o.B)) }
	if o.C != nil { parts = append(parts, "\"c\":"+strconv.Itoa(int(*o.C))) }
	if o.D != nil { parts = append(parts, "\"d\":"+_ds(*o.D)) }
	if o.E != nil { parts = append(parts, "\"e\":"+string(byte(34)) + _db(o.E) + string(byte(34))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpAllOpt5(o AllOpt5) string {
	parts := []string{}
	if o.P != nil { parts = append(parts, "\"p\":"+dumpInner(*o.P)) }
	if o.Q != nil { parts = append(parts, "\"q\":"+_ds(*o.Q)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpRecList(o RecList) string {
	parts := []string{}
	parts = append(parts, "\"value\":"+strconv.Itoa(int(o.Value)))
	if o.Next != nil { parts = append(parts, "\"next\":"+dumpRecList(*o.Next)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpRecTree(o RecTree) string {
	parts := []string{}
	parts = append(parts, "\"value\":"+_ds(o.Value))
	if o.Left_node != nil { parts = append(parts, "\"left_node\":"+dumpRecTree(*o.Left_node)) }
	if o.Right_node != nil { parts = append(parts, "\"right_node\":"+dumpRecTree(*o.Right_node)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpRecChain(o RecChain) string {
	parts := []string{}
	parts = append(parts, "\"id\":"+strconv.Itoa(int(o.Id)))
	parts = append(parts, "\"label\":"+_ds(o.Label))
	if o.Next != nil { parts = append(parts, "\"next\":"+dumpRecChain(*o.Next)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpRecWrap(o RecWrap) string {
	parts := []string{}
	parts = append(parts, "\"payload\":"+string(byte(34)) + _db(o.Payload) + string(byte(34)))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpRecWrap(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpRecWide(o RecWide) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+strconv.Itoa(int(o.A)))
	parts = append(parts, "\"b\":"+_ds(o.B))
	parts = append(parts, "\"c\":"+_dn(float64(o.C)))
	if o.Child != nil { parts = append(parts, "\"child\":"+dumpRecWide(*o.Child)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpWide20(o Wide20) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_ds(o.F1))
	parts = append(parts, "\"f2\":"+_dbool(o.F2))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	parts = append(parts, "\"f6\":"+_di(o.F6))
	parts = append(parts, "\"f7\":"+strconv.Itoa(int(o.F7)))
	parts = append(parts, "\"f8\":"+strconv.Itoa(int(o.F8)))
	parts = append(parts, "\"f9\":"+strconv.Itoa(int(o.F9)))
	parts = append(parts, "\"f10\":"+_du(o.F10))
	parts = append(parts, "\"f11\":"+_dn(float64(o.F11)))
	parts = append(parts, "\"f12\":"+_dn(float64(o.F12)))
	parts = append(parts, "\"f13\":"+string(byte(34)) + _db(o.F13) + string(byte(34)))
	parts = append(parts, "\"f14\":"+_ds(o.F14))
	parts = append(parts, "\"f15\":"+_dbool(o.F15))
	parts = append(parts, "\"f16\":"+strconv.Itoa(int(o.F16)))
	parts = append(parts, "\"f17\":"+strconv.Itoa(int(o.F17)))
	parts = append(parts, "\"f18\":"+strconv.Itoa(int(o.F18)))
	parts = append(parts, "\"f19\":"+_di(o.F19))
	parts = append(parts, "\"f20\":"+strconv.Itoa(int(o.F20)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpWide25(o Wide25) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+_du(o.F3))
	parts = append(parts, "\"f4\":"+_dn(float64(o.F4)))
	parts = append(parts, "\"f5\":"+_dn(float64(o.F5)))
	parts = append(parts, "\"f6\":"+string(byte(34)) + _db(o.F6) + string(byte(34)))
	parts = append(parts, "\"f7\":"+_ds(o.F7))
	parts = append(parts, "\"f8\":"+_dbool(o.F8))
	parts = append(parts, "\"f9\":"+strconv.Itoa(int(o.F9)))
	parts = append(parts, "\"f10\":"+strconv.Itoa(int(o.F10)))
	parts = append(parts, "\"f11\":"+strconv.Itoa(int(o.F11)))
	parts = append(parts, "\"f12\":"+_di(o.F12))
	parts = append(parts, "\"f13\":"+strconv.Itoa(int(o.F13)))
	parts = append(parts, "\"f14\":"+strconv.Itoa(int(o.F14)))
	parts = append(parts, "\"f15\":"+strconv.Itoa(int(o.F15)))
	parts = append(parts, "\"f16\":"+_du(o.F16))
	parts = append(parts, "\"f17\":"+_dn(float64(o.F17)))
	parts = append(parts, "\"f18\":"+_dn(float64(o.F18)))
	parts = append(parts, "\"f19\":"+string(byte(34)) + _db(o.F19) + string(byte(34)))
	parts = append(parts, "\"f20\":"+_ds(o.F20))
	parts = append(parts, "\"f21\":"+_dbool(o.F21))
	parts = append(parts, "\"f22\":"+strconv.Itoa(int(o.F22)))
	parts = append(parts, "\"f23\":"+strconv.Itoa(int(o.F23)))
	parts = append(parts, "\"f24\":"+strconv.Itoa(int(o.F24)))
	parts = append(parts, "\"f25\":"+_di(o.F25))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpWide30(o Wide30) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+_dbool(o.F1))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+strconv.Itoa(int(o.F4)))
	parts = append(parts, "\"f5\":"+_di(o.F5))
	parts = append(parts, "\"f6\":"+strconv.Itoa(int(o.F6)))
	parts = append(parts, "\"f7\":"+strconv.Itoa(int(o.F7)))
	parts = append(parts, "\"f8\":"+strconv.Itoa(int(o.F8)))
	parts = append(parts, "\"f9\":"+_du(o.F9))
	parts = append(parts, "\"f10\":"+_dn(float64(o.F10)))
	parts = append(parts, "\"f11\":"+_dn(float64(o.F11)))
	parts = append(parts, "\"f12\":"+string(byte(34)) + _db(o.F12) + string(byte(34)))
	parts = append(parts, "\"f13\":"+_ds(o.F13))
	parts = append(parts, "\"f14\":"+_dbool(o.F14))
	parts = append(parts, "\"f15\":"+strconv.Itoa(int(o.F15)))
	parts = append(parts, "\"f16\":"+strconv.Itoa(int(o.F16)))
	parts = append(parts, "\"f17\":"+strconv.Itoa(int(o.F17)))
	parts = append(parts, "\"f18\":"+_di(o.F18))
	parts = append(parts, "\"f19\":"+strconv.Itoa(int(o.F19)))
	parts = append(parts, "\"f20\":"+strconv.Itoa(int(o.F20)))
	parts = append(parts, "\"f21\":"+strconv.Itoa(int(o.F21)))
	parts = append(parts, "\"f22\":"+_du(o.F22))
	parts = append(parts, "\"f23\":"+_dn(float64(o.F23)))
	parts = append(parts, "\"f24\":"+_dn(float64(o.F24)))
	parts = append(parts, "\"f25\":"+string(byte(34)) + _db(o.F25) + string(byte(34)))
	parts = append(parts, "\"f26\":"+_ds(o.F26))
	parts = append(parts, "\"f27\":"+_dbool(o.F27))
	parts = append(parts, "\"f28\":"+strconv.Itoa(int(o.F28)))
	parts = append(parts, "\"f29\":"+strconv.Itoa(int(o.F29)))
	parts = append(parts, "\"f30\":"+strconv.Itoa(int(o.F30)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpWide35(o Wide35) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+_du(o.F2))
	parts = append(parts, "\"f3\":"+_dn(float64(o.F3)))
	parts = append(parts, "\"f4\":"+_dn(float64(o.F4)))
	parts = append(parts, "\"f5\":"+string(byte(34)) + _db(o.F5) + string(byte(34)))
	parts = append(parts, "\"f6\":"+_ds(o.F6))
	parts = append(parts, "\"f7\":"+_dbool(o.F7))
	parts = append(parts, "\"f8\":"+strconv.Itoa(int(o.F8)))
	parts = append(parts, "\"f9\":"+strconv.Itoa(int(o.F9)))
	parts = append(parts, "\"f10\":"+strconv.Itoa(int(o.F10)))
	parts = append(parts, "\"f11\":"+_di(o.F11))
	parts = append(parts, "\"f12\":"+strconv.Itoa(int(o.F12)))
	parts = append(parts, "\"f13\":"+strconv.Itoa(int(o.F13)))
	parts = append(parts, "\"f14\":"+strconv.Itoa(int(o.F14)))
	parts = append(parts, "\"f15\":"+_du(o.F15))
	parts = append(parts, "\"f16\":"+_dn(float64(o.F16)))
	parts = append(parts, "\"f17\":"+_dn(float64(o.F17)))
	parts = append(parts, "\"f18\":"+string(byte(34)) + _db(o.F18) + string(byte(34)))
	parts = append(parts, "\"f19\":"+_ds(o.F19))
	parts = append(parts, "\"f20\":"+_dbool(o.F20))
	parts = append(parts, "\"f21\":"+strconv.Itoa(int(o.F21)))
	parts = append(parts, "\"f22\":"+strconv.Itoa(int(o.F22)))
	parts = append(parts, "\"f23\":"+strconv.Itoa(int(o.F23)))
	parts = append(parts, "\"f24\":"+_di(o.F24))
	parts = append(parts, "\"f25\":"+strconv.Itoa(int(o.F25)))
	parts = append(parts, "\"f26\":"+strconv.Itoa(int(o.F26)))
	parts = append(parts, "\"f27\":"+strconv.Itoa(int(o.F27)))
	parts = append(parts, "\"f28\":"+_du(o.F28))
	parts = append(parts, "\"f29\":"+_dn(float64(o.F29)))
	parts = append(parts, "\"f30\":"+_dn(float64(o.F30)))
	parts = append(parts, "\"f31\":"+string(byte(34)) + _db(o.F31) + string(byte(34)))
	parts = append(parts, "\"f32\":"+_ds(o.F32))
	parts = append(parts, "\"f33\":"+_dbool(o.F33))
	parts = append(parts, "\"f34\":"+strconv.Itoa(int(o.F34)))
	parts = append(parts, "\"f35\":"+strconv.Itoa(int(o.F35)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpWide40(o Wide40) string {
	parts := []string{}
	parts = append(parts, "\"f1\":"+strconv.Itoa(int(o.F1)))
	parts = append(parts, "\"f2\":"+strconv.Itoa(int(o.F2)))
	parts = append(parts, "\"f3\":"+strconv.Itoa(int(o.F3)))
	parts = append(parts, "\"f4\":"+_di(o.F4))
	parts = append(parts, "\"f5\":"+strconv.Itoa(int(o.F5)))
	parts = append(parts, "\"f6\":"+strconv.Itoa(int(o.F6)))
	parts = append(parts, "\"f7\":"+strconv.Itoa(int(o.F7)))
	parts = append(parts, "\"f8\":"+_du(o.F8))
	parts = append(parts, "\"f9\":"+_dn(float64(o.F9)))
	parts = append(parts, "\"f10\":"+_dn(float64(o.F10)))
	parts = append(parts, "\"f11\":"+string(byte(34)) + _db(o.F11) + string(byte(34)))
	parts = append(parts, "\"f12\":"+_ds(o.F12))
	parts = append(parts, "\"f13\":"+_dbool(o.F13))
	parts = append(parts, "\"f14\":"+strconv.Itoa(int(o.F14)))
	parts = append(parts, "\"f15\":"+strconv.Itoa(int(o.F15)))
	parts = append(parts, "\"f16\":"+strconv.Itoa(int(o.F16)))
	parts = append(parts, "\"f17\":"+_di(o.F17))
	parts = append(parts, "\"f18\":"+strconv.Itoa(int(o.F18)))
	parts = append(parts, "\"f19\":"+strconv.Itoa(int(o.F19)))
	parts = append(parts, "\"f20\":"+strconv.Itoa(int(o.F20)))
	parts = append(parts, "\"f21\":"+_du(o.F21))
	parts = append(parts, "\"f22\":"+_dn(float64(o.F22)))
	parts = append(parts, "\"f23\":"+_dn(float64(o.F23)))
	parts = append(parts, "\"f24\":"+string(byte(34)) + _db(o.F24) + string(byte(34)))
	parts = append(parts, "\"f25\":"+_ds(o.F25))
	parts = append(parts, "\"f26\":"+_dbool(o.F26))
	parts = append(parts, "\"f27\":"+strconv.Itoa(int(o.F27)))
	parts = append(parts, "\"f28\":"+strconv.Itoa(int(o.F28)))
	parts = append(parts, "\"f29\":"+strconv.Itoa(int(o.F29)))
	parts = append(parts, "\"f30\":"+_di(o.F30))
	parts = append(parts, "\"f31\":"+strconv.Itoa(int(o.F31)))
	parts = append(parts, "\"f32\":"+strconv.Itoa(int(o.F32)))
	parts = append(parts, "\"f33\":"+strconv.Itoa(int(o.F33)))
	parts = append(parts, "\"f34\":"+_du(o.F34))
	parts = append(parts, "\"f35\":"+_dn(float64(o.F35)))
	parts = append(parts, "\"f36\":"+_dn(float64(o.F36)))
	parts = append(parts, "\"f37\":"+string(byte(34)) + _db(o.F37) + string(byte(34)))
	parts = append(parts, "\"f38\":"+_ds(o.F38))
	parts = append(parts, "\"f39\":"+_dbool(o.F39))
	parts = append(parts, "\"f40\":"+strconv.Itoa(int(o.F40)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeEmpty(o EdgeEmpty) string {
	parts := []string{}

	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeOneOpt(o EdgeOneOpt) string {
	parts := []string{}
	if o.Maybe != nil { parts = append(parts, "\"maybe\":"+_ds(*o.Maybe)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeBigNums(o EdgeBigNums) string {
	parts := []string{}
	parts = append(parts, "\"i8\":"+strconv.Itoa(int(o.I8)))
	parts = append(parts, "\"i16\":"+strconv.Itoa(int(o.I16)))
	parts = append(parts, "\"i32\":"+strconv.Itoa(int(o.I32)))
	parts = append(parts, "\"i64\":"+_di(o.I64))
	parts = append(parts, "\"u8\":"+strconv.Itoa(int(o.U8)))
	parts = append(parts, "\"u16\":"+strconv.Itoa(int(o.U16)))
	parts = append(parts, "\"u32\":"+strconv.Itoa(int(o.U32)))
	parts = append(parts, "\"u64\":"+_du(o.U64))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeZeroVals(o EdgeZeroVals) string {
	parts := []string{}
	parts = append(parts, "\"s\":"+_ds(o.S))
	parts = append(parts, "\"i\":"+strconv.Itoa(int(o.I)))
	parts = append(parts, "\"f\":"+_dn(float64(o.F)))
	parts = append(parts, "\"b\":"+_dbool(o.B))
	parts = append(parts, "\"by_field\":"+string(byte(34)) + _db(o.By_field) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeNullable(o EdgeNullable) string {
	parts := []string{}
	if o.A != nil { parts = append(parts, "\"a\":"+_ds(*o.A)) }
	if o.B != nil { parts = append(parts, "\"b\":"+strconv.Itoa(int(*o.B))) }
	if o.C != nil { parts = append(parts, "\"c\":"+dumpInner(*o.C)) }
	if o.D != nil { parts = append(parts, "\"d\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.D { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]") }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeNegZero(o EdgeNegZero) string {
	parts := []string{}
	parts = append(parts, "\"v\":"+_dn(float64(o.V)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeNullByte(o EdgeNullByte) string {
	parts := []string{}
	parts = append(parts, "\"s\":"+_ds(o.S))
	parts = append(parts, "\"b\":"+string(byte(34)) + _db(o.B) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeBoundary(o EdgeBoundary) string {
	parts := []string{}
	parts = append(parts, "\"i32_neg129\":"+strconv.Itoa(int(o.I32_neg129)))
	parts = append(parts, "\"i32_128\":"+strconv.Itoa(int(o.I32_128)))
	parts = append(parts, "\"i32_256\":"+strconv.Itoa(int(o.I32_256)))
	parts = append(parts, "\"i32_65536\":"+strconv.Itoa(int(o.I32_65536)))
	parts = append(parts, "\"i32_neg32769\":"+strconv.Itoa(int(o.I32_neg32769)))
	parts = append(parts, "\"u32_65536\":"+strconv.Itoa(int(o.U32_65536)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeStrLen(o EdgeStrLen) string {
	parts := []string{}
	parts = append(parts, "\"s31\":"+_ds(o.S31))
	parts = append(parts, "\"s32\":"+_ds(o.S32))
	parts = append(parts, "\"s255\":"+_ds(o.S255))
	parts = append(parts, "\"s256\":"+_ds(o.S256))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeBytesLen(o EdgeBytesLen) string {
	parts := []string{}
	parts = append(parts, "\"b31\":"+string(byte(34)) + _db(o.B31) + string(byte(34)))
	parts = append(parts, "\"b32\":"+string(byte(34)) + _db(o.B32) + string(byte(34)))
	parts = append(parts, "\"b255\":"+string(byte(34)) + _db(o.B255) + string(byte(34)))
	parts = append(parts, "\"b256\":"+string(byte(34)) + _db(o.B256) + string(byte(34)))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeArrEmpty(o EdgeArrEmpty) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpEdgeArrBoundary(o EdgeArrBoundary) string {
	parts := []string{}
	parts = append(parts, "\"a15\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.A15 { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]")
	parts = append(parts, "\"a16\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.A16 { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]")
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptArr1(o OptArr1) string {
	parts := []string{}
	parts = append(parts, "\"req\":"+_ds(o.Req))
	if o.Items != nil { parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, strconv.Itoa(int(e))) }; return arr }(), ",")+"]") }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptArr2(o OptArr2) string {
	parts := []string{}
	parts = append(parts, "\"id\":"+strconv.Itoa(int(o.Id)))
	if o.Names != nil { parts = append(parts, "\"names\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Names { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]") }
	if o.Flags != nil { parts = append(parts, "\"flags\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Flags { arr = append(arr, _dbool(e)) }; return arr }(), ",")+"]") }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptArr3(o OptArr3) string {
	parts := []string{}
	if o.A != nil { parts = append(parts, "\"a\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.A { arr = append(arr, _ds(e)) }; return arr }(), ",")+"]") }
	if o.B != nil { parts = append(parts, "\"b\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.B { arr = append(arr, _dn(float64(e))) }; return arr }(), ",")+"]") }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptArr4(o OptArr4) string {
	parts := []string{}
	parts = append(parts, "\"payload\":"+string(byte(34)) + _db(o.Payload) + string(byte(34)))
	if o.Chunks != nil { parts = append(parts, "\"chunks\":"+"[" + strings.Join(func() []string { var arr []string; for _, e := range o.Chunks { arr = append(arr, string(byte(34)) + _db(e) + string(byte(34))) }; return arr }(), ",") + "]") }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpOptArr5(o OptArr5) string {
	parts := []string{}
	if o.Models != nil { parts = append(parts, "\"models\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Models { arr = append(arr, dumpInner(e)) }; return arr }(), ",")+"]") }
	parts = append(parts, "\"name\":"+_ds(o.Name))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOpt1(o NestOpt1) string {
	parts := []string{}
	parts = append(parts, "\"outer\":"+dumpLabel(o.Outer))
	parts = append(parts, "\"name\":"+_ds(o.Name))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOpt2(o NestOpt2) string {
	parts := []string{}
	if o.A != nil { parts = append(parts, "\"a\":"+dumpIdVal(*o.A)) }
	if o.B != nil { parts = append(parts, "\"b\":"+dumpIdVal(*o.B)) }
	if o.C != nil { parts = append(parts, "\"c\":"+dumpIdVal(*o.C)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOpt3(o NestOpt3) string {
	parts := []string{}
	parts = append(parts, "\"money\":"+dumpMoney(o.Money))
	if o.Value_range != nil { parts = append(parts, "\"value_range\":"+dumpRange32(*o.Value_range)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOpt4(o NestOpt4) string {
	parts := []string{}
	if o.Addr != nil { parts = append(parts, "\"addr\":"+dumpAddr(*o.Addr)) }
	if o.Coord != nil { parts = append(parts, "\"coord\":"+dumpCoord(*o.Coord)) }
	parts = append(parts, "\"name\":"+_ds(o.Name))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOpt5(o NestOpt5) string {
	parts := []string{}
	parts = append(parts, "\"point\":"+dumpPoint3(o.Point))
	parts = append(parts, "\"addr\":"+dumpAddr(o.Addr))
	if o.Label != nil { parts = append(parts, "\"label\":"+dumpLabel(*o.Label)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOptInner1(o NestOptInner1) string {
	parts := []string{}
	parts = append(parts, "\"tag\":"+_ds(o.Tag))
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpOptInner(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOptInner2(o NestOptInner2) string {
	parts := []string{}
	parts = append(parts, "\"tag\":"+_ds(o.Tag))
	parts = append(parts, "\"nested\":"+dumpOptInner(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpNestOptInner3(o NestOptInner3) string {
	parts := []string{}
	if o.Outer != nil { parts = append(parts, "\"outer\":"+dumpOptInner(*o.Outer)) }
	if o.Nested != nil { parts = append(parts, "\"nested\":"+dumpOptInner(*o.Nested)) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest1(o DeepNest1) string {
	parts := []string{}
	parts = append(parts, "\"label\":"+_ds(o.Label))
	parts = append(parts, "\"nested\":"+dumpAddr(o.Nested))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest2(o DeepNest2) string {
	parts := []string{}
	parts = append(parts, "\"name\":"+_ds(o.Name))
	parts = append(parts, "\"money\":"+dumpMoney(o.Money))
	parts = append(parts, "\"addr\":"+dumpAddr(o.Addr))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest3(o DeepNest3) string {
	parts := []string{}
	parts = append(parts, "\"title\":"+_ds(o.Title))
	parts = append(parts, "\"point\":"+dumpPoint3(o.Point))
	parts = append(parts, "\"value_range\":"+dumpRange32(o.Value_range))
	parts = append(parts, "\"money\":"+dumpMoney(o.Money))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest4(o DeepNest4) string {
	parts := []string{}
	parts = append(parts, "\"coords\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Coords { arr = append(arr, dumpCoord(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"nested\":"+dumpInner(o.Nested))
	parts = append(parts, "\"tag\":"+_ds(o.Tag))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest5(o DeepNest5) string {
	parts := []string{}
	parts = append(parts, "\"labels\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Labels { arr = append(arr, dumpLabel(e)) }; return arr }(), ",")+"]")
	parts = append(parts, "\"money\":"+dumpMoney(o.Money))
	parts = append(parts, "\"name\":"+_ds(o.Name))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest6(o DeepNest6) string {
	parts := []string{}
	parts = append(parts, "\"items\":"+"["+strings.Join(func() []string { var arr []string; for _, e := range o.Items { arr = append(arr, dumpIdVal(e)) }; return arr }(), ",")+"]")
	if o.Addr != nil { parts = append(parts, "\"addr\":"+dumpAddr(*o.Addr)) }
	parts = append(parts, "\"coord\":"+dumpCoord(o.Coord))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpDeepNest7(o DeepNest7) string {
	parts := []string{}
	parts = append(parts, "\"a\":"+dumpAddr(o.A))
	parts = append(parts, "\"b\":"+dumpAddr(o.B))
	parts = append(parts, "\"c\":"+dumpAddr(o.C))
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpTimestampEntry(o TimestampEntry) string {
	parts := []string{}
	parts = append(parts, "\"ts\":"+_di(o.Ts))
	parts = append(parts, "\"event\":"+_ds(o.Event))
	if o.Payload != nil { parts = append(parts, "\"payload\":"+string(byte(34)) + _db(o.Payload) + string(byte(34))) }
	return "{"+strings.Join(parts, ",")+"}"
}
func dumpConfigEntry(o ConfigEntry) string {
	parts := []string{}
	parts = append(parts, "\"key\":"+_ds(o.Key))
	if o.IntValue != nil { parts = append(parts, "\"intValue\":"+strconv.Itoa(int(*o.IntValue))) }
	if o.StrValue != nil { parts = append(parts, "\"strValue\":"+_ds(*o.StrValue)) }
	if o.BoolValue != nil { parts = append(parts, "\"boolValue\":"+_dbool(*o.BoolValue)) }
	if o.FloatValue != nil { parts = append(parts, "\"floatValue\":"+_dn(float64(*o.FloatValue))) }
	return "{"+strings.Join(parts, ",")+"}"
}
